### ISSUE TITLE
orafce make and make install doesn't work

### ISSUE THREAD

**Issue by chiragbhalodia** [orafce/orafce#106]
Hi,

I am trying to install orafce using following command on windows from source directory, I am getting following error:
C:\Work\orafce-master>make
makefile:24: ../../src/Makefile.global: No such file or directory
makefile:25: /contrib/contrib-global.mk: No such file or directory
make: *** No rule to make target `/contrib/contrib-global.mk'.  Stop.

I couldn't find Makefile.global or contrib folder.  Am I missing anything?

**Comment by okbob** [comment]
čt 14. 5. 2020 v 15:18 odesílatel chiragbhalodia <notifications@github.com>
napsal:

> Hi,
>
> I am trying to install orafce using following command on windows from
> source directory, I am getting following error:
> C:\Work\orafce-master>make
> makefile:24: ../../src/Makefile.global: No such file or directory
> makefile:25: /contrib/contrib-global.mk: No such file or directory
> make: *** No rule to make target `/contrib/contrib-global.mk'. Stop.
>
These steps are steps for build Orafce, not for installation.


> I couldn't find Makefile.global or contrib folder. Am I missing anything?
>
yes, you need to have to have Postgres devel environment. Build via
makefile works only on Unix systems, or Cygwin.

You need to look how to build or install Orafce on Windows. Linux (Unix)
build, installation is very different.

Pavel

**Comment by chiragbhalodia** [comment]
Thanks a lot for your reply. 
Finally, I found windows installation from following link:
http://okbob.blogspot.com/2019/10/precompiled-libraries-for-orafce-38-for.html
I could now add extension and invoke oracle functions so closing ticket.

**Comment by okbob** [comment]
čt 14. 5. 2020 v 16:51 odesílatel chiragbhalodia <notifications@github.com>
napsal:

> Thanks a lot for your reply.
> Finally, I found windows installation from following link:
>
> http://okbob.blogspot.com/2019/10/precompiled-libraries-for-orafce-38-for.html
> I could now add extension and invoke oracle functions so closing ticket.
>
super :)

Pavel
