### ISSUE TITLE
How to reproduce Windows UTL_FILE package problem (issue 49)? 

### ISSUE THREAD

**Issue by higuchi-daisuke** [orafce/orafce#107]
Hi, 

I have question about UTL_FILE package on Windows. 

I understand that UTL_FILE is not supported on Windows. 
I think the problem that caused it came from [this issuse](https://github.com/orafce/orafce/issues/49). 

I create PostgreSQL module and orafce module manually and test, but I could not reproduce the problem which was reported. 
And also I use manually created PostgreSQL modulde and published orafce module on https://okbob.blogspot.com/search?q=precompiled, but I could not reproduce. 
So, could you teach me how to reproduce Windows UTL_FILE problem to research the cause of this? 
And I want to know which minor version for PostgreSQL 9.5.xx was used to create published orafce dll. 

Notes:
- I use PostgreSQL 9.5.22 and orafce 3.6.0. 
- When compiling orafce, I fix Mkvcbuild.pm to solve some dependency. 
- I compile and test by using Visual Studio 2013 and 2015, but problem is not reproduced neither. 

Regards, 
Daisuke Higuchi

**Comment by okbob** [comment]
Hi

pá 22. 5. 2020 v 2:55 odesílatel Daisuke <notifications@github.com> napsal:

> Hi,
>
> I have question about UTL_FILE package on Windows.
>
> I understand that UTL_FILE is not supported on Windows.
> I think the problem that caused it came from this issuse
> <https://github.com/orafce/orafce/issues/49>.
>

yes

I create PostgreSQL module and orafce module manually and test, but I could
> not reproduce the problem which was reported.
> And also I use manually created PostgreSQL modulde and published orafce
> module on https://okbob.blogspot.com/search?q=precompiled, but I could
> not reproduce.
> So, could you teach me how to reproduce Windows UTL_FILE problem to
> research the cause of this?
> And I want to know which minor version for PostgreSQL 9.5.xx was used to
> create published orafce dll.
>
Without modification you cannot to repeat this issue, because there is
raised a exception so this functionality is not supported. If you remove
related line, then is possible so execution of some function from utl_file
crashes Postgres.


> Notes:
>
>    - I use PostgreSQL 9.5.22 and orafce 3.6.0.
>    - When compiling orafce, I fix Mkvcbuild.pm to solve some dependency.
>    - I compile and test by using Visual Studio 2013 and 2015, but problem
>    is not reproduced neither.
>
> I have windows 10, Visual Studio 2015, and if I remember I did these tests
on Postgres 10.

But I have to clean my build env to repeat these issue.

**Comment by okbob** [comment]
I tested it again, and in my environment and it ending by crash again.

How to repeat it

1. you need to compile Postgres from source code. Unfortunately last
released version is not possible to build on windows without removing some
code that breaks build process. I'll fix it this week.

2. you need to comment lines with text elog(ERROR, "utl_file package is not
supported on Microsoft Windows") in file.c

3. build and install orafce.dll

4. you can use tests from orafcesource/sql/files.sql

When I try to run function "select gen_file(utl_file.tmpdir());" in PgAdmin

I got a message "The application has lost the database connection" - that
is a signal so Postgres server crashed.

It was tested on Postgres 12, Windows 10, MSVS 2015





pá 22. 5. 2020 v 10:24 odesílatel Pavel Stehule <pavel.stehule@gmail.com>
napsal:

**Comment by higuchi-daisuke** [comment]
Hi, 
Thank you for sharing the details, but I haven't reproduced it yet. I will try a little more.

**Comment by okbob** [comment]
po 25. 5. 2020 v 14:13 odesílatel Daisuke <notifications@github.com> napsal:

> Hi,
> Thank you for sharing the details, but I haven't reproduced it yet. I will
> try a little more.
>
It's strange, but everything is possible :)

Pavel

**Comment by higuchi-daisuke** [comment]
Hi, 

When I use PostgreSQL 9.5.22 Windows binary from [EDB download site](https://wiki.postgresql.org/wiki/Getting_a_stack_trace_of_a_running_PostgreSQL_backend_on_Windows) and orafce 3.6.2 Windows binary [which you compiled](http://okbob.blogspot.com/2017/12/bugfix-of-precompiled-dll-of-orafce-362.html), I could reproduce. 
Using dependency walker, I confirmed that PostgreSQL 9.5.22 binary requires MSVCR120.DLL but orafce 3.6.2 binary requires VCRUNTIME140.DLL. 

Then, when I use PostgreSQL 11.8 Windows binary and the latest orafce which I compiled on Visual Studio 2017, I have no error. 
(To compile, commented out elog(ERROR, "utl_file package is not ...) in file.c and some function in orafce--3.12.sql. )
At this case, I confirmed that PostgreSQL 11.8 binary and latest orafce which I compiled require VCRUNTIME140.DLL. 

So, I think this problem is related to Visual Studio version, Windows SDK or something which are used to compile. 
How do you think about this? 
And could you teach me which runtime libraries are required by your PostgreSQL and orafce?

**Comment by okbob** [comment]
st 27. 5. 2020 v 3:41 odesílatel Daisuke <notifications@github.com> napsal:

> Hi,
>
> When I use PostgreSQL 9.5.22 Windows binary from EDB download site
> <https://wiki.postgresql.org/wiki/Getting_a_stack_trace_of_a_running_PostgreSQL_backend_on_Windows>
> and orafce 3.6.2 Windows binary which you compiled
> <http://okbob.blogspot.com/2017/12/bugfix-of-precompiled-dll-of-orafce-362.html>,
> I could reproduce.
> Using dependency walker, I confirmed that PostgreSQL 9.5.22 binary
> requires MSVCR120.DLL but orafce 3.6.2 binary requires VCRUNTIME140.DLL.
>
> Then, when I use PostgreSQL 11.8 Windows binary and the latest orafce
> which I compiled on Visual Studio 2017, I have no error.
> (To compile, commented out elog(ERROR, "utl_file package is not ...) in
> file.c and some function in orafce--3.12.sql. )
> At this case, I confirmed that PostgreSQL 11.8 binary and latest orafce
> which I compiled require VCRUNTIME140.DLL
>
So, I think this problem is related to Visual Studio version, Windows SDK
> or something which are used to compile.
> How do you think about this?
> And could you teach me which runtime libraries are required by your
> PostgreSQL and orafce?
>


I am looking on Postgres 12, and it depends on VCRUNTIME140.DLL

Orafce has ma dependency on VCRUNTIME140D.DLL - but D means DEBUG



When I did some deeper debugging of this bug, I found so it hangs on some
internal assert related to not initialized thread lock for protection IO.

But I tried _nolock routines, but these rutines returned badly file
descriptors (invalid pointer), and it doesn't work too.

Same routines is working for Postgres in Postgres code, but doesn't work
inside extension (separate dll). I think so Microsoft try to use dll as
separate unit with some separated data, and these data are not correctly
initialized in Orafce.

Generally Postgres extensions doesn't access IO directly, so this issue is
not visible.

I think so Orafce on MS Windows is not correctly initialized on 100% how
Microsoft expects, Postgres has own dll loader. But this is just my
hypotheses - I know nothing :(. Maybe older compilers produce partially
broken dll.

I am 20 years on Linux and Microsoft Windows and debugging there is for me
pretty unfriendly, because I miss deeper knowledges about this platform.

If it is working on Visul Studio 2017, then it is signal, so problem is in
compiler, that doesn't generate dll 100% correctly for some really specific
cases.

Work with IO from dll is fundamental, I think. So I think there is a issue
just for some really special combination of factors.

There can be more than one issue - maybe some issue related to older MSVC
and other issue related to postgres shared library loader (on windows).

**Comment by higuchi-daisuke** [comment]
Hi, 

I found one MSDN document about incompatiblity of runtime libraries. 

https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=vs-2019
```
The Microsoft C++ (MSVC) compiler toolsets in Visual Studio 2013 and earlier don't guarantee binary compatibility across versions.
You can't link object files, static libraries, dynamic libraries, and executables built by different versions.
The ABIs, object formats, and runtime libraries are incompatible.

We've changed this behavior in Visual Studio 2015, 2017, and 2019.
```
At least, PostgreSQL 10 or earlier which EDB published are compiled with VS2013, I think. 
It means that orafce should be compiled by VS2013 with these PostgreSQL. 

On the other hand, PostgreSQL 11 which EDB published are compiled with VS2015, I think. 
So, when I compiled orafce by VS2015 or VS2017, utl_file could be used. 

>I am looking on Postgres 12, and it depends on VCRUNTIME140.DLL
>Orafce has ma dependency on VCRUNTIME140D.DLL - but D means DEBUG

Seeing following document, compiler option should be the same as PostgreSQL and orafce. 

https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=vs-2019
```
All modules passed to a given invocation of the linker must have been compiled with the same run-time library compiler option (/MD, /MT, /LD).
```

Seeing one stackoverflow issue, mixing release dll and debug dll cause not good result. 
https://stackoverflow.com/questions/12285226/mixing-release-dlls-with-debug-main-application-exe

Regards,

**Comment by okbob** [comment]
čt 28. 5. 2020 v 5:23 odesílatel Daisuke <notifications@github.com> napsal:

> Hi,
>
> I found one MSDN document about incompatiblity of runtime libraries.
>
>
> https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=vs-2019
>
> The Microsoft C++ (MSVC) compiler toolsets in Visual Studio 2013 and earlier don't guarantee binary compatibility across versions.
> You can't link object files, static libraries, dynamic libraries, and executables built by different versions.
> The ABIs, object formats, and runtime libraries are incompatible.
>
> We've changed this behavior in Visual Studio 2015, 2017, and 2019.
>
> At least, PostgreSQL 10 or earlier which EDB published are compiled with
> VS2013, I think.
> It means that orafce should be compiled by VS2013 with these PostgreSQL.
>
> On the other hand, PostgreSQL 11 which EDB published are compiled with
> VS2015, I think.
> So, when I compiled orafce by VS2015 or VS2017, utl_file could be used.
>
I had these problems with VS2015 and Postgres 12.


> I am looking on Postgres 12, and it depends on VCRUNTIME140.DLL
> Orafce has ma dependency on VCRUNTIME140D.DLL - but D means DEBUG
>
> Seeing following document, compiler option should be the same as
> PostgreSQL and orafce.
>
>
> https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=vs-2019
>
> All modules passed to a given invocation of the linker must have been compiled with the same run-time library compiler option (/MD, /MT, /LD).
>
>
I'll test it

Pavel

**Comment by okbob** [comment]
čt 28. 5. 2020 v 5:50 odesílatel Pavel Stehule <pavel.stehule@gmail.com>
napsal:

>
>
> čt 28. 5. 2020 v 5:23 odesílatel Daisuke <notifications@github.com>
> napsal:
>
>> Hi,
>>
>> I found one MSDN document about incompatiblity of runtime libraries.
>>
>>
>> https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=vs-2019
>>
>> The Microsoft C++ (MSVC) compiler toolsets in Visual Studio 2013 and earlier don't guarantee binary compatibility across versions.
>> You can't link object files, static libraries, dynamic libraries, and executables built by different versions.
>> The ABIs, object formats, and runtime libraries are incompatible.
>>
>> We've changed this behavior in Visual Studio 2015, 2017, and 2019.
>>
>> At least, PostgreSQL 10 or earlier which EDB published are compiled with
>> VS2013, I think.
>> It means that orafce should be compiled by VS2013 with these PostgreSQL.
>>
>> On the other hand, PostgreSQL 11 which EDB published are compiled with
>> VS2015, I think.
>> So, when I compiled orafce by VS2015 or VS2017, utl_file could be used.
>>
> I had these problems with VS2015 and Postgres 12.
>
>
>> I am looking on Postgres 12, and it depends on VCRUNTIME140.DLL
>> Orafce has ma dependency on VCRUNTIME140D.DLL - but D means DEBUG
>>
>> Seeing following document, compiler option should be the same as
>> PostgreSQL and orafce.
>>
>>
>> https://docs.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=vs-2019
>>
>> All modules passed to a given invocation of the linker must have been compiled with the same run-time library compiler option (/MD, /MT, /LD).
>>
>>
I did successful test when I build Orafce with option /MD - C/Code
Generation/Runtime Library/ = "Multi-threaded DLL /MD". I had to explicitly
set this option in my MSVS 2015 project.

**Comment by higuchi-daisuke** [comment]
Hi, 

>I did successful test when I build Orafce with option /MD - C/Code
>Generation/Runtime Library/ = "Multi-threaded DLL /MD". I had to explicitly
>set this option in my MSVS 2015 project.

It's a good news! So, I think it is better to support utl_file package on Windows again. 
Because it is very useful and good feature for orafce users (including me :) ). 

Of cause it should note about compiler option and runtime on README. 
How do you think? If you agree with me, I'll send PR a few days later. 

Regards,

**Comment by okbob** [comment]
pá 29. 5. 2020 v 10:04 odesílatel Daisuke <notifications@github.com> napsal:

> Hi,
>
> I did successful test when I build Orafce with option /MD - C/Code
> Generation/Runtime Library/ = "Multi-threaded DLL /MD". I had to explicitly
> set this option in my MSVS 2015 project.
>
> It's a good news! So, I think it is better to support utl_file package on
> Windows again.
> Because it is very useful and good feature for orafce users (including me
> :) ).
>
> Of cause it should note about compiler option and runtime on README.
> How do you think? If you agree with me, I'll send PR a few days later.
>
Please, can you test it with older version? I did this with Postgres 12,
but I had not any other.

Pavel

**Comment by higuchi-daisuke** [comment]
>Please, can you test it with older version? I did this with Postgres 12,
>but I had not any other.

Yes, I'll test.

**Comment by okbob** [comment]
pá 29. 5. 2020 v 13:32 odesílatel Daisuke <notifications@github.com> napsal:

> Please, can you test it with older version? I did this with Postgres 12,
> but I had not any other.
>
> Yes, I'll test.
>

Thank you

**Comment by okbob** [comment]
The release 3.13.4 should be compileable without any manual changes.  utl_file is enabled on MS Windows.

**Comment by higuchi-daisuke** [comment]
Hi,

Thank you for commiting some changes about enabling utl_file.

I tested 9.5/9.6/10/11/12 PostgreSQL and latest orafce and confirmed that PG Server doesn't crash in all versions. 
I use VS2013 for 9.5/9.6/10 PG, and VS2019 for 11/12 PG. All PostgreSQL binaries are got from following: 
https://www.enterprisedb.com/download-postgresql-binaries

Regards,

**Comment by okbob** [comment]
po 1. 6. 2020 v 13:52 odesílatel Daisuke <notifications@github.com> napsal:

> Hi,
>
> Thank you for commiting some changes about enabling utl_file.
>
> I tested 9.5/9.6/10/11/12 PostgreSQL and latest orafce and confirmed that
> PG Server doesn't crash in all versions.
> I use VS2013 for 9.5/9.6/10 PG, and VS2019 for 11/12 PG. All PostgreSQL
> binaries are got from following:
> https://www.enterprisedb.com/download-postgresql-binaries
>
super, thank you very much. It was very long issue.

please, can you publish dll

https://groups.google.com/forum/?hl=cs#!forum/orafce-general

Regards

Pavel

**Comment by higuchi-daisuke** [comment]
Hi, 

>please, can you publish dll

OK, I'll try. However, it may take some time. 
I have never posted to google groups, so I might have to overcome various problems (including non-technical problems). 

Regards,

**Comment by okbob** [comment]
po 1. 6. 2020 v 14:36 odesílatel Daisuke <notifications@github.com> napsal:

> Hi,
>
> please, can you publish dll
>
> OK, I'll try. However, it may take some time.
>

no problem,

Thank you very much

Pavel

**Comment by higuchi-daisuke** [comment]
Hi, 

>please, can you publish dll

Sorry for the long time.
I tried to post to Google Groups, but I couldn't. This wasn't a technical problem and I couldn't solve it.
So, I'll attach the binary I created. If necessary, you can post this to Google Groups instead.

[note]
I built orafce 3.13.4 on Windows OS (64bit).
The target PostgreSQL versions are 12.4, 11.9, 10.14, 9.6.19 and 9.5.23.

My dlls for 9.5, 9.6 and 10 request msvcr120.dll and dlls for 11 and 12 request vcruntime140.dll.
This is consistent with the runtime required by the PostgreSQL server published by EDB.

Therefore, if you use the PostgreSQL server binary published by EDB, you can use it without any problem.
However, if you build PostgreSQL using a different runtime, it may not work properly if the required runtime is not compatible.

[orafce_win_binary.zip](https://github.com/orafce/orafce/files/5264898/orafce_win_binary.zip)

Regards,
Daisuke, Higuchi

**Comment by okbob** [comment]
st 23. 9. 2020 v 3:26 odesílatel Daisuke <notifications@github.com> napsal:

> Hi,
>
> please, can you publish dll
>
> Sorry for the long time.
> I tried to post to Google Groups, but I couldn't. This wasn't a technical
> problem and I couldn't solve it.
> So, I'll attach the binary I created. If necessary, you can post this to
> Google Groups instead.
>
> [note]
> I built orafce 3.13.4 on Windows OS (64bit).
> The target PostgreSQL versions are 12.4, 11.9, 10.14, 9.6.19 and 9.5.23.
>
> My dlls for 9.5, 9.6 and 10 request msvcr120.dll and dlls for 11 and 12
> request vcruntime140.dll.
> This is consistent with the runtime required by the PostgreSQL server
> published by EDB.
>
> Therefore, if you use the PostgreSQL server binary published by EDB, you
> can use it without any problem.
> However, if you build PostgreSQL using a different runtime, it may not
> work properly if the required runtime is not compatible.
>
> orafce_win_binary.zip
> <https://github.com/orafce/orafce/files/5264898/orafce_win_binary.zip>
>

Thank you

Pavel

Regards,
