### ISSUE TITLE
How to update orafce form 3.6 to 3.8 in 10.12 PG

### ISSUE THREAD

**Issue by Monsterwulc** [orafce/orafce#108]
Hi,

I have a question about how to update orafce from 3.6 to 3.8.

Now, there are libs of orafce3.6 and 3.8 in 10 PG.

**Comment by okbob** [comment]
[image: image.gif]



Hi

út 2. 6. 2020 v 11:42 odesílatel Monsterwulc <notifications@github.com>
napsal:

> Hi,
>
> I have a question about how to update orafce from 3.6 to 3.8.
>
> Now, there are libs of orafce3.6 and 3.8 in 10 PG.
>

you should to copy new dll to postgres lib directory and .sql files +
control file to share directory.

then run sql statement ALTER EXTENSION orafce UPDATE.

https://www.postgresql.org/docs/current/sql-alterextension.html

Regards

Pavel

**Comment by Monsterwulc** [comment]
Thanks
