### ISSUE TITLE
Any plan to emulate UTL_SMTP ?

### ISSUE THREAD

**Issue by airduv** [orafce/orafce#112]
Hello Pavel.
When trying to migrate some apps from Oracle DB to Postgres we found some programs using the utl_smtp package.
It looks like something that can be ported to orafce, maybe using libcurl (supports SMTP and TLS)
https://curl.haxx.se/libcurl/c/smtp-mail.html
https://curl.haxx.se/libcurl/c/smtp-tls.html
(I think SMTP could be enough as a first test)

Any thought from you on this subject ?
Regards
Rémi

**Comment by okbob** [comment]
Hi

pá 28. 8. 2020 v 10:58 odesílatel remduv <notifications@github.com> napsal:

> Hello Pavel.
> When trying to migrate some apps from Oracle DB to Postgres we found some
> programs using the utl_smtp package.
> It looks like something that can be ported to orafce, maybe using libcurl
> (supports SMTP and TLS)
> https://curl.haxx.se/libcurl/c/smtp-mail.html
> https://curl.haxx.se/libcurl/c/smtp-tls.html
> (I think SMTP could be enough as a first test)
>
> Any thought from you on this subject ?
>
It is a hard question - currently orafce doesn't depend on any other
external library. I am not hungry to introduce new dependencies.

Second - is risk to use a library that implements its own timeout - it
redefines SIGALARM event (Postgres does it too) - and it is just a risk. I
had the possibility to see some really and hard debugged errors from this
reason. For this case it is much better to rewrite code, and instead send
mail directly just write to the table, and later from another application
read this table and send a mails. If I want to do this task well, then it
needs sandboxing of calls, and it is not easy (without it, then calling
this library breaks pg timeouts). It will work longer than a few days, and
personally, I think it is a bad pattern. But if I find a sponsor for this,
then I can write it as an optional part.

Regards

Pavel

**Comment by remduv** [comment]
Thanks for your quick answer.
I get what you said and now realize that it's not so easy to do so.
In fact, I've already developed a lightweight solution using a queue table + INSERT and NOTIFY on PL/pgSQL side 
and on the other side a small python program using psycopg2 and LISTEN.
It works quite fine but it's not really synchronous as is utl_smtp.
I'll keep using this for the moment, but it's good to have your point of view.
Regards.

**Comment by okbob** [comment]
pá 28. 8. 2020 v 14:22 odesílatel remduv <notifications@github.com> napsal:

> Thanks for your quick answer.
> I get what you said and now realize that it's not so easy to do so.
> In fact, I've already developed a lightweight solution using a queue table
> + INSERT and NOTIFY on PL/pgSQL side
> and on the other side a small python program using psycopg2 and LISTEN.
> It works quite fine but it's not really synchronous as is utl_smtp.
> I'll keep using this for the moment, but it's good to have your point of
> view.
>
The solution based on INSERT and NOTIFY is much safer. Isn't too hard
sending mails from PLPerlu - but I had a very bad experience with it (it is
ok when it is working, but if there are some problems, then it can kill
postgres server).

Regards

Pavel

Regards.

**Comment by okbob** [comment]
I checked it again, and it is not trivial task - the signal handling requires good knowledge of libcurl.

**Comment by okbob** [comment]
pá 28. 8. 2020 v 15:15 odesílatel Pavel Stehule <pavel.stehule@gmail.com>
napsal:

>
>
> pá 28. 8. 2020 v 14:22 odesílatel remduv <notifications@github.com>
> napsal:
>
>> Thanks for your quick answer.
>> I get what you said and now realize that it's not so easy to do so.
>> In fact, I've already developed a lightweight solution using a queue
>> table + INSERT and NOTIFY on PL/pgSQL side
>> and on the other side a small python program using psycopg2 and LISTEN.
>> It works quite fine but it's not really synchronous as is utl_smtp.
>> I'll keep using this for the moment, but it's good to have your point of
>> view.
>>
> The solution based on INSERT and NOTIFY is much safer. Isn't too hard
> sending mails from PLPerlu - but I had a very bad experience with it (it is
> ok when it is working, but if there are some problems, then it can kill
> postgres server).
>

Probably it is possible to use libcurl from Postgres. It does some cleaning
inside. But it is hard to integrate together. I checked few extensions that
use libcurl and probably all are little bit buggy

https://github.com/pramsey/pgsql-http/issues/112

**Comment by okbob** [comment]
so 29. 8. 2020 v 18:59 odesílatel Pavel Stehule <pavel.stehule@gmail.com>
napsal:

>
>
> pá 28. 8. 2020 v 15:15 odesílatel Pavel Stehule <pavel.stehule@gmail.com>
> napsal:
>
>>
>>
>> pá 28. 8. 2020 v 14:22 odesílatel remduv <notifications@github.com>
>> napsal:
>>
>>> Thanks for your quick answer.
>>> I get what you said and now realize that it's not so easy to do so.
>>> In fact, I've already developed a lightweight solution using a queue
>>> table + INSERT and NOTIFY on PL/pgSQL side
>>> and on the other side a small python program using psycopg2 and LISTEN.
>>> It works quite fine but it's not really synchronous as is utl_smtp.
>>> I'll keep using this for the moment, but it's good to have your point of
>>> view.
>>>
>> The solution based on INSERT and NOTIFY is much safer. Isn't too hard
>> sending mails from PLPerlu - but I had a very bad experience with it (it is
>> ok when it is working, but if there are some problems, then it can kill
>> postgres server).
>>
>
> Probably it is possible to use libcurl from Postgres. It does some
> cleaning inside. But it is hard to integrate together. I checked few
> extensions that use libcurl and probably all are little bit buggy
>
> https://github.com/pramsey/pgsql-http/issues/112
>

I played with curl lib a little bit more, and probably the implementation
of UTL_STMT is possible (with modern libcurl it can be safe).
Unfortunately, it is not a one day job, so I can implement this feature
when somebody puts money for it or if I will have free time for this -
maybe in winter.

**Comment by remduv** [comment]
Hello and thanks again for your concern.
I'm sorry that I cannot contribute that much on the C code, as I'm not experienced enough on this side for the moment.
Anyway, it's good to have your thoughts and feedback on the utl_smtp topic.
I will keep on using the asynchronous solution for the moment, as it might also be a bit better in terms of architecture, but I remain interested in a utl_smtp port in C. Let's keep in touch on this subject.

**Comment by okbob** [comment]
I wrote `orafce_mail` extension -  there `utl_mail` is emulated

https://github.com/okbob/orafce_mail
