### ISSUE TITLE
Function are failing

### ISSUE THREAD

**Issue by kirandba-hub** [orafce/orafce#114]
Hi,

I recently migrated the function from oracle to postgres by installing the ORAFCE.In my Oracle function we are having the dual and connect by keywords, when this converted to postgres it is failing with errors,below is the function in both oracle and postgres.

Oracle Function 

WHERE a.case_id=b.case_id and quality_screen in (in_quality_screen) and a.case_id=p.case_id  and P.PRODUCT_FLAG='Suspect' and coalesce(CP.PRODUCT_GROUP_NAME,'OTHER') in (WITH RECURSIVE cte AS (
 select (SELECT array_to_string(a, '') FROM regexp_matches(in_product_group_name, '[^,]+', 'g') AS foo(a) LIMIT 1 OFFSET (level - 1))
   SELECT array_to_string(a, '') FROM (regexp_matches(in_product_group_name, '[^,]+', 'g') AS foo(a) LIMIT 1 OFFSET (level - 1)) is not null   UNION ALL
 select (SELECT array_to_string(a, '') FROM (regexp_matches(in_product_group_name, '[^,]+', 'g') AS foo(a) LIMIT 1 OFFSET (level - 1))
   (SELECT array_to_string(a, '') FROM (regexp_matches(in_product_group_name, '[^,]+', 'g') AS foo(a) LIMIT 1 OFFSET (level - 1)) is not null  JOIN cte c ON ()

Postgres Function

WHERE a.case_id=b.case_id and quality_screen in (in_quality_screen) and a.case_id=p.case_id  and P.PRODUCT_FLAG='Suspect' and coalesce(CP.PRODUCT_GROUP_NAME,'OTHER') in (WITH RECURSIVE cte AS (
 select (SELECT array_to_string(a, '') FROM regexp_matches(in_product_group_name, '[^,]+', 'g') AS foo(a) LIMIT 1 OFFSET (level - 1))
   SELECT array_to_string(a, '') FROM (regexp_matches(in_product_group_name, '[^,]+', 'g') AS foo(a) LIMIT 1 OFFSET (level - 1)) is not null   UNION ALL
 select (SELECT array_to_string(a, '') FROM (regexp_matches(in_product_group_name, '[^,]+', 'g') AS foo(a) LIMIT 1 OFFSET (level - 1))
   (SELECT array_to_string(a, '') FROM (regexp_matches(in_product_group_name, '[^,]+', 'g') AS foo(a) LIMIT 1 OFFSET (level - 1)) is not null  JOIN cte c ON ()

This function is failing at (SELECT array_to_string(a, '') FROM ... I'm not getting what is wrong with this function.

Can you please help me on this.

Thanks,
Kiran

**Comment by okbob** [comment]
čt 24. 9. 2020 v 0:21 odesílatel kirandba-hub <notifications@github.com>
napsal:

> Hi,
>
> I recently migrated the function from oracle to postgres by installing the
> ORAFCE.In my Oracle function we are having the dual and connect by
> keywords, when this converted to postgres it is failing with errors,below
> is the function in both oracle and postgres.
>
> Oracle Function
>
> WHERE a.case_id=b.case_id and quality_screen in (in_quality_screen) and
> a.case_id=p.case_id and P.PRODUCT_FLAG='Suspect' and
> coalesce(CP.PRODUCT_GROUP_NAME,'OTHER') in (WITH RECURSIVE cte AS (
> select (SELECT array_to_string(a, '') FROM
> regexp_matches(in_product_group_name, '[^,]+', 'g') AS foo(a) LIMIT 1
> OFFSET (level - 1))
> SELECT array_to_string(a, '') FROM (regexp_matches(in_product_group_name,
> '[^,]+', 'g') AS foo(a) LIMIT 1 OFFSET (level - 1)) is not null UNION ALL
> select (SELECT array_to_string(a, '') FROM
> (regexp_matches(in_product_group_name, '[^,]+', 'g') AS foo(a) LIMIT 1
> OFFSET (level - 1))
> (SELECT array_to_string(a, '') FROM (regexp_matches(in_product_group_name,
> '[^,]+', 'g') AS foo(a) LIMIT 1 OFFSET (level - 1)) is not null JOIN cte c
> ON ()
>
array_to_string is only Postgres function.


> Postgres Function
>
> WHERE a.case_id=b.case_id and quality_screen in (in_quality_screen) and
> a.case_id=p.case_id and P.PRODUCT_FLAG='Suspect' and
> coalesce(CP.PRODUCT_GROUP_NAME,'OTHER') in (WITH RECURSIVE cte AS (
> select (SELECT array_to_string(a, '') FROM
> regexp_matches(in_product_group_name, '[^,]+', 'g') AS foo(a) LIMIT 1
> OFFSET (level - 1))
> SELECT array_to_string(a, '') FROM (regexp_matches(in_product_group_name,
> '[^,]+', 'g') AS foo(a) LIMIT 1 OFFSET (level - 1)) is not null UNION ALL
> select (SELECT array_to_string(a, '') FROM
> (regexp_matches(in_product_group_name, '[^,]+', 'g') AS foo(a) LIMIT 1
> OFFSET (level - 1))
> (SELECT array_to_string(a, '') FROM (regexp_matches(in_product_group_name,
> '[^,]+', 'g') AS foo(a) LIMIT 1 OFFSET (level - 1)) is not null JOIN cte c
> ON ()
>
> This function is failing at (SELECT array_to_string(a, '') FROM ... I'm
> not getting what is wrong with this function.
>
What error?

I don't see there any orafce function. Almost all are build Postgres
functions.

**Comment by kirandba-hub** [comment]
Hi,

Sorry for the confusion,below is the Oaacle Function,in this function dual and connect by is using,i don't now how postgres will handle this keywords,

WHERE  a.case_id=b.case_id and quality_screen in (in_quality_screen) and a.case_id=p.case_id and upper(P.trade_name)=CP.trade_name(+) and P.PRODUCT_FLAG='Suspect'
    and nvl(CP.PRODUCT_GROUP_NAME,'OTHER') in  ( select regexp_substr(in_product_group_name,'[^,]+', 1,level) from dual
   connect by regexp_substr(in_product_group_name, '[^,]+', 1, level) is not null )
          -- and protocol_no in   (in_protocol_no) 
           and (b.AER_RECV_DATE between in_start_date and in_end_date)
          and b.LATEST_APPRV_CASE_VERSION_NO in ( select regexp_substr(in_latest_version,'[^,]+', 1,level) from dual
   connect by regexp_substr(in_latest_version, '[^,]+', 1, level) is not null )
    and b.AER_CASE_DELETED in ( select regexp_substr(in_case_deleted,'[^,]+', 1,level) from dual
   connect by regexp_substr(in_case_deleted, '[^,]+', 1, level) is not null ) 
   and case when b.aer_category in ('Adverse event','Adverse event due to product problem') Then 'Adverse Event' Else 'Non-Valid' End in ( select regexp_substr(in_aer_category,'[^,]+', 1,level) from dual
   connect by regexp_substr(in_aer_category, '[^,]+', 1, level) is not null )

Error  

gdsrm_sdm=> \i /etc/ora2pg/GDSRM_SDM_Migration/Functions/FN_CONCATE_DATE_INFORMED_GDSRM_SDM_Function.sql
SET
psql:/etc/ora2pg/GDSRM_SDM_Migration/Functions/FN_CONCATE_DATE_INFORMED_GDSRM_SDM_Function.sql:49: ERROR:  syntax error at or near "("
LINE 18:    (SELECT array_to_string(a, '') FROM regexp_matches(I_AUTH...

I am confused where this statement is failing..Can you please help me


[postgres function.txt](https://github.com/orafce/orafce/files/5274138/postgres.function.txt)

Thanks,
Kiran

**Comment by okbob** [comment]
čt 24. 9. 2020 v 9:20 odesílatel kirandba-hub <notifications@github.com>
napsal:

> Hi,
>
> Sorry for the confusion,below is the Oaacle Function,in this function dual
> and connect by is using,i don't now how postgres will handle this keywords,
>
> WHERE a.case_id=b.case_id and quality_screen in (in_quality_screen) and
> a.case_id=p.case_id and upper(P.trade_name)=CP.trade_name(+) and
> P.PRODUCT_FLAG='Suspect'
> and nvl(CP.PRODUCT_GROUP_NAME,'OTHER') in ( select
> regexp_substr(in_product_group_name,'[^,]+', 1,level) from dual
> connect by regexp_substr(in_product_group_name, '[^,]+', 1, level) is not
> null )
> -- and protocol_no in (in_protocol_no)
> and (b.AER_RECV_DATE between in_start_date and in_end_date)
> and b.LATEST_APPRV_CASE_VERSION_NO in ( select
> regexp_substr(in_latest_version,'[^,]+', 1,level) from dual
> connect by regexp_substr(in_latest_version, '[^,]+', 1, level) is not null
> )
> and b.AER_CASE_DELETED in ( select regexp_substr(in_case_deleted,'[^,]+',
> 1,level) from dual
> connect by regexp_substr(in_case_deleted, '[^,]+', 1, level) is not null )
> and case when b.aer_category in ('Adverse event','Adverse event due to
> product problem') Then 'Adverse Event' Else 'Non-Valid' End in ( select
> regexp_substr(in_aer_category,'[^,]+', 1,level) from dual
> connect by regexp_substr(in_aer_category, '[^,]+', 1, level) is not null )
>
> Error
>
> gdsrm_sdm=> \i
> /etc/ora2pg/GDSRM_SDM_Migration/Functions/FN_CONCATE_DATE_INFORMED_GDSRM_SDM_Function.sql
> SET
> psql:/etc/ora2pg/GDSRM_SDM_Migration/Functions/FN_CONCATE_DATE_INFORMED_GDSRM_SDM_Function.sql:49:
> ERROR: syntax error at or near "("
> LINE 18: (SELECT array_to_string(a, '') FROM regexp_matches(I_AUTH...
>
> I am confused where this statement is failing..Can you please help me
>

(SELECT array_to_string(a, '') FROM (regexp_matches(in_product_group_name,
'[^,]+', 'g') AS foo(a) LIMIT 1 OFFSET (level - 1)) is not null JOIN cte c
ON ()

the empty "ON" clause looks strange

is not null JOIN cte c >>>>>>ON ()<<<<<



postgres function.txt

**Comment by kirandba-hub** [comment]
Yes... When I remove is not null join cte ... It is working.. 
I don't know whether the created function will work.. 

Should I ask application developers to buid the logic again in postgreSQL?

**Comment by okbob** [comment]
pá 25. 9. 2020 v 8:26 odesílatel kirandba-hub <notifications@github.com>
napsal:

> Yes... When I remove is not null join cte ... It is working..
> I don't know whether the created function will work..
>
> Should I ask application developers to buid the logic again in postgreSQL?
>

???
