### ISSUE TITLE
Is it possible to support orafce in google cloud sql

### ISSUE THREAD

**Issue by ycj28c** [orafce/orafce#118]
Hi, we used orafce for our oracle to postgres migration, it work very well.
Recently we try to migrate to cloud db, my manager decide to choose the google cloud (it is cheap compare to AWS RDS or Azure), however, I found that the google cloud is not support the orafce extension.
https://cloud.google.com/sql/docs/postgres/extensions#postgresql-extensions-supported-by-cloud-sql
Is there a way to work around for this problem(We have to migrate to google cloud)?

**Comment by okbob** [comment]
This is a question for google cloud admins - Orafce is licenced under cloud friendly free licence and that is all what I can do. You should to ask google.

**Comment by ycj28c** [comment]
Thanks for your reply. google cloud don't have superuser, so I can't create some custom type. The extension limitation is very strict in google cloud, can't install orafce or plpgsql_check there. Has send the question to them, hopefully can get response.

**Comment by luss** [comment]
Orafce is included in aws managed postgres offerings and (i think) in Azure
also
