### ISSUE TITLE
Does orafce supported for Postgresql 13?

### ISSUE THREAD

**Issue by nguyenxuanluong-luvina** [orafce/orafce#119]
Hi orafce team, thank you very much for this is very useful tool.
I'm using postgresql 11 and working well with orafce 3.13 .
I'm planing to change my db to postgresql 13 but the orafce seem not work on Postgresql 13, when run the command : 
`CREATE EXTENSION orafce;`
I got error :
`SQL Error [58P01]: ERROR: could not load library "D:/PostgreSQL/13/lib/orafce.dll": The specified procedure could not be found.`
Do you have any solution for this?

**Comment by okbob** [comment]
čt 29. 10. 2020 v 4:52 odesílatel Nguyễn Xuân Lương <
notifications@github.com> napsal:

> Hi orafce team, thank you very much for this is very useful tool.
> I'm using postgresql 11 and working well with orafce 3.13 .
> I'm planing to change my db to postgresql 13 but the orafce seem not work
> on Postgresql 13, when run the command :
> CREATE EXTENSION orafce;
> I got error :
> SQL Error [58P01]: ERROR: could not load library
> "D:/PostgreSQL/13/lib/orafce.dll": The specified procedure could not be
> found.
> Do you have any solution for this?
>
PostgreSQL extensions are compiled against one specific Postgres major
release. So you cannot use Orafce compiled for 11 in Postgres 13.

You should build for Postgres 13.

https://www.2ndquadrant.com/en/blog/compiling-postgresql-extensions-visual-studio-windows/

I'll do this in next month

Regards

Pavel
