### ISSUE TITLE
dbms_alert tests are unreliable

### ISSUE THREAD

**Issue by petere** [orafce/orafce#12]
In automatic testing, the `dbms_alert_session_X.sql` test fail for me about once every 10 times, presumably because the machine is fairly busy and so cannot stay within the timeouts.  I suggest to increase the timeouts in all of the tests.  Alternatively, maybe there should be a way to disable that group of tests if it cannot be made more reliable.

**Comment by okbob** [comment]
Should be fixed on 3.1.2 http://pgxn-tester.org/distributions/orafce/3.1.2
The problem was in too late start B and C - solved by pg_sleep(3) call on start A
