### ISSUE TITLE
Having lots of trouble on Mac Mohave 10.14.6

### ISSUE THREAD

**Issue by zmacomber** [orafce/orafce#122]
Has anyone successfully installed this on a Mac and can give direction on how to do so? I have read/reread the install doc several times and attempted to install this extension but I keep getting errors.

Are there any Mac specific instructions on how to install this?

**Comment by zmacomber** [comment]
I ended up being able to get thru this by using the homebrew install of postgres. Everything flowed from that initial step nicely for installing extensions.

**Comment by robli298** [comment]
Hey @zmacomber,

Could you tell me the steps you followed to have it compiled and installed on MacOS, please?
