### ISSUE TITLE
Postgresql 13 can not install orafce

### ISSUE THREAD

**Issue by DSantonastaso** [orafce/orafce#125]
Can't install orafce.
This is log:
sudo make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/13/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o parse_keyword.o parse_keyword.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/13/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o convert.o convert.c
In file included from convert.c:9:
/usr/include/postgresql/13/server/utils/pg_locale.h:19:10: fatal error: unicode/ucol.h: No such file or directory
   19 | #include <unicode/ucol.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: convert.o] Error 1

Any idea?
o.s. ubuntu 20.04

Thanks

**Comment by okbob** [comment]
po 28. 12. 2020 v 19:37 odesílatel DSantonastaso <notifications@github.com>
napsal:

> Can't install orafce.
> This is log:
> sudo make
> gcc -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Werror=vla -Wendif-labels
> -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security
> -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -Wno-format-truncation -Wno-stringop-truncation -g -g -O2
> -fstack-protector-strong -Wformat -Werror=format-security
> -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/13/server
> -I/usr/include/postgresql/internal -Wdate-time -D_FORTIFY_SOURCE=2
> -D_GNU_SOURCE -I/usr/include/libxml2 -c -o parse_keyword.o parse_keyword.c
> gcc -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Werror=vla -Wendif-labels
> -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security
> -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -Wno-format-truncation -Wno-stringop-truncation -g -g -O2
> -fstack-protector-strong -Wformat -Werror=format-security
> -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/13/server
> -I/usr/include/postgresql/internal -Wdate-time -D_FORTIFY_SOURCE=2
> -D_GNU_SOURCE -I/usr/include/libxml2 -c -o convert.o convert.c
> In file included from convert.c:9:
> /usr/include/postgresql/13/server/utils/pg_locale.h:19:10: fatal error:
> unicode/ucol.h: No such file or directory
> 19 | #include <unicode/ucol.h>
> | ^~~~~~~~~~~~~~~~
> compilation terminated.
> make: *** [: convert.o] Error 1
>
Your Postgres was compiled with libicu support, and you need to install
libicu-devel packages

 This is same issue

https://github.com/akorotkov/vgram/issues/1


Any idea?

**Comment by DSantonastaso** [comment]
Thank you for solving 👍

**Comment by DSantonastaso** [comment]
Thank you for solving 👍
