### ISSUE TITLE
Is there any way to emulate Synonym?

### ISSUE THREAD

**Issue by amoltarte** [orafce/orafce#127]
Hi!
I am desperately in need of Synonym.
Right now what happening is, we are using view in replacement of Synonym.

Current Scenario is...

A View "V" is accessing table A
Table "A" has huge data approximately 11M rows, and increasing.
All clients are accessing this View (read only or SELECT only statements) and once in 24 hours, 
I have to refill the table "A" with new (updated) data.

Now what I do is, Create a Dummy table "B" as SELECT * FROM Main table.

Now I try to 
CREATE OR REPLACE VIEW "V" AS SELECT * FROM B.
---- Here all connected clients hang as view "V" is pointing to table "A" and all clients randomly connected to "V" are fetching data from "V".

This does not happen in Oracle as we use SYNONYM there.

**Comment by okbob** [comment]
Hi

čt 11. 2. 2021 v 11:09 odesílatel Amol Tarte <notifications@github.com>
napsal:

> Hi!
> I am desperately in need of Synonym.
> Right now what happening is, we are using view in replacement of Synonym.
>
> Current Scenario is...
>
> A View "V" is accessing table A
> Table "A" has huge data approximately 11M rows, and increasing.
> All clients are accessing this View (read only or SELECT only statements)
> and once in 24 hours,
> I have to refill the table "A" with new (updated) data.
>
> Now what I do is, Create a Dummy table "B" as SELECT * FROM Main table.
>
> Now I try to
> CREATE OR REPLACE VIEW "V" AS SELECT * FROM B.
> ---- Here all connected clients hang as view "V" is pointing to table "A"
> and all clients randomly connected to "V" are fetching data from "V".
>
> This does not happen in Oracle as we use SYNONYM there.
>
no, there is nothing similar. You can use a materialized view for this case.

Regards

Pavel
