### ISSUE TITLE
How to use select dbms_output.put_line('first_line'); in anonymous block?

### ISSUE THREAD

**Issue by shab2** [orafce/orafce#131]
Hi!
This code has error. How to use dbms_output.put_line in here? Thank you!

do
$do$
declare
 ch varchar(200);
BEGIN
  ch:='hello, world!';
  select dbms_output.serveroutput('t');
  select dbms_output.put_line(ch);
  RAISE INFO '%', ch;
END
$do$;

**Comment by okbob** [comment]
st 7. 4. 2021 v 12:12 odesílatel shab2 ***@***.***> napsal:

> Hi!
> This code has error. How to use dbms_output.put_line in here? Thank you!
>
> do
> $do$
> declare
> ch varchar(200);
> BEGIN
> ch:='hello, world!';
> select dbms_output.serveroutput('t');
> select dbms_output.put_line(ch);
> RAISE INFO '%', ch;
> END
> $do$;
>

you should to use PERFORM instead SELECT

https://www.postgresql.org/docs/current/plpgsql-statements.html#PLPGSQL-STATEMENTS-SQL-NORESULT

Regards

Pavel

**Comment by shab2** [comment]
thanks
