### ISSUE TITLE
New lines after and before dbms_output

### ISSUE THREAD

**Issue by shab2** [orafce/orafce#132]
Hello, Pavel

When I use this code, then I see 2 empty lines. I using bash for programming and I prefer know how to escape this empty lines.
I undestand to cut then by sed, but maybe you know to make it by psql?

echo "1"; echo "select dbms_output.serveroutput('t'); select dbms_output.put_line('first_line');" | psql -At service=PCFT_DEV; echo "2"
OUTPUT:
1

first_line

2

**Comment by shab2** [comment]
i know you make output "first line" to ERROR output. Why? May be it is only info message... So I can split ERROR output from standard OUTPUT. By the way empty lines rests on standard OUTPUT :)

**Comment by okbob** [comment]
these empty lines are there due empty result. dbms_ouput.put_line is a void function. These functions returns nothing - just starts debug output. It cannot be fixed - the psql prints result of void function like this. Now, the Postgres supports procedures, but 12 years ago, when I wrote Orafce, the procedures was not available in Postgres, and I cannot to change it now from ensuring compatibility reasons.
