### ISSUE TITLE
Problem compilining orafce 3.15.0 under windows

### ISSUE THREAD

**Issue by vbwagner** [orafce/orafce#133]
When compiliung new orafce with postgres from 9.6 to 12 by old MSVC (2013) I'm encountering following error:

```
Microsoft (R) Incremental Linker Version 12.00.40629.0
Copyright (C) Microsoft Corporation.  All rights reserved.

   Creating library orafce.lib and object orafce.exp
convert.obj : error LNK2019: unresolved external symbol pg_enc2name_tbl referenced in function pg_unicode_to_server
orafce.dll : fatal error LNK1120: 1 unresolved externals
Failed with error #1120.
Failed with error #1120.
```
It happens becouse on Windows variabels from backend are not automatically available for loaded extensions, and should be specially exported (or better variable reference replaced by fiunction call - there is special function pg_encoding_to_char that access this table doing neccessarty precautions).

Really I see no need to use pg_enc2name_tbl[PG_UTF8] or even pg_encpoding_to_char(PG_IUTF8) instead of just
plain string literal "UTF8" in only place where this variable is accessed in the orafce code.

Problem is not reproduced with PostgreSQL 13 build with either MSVC 2013 and 2019

**Comment by vbwagner** [comment]
With PosttgreSQL 12 and MSVC 2013 head of master branch (commit 3b3dc0042ed6f22c6655ea7d5456ec5591e30e3d)  compiles OK. 

I don't think it's worth effort checking with any other postgres version from 9.6 to 11, because change is trivial.

There is one warning although: 
```
c:\users\vitus\orafce\convert.c(926) : warning C4715: 'orafce_unistr' : not al
control paths return a value
```
I suppose it is harmless and only appear because MSVC cannot understand that macro ereport(ERROR...) doesn't return,

**Comment by okbob** [comment]
so 8. 5. 2021 v 14:59 odesílatel Victor Wagner ***@***.***>
napsal:

> With PosttgreSQL 12 and MSVC 2013 head of master branch (commit 3b3dc00
> <https://github.com/orafce/orafce/commit/3b3dc0042ed6f22c6655ea7d5456ec5591e30e3d>)
> compiles OK.
>
> I don't think it's worth effort checking with any other postgres version
> from 9.6 to 11, because change is trivial.
>
> There is one warning although:
>
> c:\users\vitus\orafce\convert.c(926) : warning C4715: 'orafce_unistr' : not al
> control paths return a value
>
> I suppose it is harmless and only appear because MSVC cannot understand
> that macro ereport(ERROR...) doesn't return,
>
I tried to fix this warning in the last commit.

Thank you for check
