### ISSUE TITLE
Problem compilining orafce 3.13.4 under windows

### ISSUE THREAD

**Issue by gzhcoder** [orafce/orafce#134]
I tried to build the orafce(3.13.4) with postgres13.2 by MSVC (2017).
I’m using the below:
①Windows 10, 64 bits
②Microsoft Visual Studio Professional 2019(v142)
③orafce 3.13.4
④icu4c-64_2-Win64-MSVC2017 (libicu)
⑤postgresql-13.2-2-windows-x64-binaries

Getting below error while build:
Thanks in advance for any help on this subject.

1>------ Rebuild All started: Project: orafce, Configuration: 10.3 Win32 ------
1>aggregate.c
1>alert.c
1>assert.c
1>convert.c
1>datefce.c
1>file.c
1>magic.c
1>others.c
1>pipe.c
1>plunit.c
1>plvdate.c
1>plvlex.c
1>plvstr.c
1>plvsubst.c
1>putline.c
1>random.c
1>shmmc.c
1>utility.c
1>orafce.c
1>charlen.c
1>Compiling...
1>charpad.c
1>nvarchar2.c
1>varchar2.c
1>   Creating library D:\postgresql\orafce-VERSION_3_13_4\msvc\/bin/x86/10.3/lib/orafce.lib and object D:\postgresql\orafce-VERSION_3_13_4\msvc\/bin/x86/10.3/lib/orafce.exp
1>aggregate.obj : error LNK2001: unresolved external symbol _errfinish
1>aggregate.obj : error LNK2001: unresolved external symbol _errstart
1>aggregate.obj : error LNK2001: unresolved external symbol _string_agg_transfn
1>aggregate.obj : error LNK2001: unresolved external symbol _AggCheckCallContext
1>aggregate.obj : error LNK2001: unresolved external symbol _palloc
1>aggregate.obj : error LNK2001: unresolved external symbol _errmsg_internal
1>aggregate.obj : error LNK2001: unresolved external symbol _string_agg_finalfn
1>aggregate.obj : error LNK2001: unresolved external symbol _pg_qsort
1>aggregate.obj : error LNK2001: unresolved external symbol _appendStringInfoChar
1>aggregate.obj : error LNK2001: unresolved external symbol _appendBinaryStringInfo
1>aggregate.obj : error LNK2001: unresolved external symbol _makeStringInfo
1>aggregate.obj : error LNK2001: unresolved external symbol _pg_detoast_datum_packed
1>aggregate.obj : error LNK2001: unresolved external symbol _repalloc
1>aggregate.obj : error LNK2001: unresolved external symbol __imp__CurrentMemoryContext
1>alert.obj : error LNK2001: unresolved external symbol _SPI_exec
1>alert.obj : error LNK2001: unresolved external symbol _ProcessInterrupts
1>alert.obj : error LNK2001: unresolved external symbol _pstrdup
1>alert.obj : error LNK2001: unresolved external symbol __imp__SPI_processed
1>alert.obj : error LNK2001: unresolved external symbol _pgwin32_dispatch_queued_signals

...

>orafce.obj : error LNK2001: unresolved external symbol _DefineCustomBoolVariable
1>orafce.obj : error LNK2001: unresolved external symbol _EmitWarningsOnPlaceholders
1>charpad.obj : error LNK2001: unresolved external symbol _pg_dsplen
1>nvarchar2.obj : error LNK2001: unresolved external symbol _pg_mbcharcliplen
1>nvarchar2.obj : error LNK2001: unresolved external symbol _pq_getmsgtext
1>nvarchar2.obj : error LNK2001: unresolved external symbol _pg_mbstrlen
1>varchar2.obj : error LNK2001: unresolved external symbol _varchar_support
1>D:\postgresql\orafce-VERSION_3_13_4\msvc\\bin\x86\10.3\lib\\orafce.dll : fatal error LNK1120: 174 unresolved externals
1>Done building project "orafce.2010.vcxproj" -- FAILED.

**Comment by okbob** [comment]
pá 14. 5. 2021 v 8:23 odesílatel gzhcoder ***@***.***> napsal:

> I tried to build the orafce(3.13.4) with postgres13.2 by MSVC (2017).
> I’m using the below:
> ①Windows 10, 64 bits
> ②Microsoft Visual Studio Professional 2019(v142)
> ③orafce 3.13.4
> ④icu4c-64_2-Win64-MSVC2017 (libicu)
> ⑤postgresql-13.2-2-windows-x64-binaries
>
> Getting below error while build:
> Thanks in advance for any help on this subject.
>
> 1>------ Rebuild All started: Project: orafce, Configuration: 10.3 Win32
> ------
> 1>aggregate.c
> 1>alert.c
> 1>assert.c
> 1>convert.c
> 1>datefce.c
> 1>file.c
> 1>magic.c
> 1>others.c
> 1>pipe.c
> 1>plunit.c
> 1>plvdate.c
> 1>plvlex.c
> 1>plvstr.c
> 1>plvsubst.c
> 1>putline.c
> 1>random.c
> 1>shmmc.c
> 1>utility.c
> 1>orafce.c
> 1>charlen.c
> 1>Compiling...
> 1>charpad.c
> 1>nvarchar2.c
> 1>varchar2.c
> 1> Creating library
> D:\postgresql\orafce-VERSION_3_13_4\msvc/bin/x86/10.3/lib/orafce.lib and
> object D:\postgresql\orafce-VERSION_3_13_4\msvc/bin/x86/10.3/lib/orafce.exp
> 1>aggregate.obj : error LNK2001: unresolved external symbol _errfinish
> 1>aggregate.obj : error LNK2001: unresolved external symbol _errstart
> 1>aggregate.obj : error LNK2001: unresolved external symbol
> _string_agg_transfn
> 1>aggregate.obj : error LNK2001: unresolved external symbol
> _AggCheckCallContext
> 1>aggregate.obj : error LNK2001: unresolved external symbol _palloc
> 1>aggregate.obj : error LNK2001: unresolved external symbol
> _errmsg_internal
> 1>aggregate.obj : error LNK2001: unresolved external symbol
> _string_agg_finalfn
> 1>aggregate.obj : error LNK2001: unresolved external symbol _pg_qsort
> 1>aggregate.obj : error LNK2001: unresolved external symbol
> _appendStringInfoChar
> 1>aggregate.obj : error LNK2001: unresolved external symbol
> _appendBinaryStringInfo
> 1>aggregate.obj : error LNK2001: unresolved external symbol _makeStringInfo
> 1>aggregate.obj : error LNK2001: unresolved external symbol
> _pg_detoast_datum_packed
> 1>aggregate.obj : error LNK2001: unresolved external symbol _repalloc
> 1>aggregate.obj : error LNK2001: unresolved external symbol
> __imp__CurrentMemoryContext
> 1>alert.obj : error LNK2001: unresolved external symbol _SPI_exec
> 1>alert.obj : error LNK2001: unresolved external symbol _ProcessInterrupts
> 1>alert.obj : error LNK2001: unresolved external symbol _pstrdup
> 1>alert.obj : error LNK2001: unresolved external symbol
> __imp__SPI_processed
> 1>alert.obj : error LNK2001: unresolved external symbol
> _pgwin32_dispatch_queued_signals
>
> ...
>
> orafce.obj : error LNK2001: unresolved external symbol
> _DefineCustomBoolVariable
> 1>orafce.obj : error LNK2001: unresolved external symbol
> _EmitWarningsOnPlaceholders
> 1>charpad.obj : error LNK2001: unresolved external symbol _pg_dsplen
> 1>nvarchar2.obj : error LNK2001: unresolved external symbol
> _pg_mbcharcliplen
> 1>nvarchar2.obj : error LNK2001: unresolved external symbol _pq_getmsgtext
> 1>nvarchar2.obj : error LNK2001: unresolved external symbol _pg_mbstrlen
> 1>varchar2.obj : error LNK2001: unresolved external symbol _varchar_support
> 1>D:\postgresql\orafce-VERSION_3_13_4\msvc\bin\x86\10.3\lib\orafce.dll :
> fatal error LNK1120: 174 unresolved externals
> 1>Done building project "orafce.2010.vcxproj" -- FAILED.
>
>
looks so your project miss seting postgresql.lib

https://github.com/orafce/orafce/blob/master/README.msvc

Under "Linker" -> "Input" -> "Additional Dependencies", add postgres.lib to
the library list

Regards

Pavel

**Comment by gzhcoder** [comment]
> Under "Linker" -> "Input" -> "Additional Dependencies", add postgres.lib to
the library list

Thank you for your prompt. I have already set it, and the error is the same.

**Comment by okbob** [comment]
pá 14. 5. 2021 v 9:02 odesílatel gzhcoder ***@***.***> napsal:

> Under "Linker" -> "Input" -> "Additional Dependencies", add postgres.lib to
> the library list
>
> Thank you for your prompt. I have already set it, and the error is the
> same.
>

ok

please recheck all other settings -

The strange things is

_pgwin32_dispatch_queued_signals
maybe you do build for win32, although you have only 64bit Postgres

**Comment by gzhcoder** [comment]
After changing to 32 bits Postgres, the error is below:

Rebuild started...
1>------ Rebuild All started: Project: orafce, Configuration: 10.3 Win32 ------
1>aggregate.c
1>alert.c
1>assert.c
1>convert.c
1>datefce.c
1>file.c
1>magic.c
1>others.c
1>pipe.c
1>plunit.c
1>plvdate.c
1>plvlex.c
1>plvstr.c
1>plvsubst.c
1>putline.c
1>random.c
1>shmmc.c
1>utility.c
1>orafce.c
1>charlen.c
1>Compiling...
1>charpad.c
1>nvarchar2.c
1>varchar2.c
1>   Creating library D:\postgresql\orafce-VERSION_3_13_4\msvc\/bin/x86/10.3/lib/orafce.lib and object D:\postgresql\orafce-VERSION_3_13_4\msvc\/bin/x86/10.3/lib/orafce.exp
1>plvlex.obj : error LNK2001: unresolved external symbol _orafce_sql_yyerror
1>plvlex.obj : error LNK2001: unresolved external symbol _orafce_sql_scanner_init
1>plvlex.obj : error LNK2001: unresolved external symbol _orafce_sql_yyparse
1>plvlex.obj : error LNK2001: unresolved external symbol _orafce_sql_scanner_finish
1>D:\postgresql\orafce-VERSION_3_13_4\msvc\\bin\x86\10.3\lib\\orafce.dll : fatal error LNK1120: 4 unresolved externals
1>Done building project "orafce.2010.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by gzhcoder** [comment]
> After changing to 32 bits Postgres, the error is below:

postgresql-13.2-2-windows-x64-binaries  →  postgresql-10.17-1-windows-binaries

**Comment by okbob** [comment]
pá 14. 5. 2021 v 10:26 odesílatel gzhcoder ***@***.***>
napsal:

> After changing to 32 bits Postgres, the error is below:
>
> Rebuild started...
> 1>------ Rebuild All started: Project: orafce, Configuration: 10.3 Win32
> ------
> 1>aggregate.c
> 1>alert.c
> 1>assert.c
> 1>convert.c
> 1>datefce.c
> 1>file.c
> 1>magic.c
> 1>others.c
> 1>pipe.c
> 1>plunit.c
> 1>plvdate.c
> 1>plvlex.c
> 1>plvstr.c
> 1>plvsubst.c
> 1>putline.c
> 1>random.c
> 1>shmmc.c
> 1>utility.c
> 1>orafce.c
> 1>charlen.c
> 1>Compiling...
> 1>charpad.c
> 1>nvarchar2.c
> 1>varchar2.c
> 1> Creating library
> D:\postgresql\orafce-VERSION_3_13_4\msvc/bin/x86/10.3/lib/orafce.lib and
> object D:\postgresql\orafce-VERSION_3_13_4\msvc/bin/x86/10.3/lib/orafce.exp
> 1>plvlex.obj : error LNK2001: unresolved external symbol
> _orafce_sql_yyerror
> 1>plvlex.obj : error LNK2001: unresolved external symbol
> _orafce_sql_scanner_init
> 1>plvlex.obj : error LNK2001: unresolved external symbol
> _orafce_sql_yyparse
> 1>plvlex.obj : error LNK2001: unresolved external symbol
> _orafce_sql_scanner_finish
> 1>D:\postgresql\orafce-VERSION_3_13_4\msvc\bin\x86\10.3\lib\orafce.dll :
> fatal error LNK1120: 4 unresolved externals
>
looks to so sqlscan.c was not included and compiled, maybe you miss
sqlparse.c in your project

4. Add existing items - *.c and *.h files except "sqlscan.c". This file is
compiled
   as include of sqlparse.c and should not be compiled as separate c file!

**Comment by gzhcoder** [comment]
> looks to so sqlscan.c was not included and compiled, maybe you miss
sqlparse.c in your project

I'm sorry that I really missed this sqlparse.c. After adding this file in my project, I still get an error.

Rebuild started...
1>------ Rebuild All started: Project: orafce, Configuration: 10.3 Win32 ------
1>aggregate.c
1>alert.c
1>assert.c
1>convert.c
1>datefce.c
1>file.c
1>magic.c
1>others.c
1>pipe.c
1>plunit.c
1>plvdate.c
1>plvlex.c
1>plvstr.c
1>plvsubst.c
1>putline.c
1>random.c
1>shmmc.c
1>sqlparse.c
1>sqlscan.l(517,1): warning C4244: 'initializing': conversion from 'unsigned long' to 'unsigned char', possible loss of data
1>sqlscan.l(522,1): warning C4244: 'initializing': conversion from 'unsigned long' to 'unsigned char', possible loss of data
1>utility.c
1>orafce.c
1>Compiling...
1>charlen.c
1>charpad.c
1>nvarchar2.c
1>varchar2.c
1>   Creating library D:\postgresql\orafce-VERSION_3_13_4\msvc\/bin/x86/10.3/lib/orafce.lib and object D:\postgresql\orafce-VERSION_3_13_4\msvc\/bin/x86/10.3/lib/orafce.exp
1>sqlparse.obj : error LNK2001: unresolved external symbol _orafce_scan_keyword
1>D:\postgresql\orafce-VERSION_3_13_4\msvc\\bin\x86\10.3\lib\\orafce.dll : fatal error LNK1120: 1 unresolved externals
1>Done building project "orafce.2010.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by okbob** [comment]
pá 14. 5. 2021 v 12:33 odesílatel gzhcoder ***@***.***>
napsal:

> looks to so sqlscan.c was not included and compiled, maybe you miss
> sqlparse.c in your project
>
> I'm sorry that I really missed this sqlparse.c. After adding this file in
> my project, I still get an error.
>
> Rebuild started...
> 1>------ Rebuild All started: Project: orafce, Configuration: 10.3 Win32
> ------
> 1>aggregate.c
> 1>alert.c
> 1>assert.c
> 1>convert.c
> 1>datefce.c
> 1>file.c
> 1>magic.c
> 1>others.c
> 1>pipe.c
> 1>plunit.c
> 1>plvdate.c
> 1>plvlex.c
> 1>plvstr.c
> 1>plvsubst.c
> 1>putline.c
> 1>random.c
> 1>shmmc.c
> 1>sqlparse.c
> 1>sqlscan.l(517,1): warning C4244: 'initializing': conversion from
> 'unsigned long' to 'unsigned char', possible loss of data
> 1>sqlscan.l(522,1): warning C4244: 'initializing': conversion from
> 'unsigned long' to 'unsigned char', possible loss of data
> 1>utility.c
> 1>orafce.c
> 1>Compiling...
> 1>charlen.c
> 1>charpad.c
> 1>nvarchar2.c
> 1>varchar2.c
> 1> Creating library
> D:\postgresql\orafce-VERSION_3_13_4\msvc/bin/x86/10.3/lib/orafce.lib and
> object D:\postgresql\orafce-VERSION_3_13_4\msvc/bin/x86/10.3/lib/orafce.exp
> 1>sqlparse.obj : error LNK2001: unresolved external symbol
> _orafce_scan_keyword
> 1>D:\postgresql\orafce-VERSION_3_13_4\msvc\bin\x86\10.3\lib\orafce.dll :
> fatal error LNK1120: 1 unresolved externals
> 1>Done building project "orafce.2010.vcxproj" -- FAILED.
> ========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
>

you miss file parse_keyword.c in your project

**Comment by gzhcoder** [comment]
> you miss file parse_keyword.c in your project
After adding parse_keyword.c in my project, it works! Thank you so much!

[https://www.enterprisedb.com/downloads/postgres-postgresql-downloads](url)
PostgreSQL 13 does not have a Windows x86-32 version.
I want to build the orafce(3.13.4) with postgres13 on windows，how could i do？

**Comment by okbob** [comment]
po 17. 5. 2021 v 8:05 odesílatel gzhcoder ***@***.***> napsal:

> you miss file parse_keyword.c in your project
> After adding parse_keyword.c in my project, it works! Thank you so much!
>
> https://www.enterprisedb.com/downloads/postgres-postgresql-downloads
> <http://url>
> PostgreSQL 13 does not have a Windows x86-32 version.
> I want to build the orafce(3.13.4) with postgres13 on windows，how could i
> do？
>
Why do you need it?

Orafce should be built just against a specific Postgres version. When there
are not 32bit Postgres, then there is no necessity to build 32 bit Orafce.
Last 32bit Postgres was Postgres 10.
If you really need it, then you have to do your own PostgreSQL x86 build.

**Comment by gzhcoder** [comment]
>  Why do you need it?
> 
> Orafce should be built just against a specific Postgres version. When there
> are not 32bit Postgres, then there is no necessity to build 32 bit Orafce.
> Last 32bit Postgres was Postgres 10.
> If you really need it, then you have to do your own PostgreSQL x86 build.

I want to build 64bit orafce(3.13.4) with 64bit postgres13 on windows. Now it works well.
But when I copy the following three files to the directory of postgresql and execute the command "CREATE EXTENSION orafce;", 

①ORF_HOME\msvc\bin\x64\10.3\lib\orafce.dll ⇒ PG_HOME\lib\
②ORF_HOME\orafce.control ⇒ PG_HOME\share\extension\ 
③ORF_HOME\orafce--3.13.sql ⇒ PG_HOME\share\extension\ 

i still got some error below:

ERROR:  could not find function "orafce_replace_empty_strings" in file "D:/Program Files/PostgreSQL/13/lib/orafce.dll"
ERROR:  could not find function "orafce_replace_null_strings" in file "D:/Program Files/PostgreSQL/13/lib/orafce.dll"

**Comment by okbob** [comment]
po 17. 5. 2021 v 15:15 odesílatel gzhcoder ***@***.***>
napsal:

> Why do you need it?
>
> Orafce should be built just against a specific Postgres version. When there
> are not 32bit Postgres, then there is no necessity to build 32 bit Orafce.
> Last 32bit Postgres was Postgres 10.
> If you really need it, then you have to do your own PostgreSQL x86 build.
>
> I want to build 64bit orafce(3.13.4) with 64bit postgres13 on windows. Now
> it works well.
> But when I copy the following three files to the directory of postgresql
> and execute the command "CREATE EXTENSION orafce;",
>
> ①ORF_HOME\msvc\bin\x64\10.3\lib\orafce.dll ⇒ PG_HOME\lib
> ②ORF_HOME\orafce.control ⇒ PG_HOME\share\extension\
> ③ORF_HOME\orafce--3.13.sql ⇒ PG_HOME\share\extension\
>
> i still got some error below:
>
> ERROR: could not find function "orafce_replace_empty_strings" in file
> "D:/Program Files/PostgreSQL/13/lib/orafce.dll"
> ERROR: could not find function "orafce_replace_null_strings" in file
> "D:/Program Files/PostgreSQL/13/lib/orafce.dll"
>
probably you miss compile replace_empty_string.c file

**Comment by gzhcoder** [comment]
> probably you miss compile replace_empty_string.c file

After adding replace_empty_string.c in my project, it works very well!  I really appreciate your answers with patience!
I'm sorry that i also need to build 64bit orafce(3.1.2) with 64bit postgres9.4 on windows.
Getting below error while build:

1>  datefce.c
1>..\..\..\orafce-VERSION_3_1_2\datefce.c(67): error C2370: 'days' : redefinition; different storage class
1>          E:\postgresql\postgresql-9.4.26-1-windows-x64-binaries\pgsql\include\server\utils/datetime.h(271) : see declaration of 'days'

1>  pipe.c
1>..\..\..\orafce-VERSION_3_1_2\pipe.c(1097): error C2121: '#' : invalid character : possibly the result of a macro expansion
1>..\..\..\orafce-VERSION_3_1_2\pipe.c(1097): error C2143: syntax error : missing ')' before 'if'
1>..\..\..\orafce-VERSION_3_1_2\pipe.c(1097): error C2121: '#' : invalid character : possibly the result of a macro expansion
1>..\..\..\orafce-VERSION_3_1_2\pipe.c(1120): error C2061: syntax error : identifier 'dbms_pipe_reset_buffer'
1>..\..\..\orafce-VERSION_3_1_2\pipe.c(1120): error C2059: syntax error : ';'
1>..\..\..\orafce-VERSION_3_1_2\pipe.c(1120): error C2059: syntax error : 'type'

1>  plvdate.c
1>..\..\..\orafce-VERSION_3_1_2\plvdate.c(38): error C2370: 'days' : redefinition; different storage class
1>          E:\postgresql\postgresql-9.4.26-1-windows-x64-binaries\pgsql\include\server\utils/datetime.h(271) : see declaration of 'days'

**Comment by okbob** [comment]
út 18. 5. 2021 v 6:15 odesílatel gzhcoder ***@***.***> napsal:

> probably you miss compile replace_empty_string.c file
>
> After adding replace_empty_string.c in my project, it works very well! I
> really appreciate your answers with patience!
> I'm sorry that i also need to build 64bit orafce(3.1.2) with 64bit
> postgres9.4 on windows.
> Getting below error while build:
>
> 1> datefce.c
> 1>......\orafce-VERSION_3_1_2\datefce.c(67): error C2370: 'days' :
> redefinition; different storage class
> 1>
> E:\postgresql\postgresql-9.4.26-1-windows-x64-binaries\pgsql\include\server\utils/datetime.h(271)
> : see declaration of 'days'
>
> 1> pipe.c
> 1>......\orafce-VERSION_3_1_2\pipe.c(1097): error C2121: '#' : invalid
> character : possibly the result of a macro expansion
> 1>......\orafce-VERSION_3_1_2\pipe.c(1097): error C2143: syntax error :
> missing ')' before 'if'
> 1>......\orafce-VERSION_3_1_2\pipe.c(1097): error C2121: '#' : invalid
> character : possibly the result of a macro expansion
> 1>......\orafce-VERSION_3_1_2\pipe.c(1120): error C2061: syntax error :
> identifier 'dbms_pipe_reset_buffer'
> 1>......\orafce-VERSION_3_1_2\pipe.c(1120): error C2059: syntax error : ';'
> 1>......\orafce-VERSION_3_1_2\pipe.c(1120): error C2059: syntax error :
> 'type'
>
> 1> plvdate.c
> 1>......\orafce-VERSION_3_1_2\plvdate.c(38): error C2370: 'days' :
> redefinition; different storage class
> 1>
> E:\postgresql\postgresql-9.4.26-1-windows-x64-binaries\pgsql\include\server\utils/datetime.h(271)
> : see declaration of 'days'
>

please, try to use
https://github.com/orafce/orafce/releases/tag/VERSION_3_11_0 3.11.0 release

it was last with support Postgres 9.4

Current Orafce extension supports PostgreSQL 9.5 and higher, but support
for 9.5 and 9.6 will be removed early

**Comment by gzhcoder** [comment]
[https://github.com/orafce/orafce/releases/tag/VERSION_3_1_2](url)

I tried to build orafce3.1.2 with postgresql9.4 , not orafce3.12.0
Doesn't orafce3.1.2 support postgresql9.4 ?

**Comment by okbob** [comment]
út 18. 5. 2021 v 7:17 odesílatel gzhcoder ***@***.***> napsal:

> https://github.com/orafce/orafce/releases/tag/VERSION_3_1_2 <http://url>
>
> I tried to build orafce3.1.2 with postgresql9.4 , not orafce3.12.0
> Doesn't orafce3.1.2 support postgresql9.4 ?
>
I think so 3.1.2 should to support Postgres 9.4.

but this release  is really old
https://github.com/orafce/orafce/releases/tag/VERSION_3_1_2

**Comment by gzhcoder** [comment]
> 1> datefce.c
>  1>......\orafce-VERSION_3_1_2\datefce.c(67): error C2370: 'days' :
>  redefinition; different storage class
>  1>
>  E:\postgresql\postgresql-9.4.26-1-windows-x64-binaries\pgsql\include\server\utils/datetime.h(271)
>  : see declaration of 'days'
> 
>  1> pipe.c
>  1>......\orafce-VERSION_3_1_2\pipe.c(1097): error C2121: '#' : invalid
>  character : possibly the result of a macro expansion
>  1>......\orafce-VERSION_3_1_2\pipe.c(1097): error C2143: syntax error :
>  missing ')' before 'if'
>  1>......\orafce-VERSION_3_1_2\pipe.c(1097): error C2121: '#' : invalid
>  character : possibly the result of a macro expansion
>  1>......\orafce-VERSION_3_1_2\pipe.c(1120): error C2061: syntax error :
>  identifier 'dbms_pipe_reset_buffer'
>  1>......\orafce-VERSION_3_1_2\pipe.c(1120): error C2059: syntax error : ';'
>  1>......\orafce-VERSION_3_1_2\pipe.c(1120): error C2059: syntax error :
>  'type'
> 
>  1> plvdate.c
>  1>......\orafce-VERSION_3_1_2\plvdate.c(38): error C2370: 'days' :
>  redefinition; different storage class
>  1>
>  E:\postgresql\postgresql-9.4.26-1-windows-x64-binaries\pgsql\include\server\utils/datetime.h(271)
>  : see declaration of 'days'

Getting above error while build orafce3.1.2 with postgresql9.4:
Please give me some advice on how to fix it if possible.

**Comment by okbob** [comment]
út 18. 5. 2021 v 6:23 odesílatel Pavel Stehule ***@***.***>
napsal:

>
>
> út 18. 5. 2021 v 6:15 odesílatel gzhcoder ***@***.***>
> napsal:
>
>> probably you miss compile replace_empty_string.c file
>>
>> After adding replace_empty_string.c in my project, it works very well! I
>> really appreciate your answers with patience!
>> I'm sorry that i also need to build 64bit orafce(3.1.2) with 64bit
>> postgres9.4 on windows.
>> Getting below error while build:
>>
>> 1> datefce.c
>> 1>......\orafce-VERSION_3_1_2\datefce.c(67): error C2370: 'days' :
>> redefinition; different storage class
>> 1>
>> E:\postgresql\postgresql-9.4.26-1-windows-x64-binaries\pgsql\include\server\utils/datetime.h(271)
>> : see declaration of 'days'
>>
>> 1> pipe.c
>> 1>......\orafce-VERSION_3_1_2\pipe.c(1097): error C2121: '#' : invalid
>> character : possibly the result of a macro expansion
>> 1>......\orafce-VERSION_3_1_2\pipe.c(1097): error C2143: syntax error :
>> missing ')' before 'if'
>> 1>......\orafce-VERSION_3_1_2\pipe.c(1097): error C2121: '#' : invalid
>> character : possibly the result of a macro expansion
>> 1>......\orafce-VERSION_3_1_2\pipe.c(1120): error C2061: syntax error :
>> identifier 'dbms_pipe_reset_buffer'
>> 1>......\orafce-VERSION_3_1_2\pipe.c(1120): error C2059: syntax error :
>> ';'
>> 1>......\orafce-VERSION_3_1_2\pipe.c(1120): error C2059: syntax error :
>> 'type'
>>
>
I checked this code, and it is absolutely correct. It looks like some
problem in you configuration

1> plvdate.c
>> 1>......\orafce-VERSION_3_1_2\plvdate.c(38): error C2370: 'days' :
>> redefinition; different storage class
>> 1>
>> E:\postgresql\postgresql-9.4.26-1-windows-x64-binaries\pgsql\include\server\utils/datetime.h(271)
>> : see declaration of 'days'
>>
>
> please, try to use
> https://github.com/orafce/orafce/releases/tag/VERSION_3_11_0 3.11.0
> release
>
> it was last with support Postgres 9.4
>
> Current Orafce extension supports PostgreSQL 9.5 and higher, but support
> for 9.5 and 9.6 will be removed early
>

I found some older compiled dll of Orafce

https://groups.google.com/g/orafce-general/c/bZNUXXR1RsQ

**Comment by okbob** [comment]
út 18. 5. 2021 v 7:46 odesílatel gzhcoder ***@***.***> napsal:

> 1> datefce.c
> 1>......\orafce-VERSION_3_1_2\datefce.c(67): error C2370: 'days' :
> redefinition; different storage class
> 1>
>
> E:\postgresql\postgresql-9.4.26-1-windows-x64-binaries\pgsql\include\server\utils/datetime.h(271)
> : see declaration of 'days'
>
> 1> pipe.c
> 1>......\orafce-VERSION_3_1_2\pipe.c(1097): error C2121: '#' : invalid
> character : possibly the result of a macro expansion
> 1>......\orafce-VERSION_3_1_2\pipe.c(1097): error C2143: syntax error :
> missing ')' before 'if'
> 1>......\orafce-VERSION_3_1_2\pipe.c(1097): error C2121: '#' : invalid
> character : possibly the result of a macro expansion
> 1>......\orafce-VERSION_3_1_2\pipe.c(1120): error C2061: syntax error :
> identifier 'dbms_pipe_reset_buffer'
> 1>......\orafce-VERSION_3_1_2\pipe.c(1120): error C2059: syntax error : ';'
> 1>......\orafce-VERSION_3_1_2\pipe.c(1120): error C2059: syntax error :
> 'type'
>
> 1> plvdate.c
> 1>......\orafce-VERSION_3_1_2\plvdate.c(38): error C2370: 'days' :
> redefinition; different storage class
> 1>
>
> E:\postgresql\postgresql-9.4.26-1-windows-x64-binaries\pgsql\include\server\utils/datetime.h(271)
> : see declaration of 'days'
>
> Getting above error while build orafce3.1.2 with postgresql9.4:
> Please give me some advice on how to fix it if possible.
>

I have no idea.  The compilation on MS is terrible work. I develop Orafce
on Linux, and it is possible, so some releases are not compileable on MS.
There are lot of factors, that can break it. Version of VS, version of
runtime library that you use, version of runtime library that use Postgres,
...

Please, try to check Orafce 3.3.1. There you can be sure so build for MS is
possible.

Please, try to apply steps from README.msvc (it is in master branch) on
your project configuration. Or use the compiled dll from the link that I
sent to you.

**Comment by gzhcoder** [comment]
> Please, try to check Orafce 3.3.1. There you can be sure so build for MS is
> possible.
> 
> Please, try to apply steps from README.msvc (it is in master branch) on
> your project configuration. Or use the compiled dll from the link that I
> sent to you.

I'm going to replace Orafce 3.1.2 with Orafce 3.3.1
Thank you very much for all your assistance.
