### ISSUE TITLE
Can't create extension orafce in Postgresql 13

### ISSUE THREAD

**Issue by moshanh** [orafce/orafce#138]
Hi orafce team 
I am getting error while running `create extension orafce;`.  Can anyone please help me with this issue?!
Thanks in advance!

postgres=# create extension orafce;
ERROR:  could not load library "/usr/pgsql-13/lib/orafce.so": /usr/pgsql-13/lib/orafce.so: undefined symbol: NumScanKeywords
postgres=# SELECT * FROM pg_available_extensions;
  name   | default_version | installed_version |                                            comment                                            
---------+-----------------+-------------------+-----------------------------------------------------------------------------------------------
 plpgsql | 1.0             | 1.0               | PL/pgSQL procedural language
 orafce  | 3.13            |                   | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS
(2 rows)

postgres=# select version();
                                                 version                                                 
---------------------------------------------------------------------------------------------------------
 PostgreSQL 13.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
(1 row)

**Comment by okbob** [comment]
čt 15. 7. 2021 v 9:14 odesílatel moshanh ***@***.***> napsal:

> Hi orafce team
> I am getting error while running create extension orafce;. Can anyone
> please help me with this issue?!
> Thanks in advance!
>
> postgres=# create extension orafce;
> ERROR: could not load library "/usr/pgsql-13/lib/orafce.so":
> /usr/pgsql-13/lib/orafce.so: undefined symbol: NumScanKeywords
> postgres=# SELECT * FROM pg_available_extensions;
> name | default_version | installed_version | comment
>
> ---------+-----------------+-------------------+-----------------------------------------------------------------------------------------------
> plpgsql | 1.0 | 1.0 | PL/pgSQL procedural language
> orafce | 3.13 | | Functions and operators that emulate a subset of
> functions and packages from the Oracle RDBMS
> (2 rows)
> postgres=# select version();
> version
>
> PostgreSQL 13.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5
> 20150623 (Red Hat 4.8.5-44), 64-bit
> (1 row)
>

 You have the wrong dll file. Orafce like any other compiled extensions for
Postgres are compiled against one specific major version.

The Symbol NumScanKeywords was removed in Postgres 12. You need to use dll
file (library) compiled for PostgreSQL 13.

**Comment by moshanh** [comment]
Thanks for your help, I changed the version to 3.15.1 and it was successful.

**Comment by okbob** [comment]
čt 15. 7. 2021 v 9:45 odesílatel moshanh ***@***.***> napsal:

> Thanks for your help, I changed the version to 3.15.1 and it was
> successful.
>

super :)

Pavel
