### ISSUE TITLE
unable to compile orafce due to redefinition of 'pipe' in pipe.c file in Fedora 35

### ISSUE THREAD

**Issue by zmiklank** [orafce/orafce#139]
Hello.
I am encountering this problem, when building orafce in Fedora 35 environment:
```
pipe.c:94:3: error: redefinition of 'pipe' as different kind of symbol
} pipe;
  ^
/usr/include/unistd.h:437:12: note: previous definition is here
extern int pipe (int __pipedes[2]) __THROW __wur;
           ^
```
Interesting is, that in Fedora 34 everything works OK. Version postgresql-server-devel changed from 13.1-1 to 13.4-1 between Fedora 34 and 35, if that information helps somehow.

The compilation is successful when the pipe typedef is renamed.
Have you encountered same problem yet? Would the renaming of the pipe typedef be a proper solution?

**Comment by okbob** [comment]
yes, using the identifier "pipe" was not good idea. I renamed it, and released new version of orafce https://github.com/orafce/orafce/releases/tag/VERSION_3_16_0

**Comment by zmiklank** [comment]
Thank you.

**Comment by okbob** [comment]
Thank you for report

pá 17. 9. 2021 v 11:13 odesílatel zmiklank ***@***.***>
napsal:
