### ISSUE TITLE
encounter error when run timestamp without time zone + integer

### ISSUE THREAD

**Issue by snzip** [orafce/orafce#142]
orafce-3.14.0

 select (now()::timestamp without time zone - 1);
ERROR:  operator is not unique: timestamp without time zone - integer
第1行select (now()::timestamp without time zone - 1);
                                                ^
提示:  Could not choose a best candidate operator. You might need to add explicit type casts.

ppm_pg_beta=# \do
                                    运算子列表
 架构模式 | 名称 | 左参数类型  | 右参数类型  |          结果类型           | 描述
----------+------+-------------+-------------+-----------------------------+------
 oracle   | +    | oracle.date | bigint      | timestamp without time zone |
 oracle   | +    | oracle.date | integer     | timestamp without time zone |
 oracle   | +    | oracle.date | numeric     | timestamp without time zone |
 oracle   | +    | oracle.date | smallint    | timestamp without time zone |
 oracle   | -    | oracle.date | bigint      | timestamp without time zone |
 oracle   | -    | oracle.date | integer     | timestamp without time zone |
 oracle   | -    | oracle.date | numeric     | timestamp without time zone |
 oracle   | -    | oracle.date | oracle.date | double precision            |
 oracle   | -    | oracle.date | smallint    | timestamp without time zone |

**Comment by okbob** [comment]
It is working on my computer:
```
postgres=# select oracle.sysdate() + 1;
┌─────────────────────┐
│      ?column?       │
╞═════════════════════╡
│ 2021-10-10 03:26:13 │
└─────────────────────┘
(1 row)

postgres=# select (now()::timestamp without time zone - 1);
┌─────────────────────┐
│      ?column?       │
╞═════════════════════╡
│ 2021-10-08 05:26:27 │
└─────────────────────┘
(1 row)
```
Some things like this can be partially broken without big possibility to fix it due significantly different type system in Postgres and in Oracle.

When you use Orafce, then it is good idea to set `search_path` to `oracle` schema

Maybe this is problem on your comp:
```
postgres=# select (now()::timestamp without time zone - 1);
ERROR:  operator does not exist: timestamp without time zone - integer
LINE 1: select (now()::timestamp without time zone - 1);
                                                   ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
postgres=# set search_path to public, oracle;
SET
postgres=# select (now()::timestamp without time zone - 1);
┌─────────────────────┐
│      ?column?       │
╞═════════════════════╡
│ 2021-10-08 05:30:15 │
└─────────────────────┘
(1 row)
```
