### ISSUE TITLE
Installation on MacOs

### ISSUE THREAD

**Issue by robliebke** [orafce/orafce#155]
Are there any documentation or instructions to install it on MacOS?

**Comment by okbob** [comment]
út 23. 11. 2021 v 0:56 odesílatel Rob L. ***@***.***> napsal:

> Are there any documentation or instructions to install it on MacOS?
>
There should not be any problem - in this context it should be same like
installation of any postgres's extension on MacOS or BSD system

Unfortunately, I do not have a MacOS, so I have not any real experience,
but nobody reported any issues.

**Comment by robliebke** [comment]
I was able to compile it fine.

**Comment by okbob** [comment]
please, can you write some notes about compilation on macos to README?



pá 26. 11. 2021 v 1:48 odesílatel Rob L. ***@***.***> napsal:
