### ISSUE TITLE
Linking error while compiling in Windows.

### ISSUE THREAD

**Issue by borealis8uno** [orafce/orafce#156]
Hello,
I am trying to build orafce-VERSION_3_17_0 under Windows with Visual Studio 2019 using https://www.2ndquadrant.com/en/blog/compiling-postgresql-extensions-visual-studio-windows/ as template.
The build fails in linking with 4 errors: 
Error	LNK2001	unresolved external symbol orafce_sql_yyerror
Error	LNK2001	unresolved external symbol orafce_sql_scanner_init
Error	LNK2001	unresolved external symbol orafce_sql_yyparse
Error	LNK2001	unresolved external symbol orafce_sql_scanner_finish
All of them related to orafce-VERSION_3_17_0\msvc\plvlex.obj

Maybe there is a dependency missing... Do you have any hint?
Thank you!

**Comment by okbob** [comment]
you have to use this checklist

https://github.com/orafce/orafce/blob/master/README.msvc

Maybe you have to problem in 

4. Add existing items - *.c and *.h files except "sqlscan.c". This file is compiled
   as include of sqlparse.c and should not be compiled as separate c file!
