### ISSUE TITLE
No image of some function syntax

### ISSUE THREAD

**Issue by aero-byte** [orafce/orafce#159]
Dear orafce team,

I cannot see the syntax image for the following functions. (This will result in a 404 error.)

・REGEXP_COUNT
・REGEXP_INSTR
・REGEXP_LIKE
・REGEXP_SUBSTR
・REGEXP_REPLACE

・reference
[https://github.com/orafce/orafce/blob/master/doc/orafce_documentation/Orafce_Documentation_05.md](url)

・The directory containing the images
[https://github.com/orafce/orafce/tree/master/doc/orafce_documentation/gif](url)

**Comment by okbob** [comment]
Unfortunately nobody made these syntax images. I removed these broken indexes.
