### ISSUE TITLE
Utl_file package is not supported on Microsoft Windows

### ISSUE THREAD

**Issue by deepakp555** [orafce/orafce#165]
![uti file issue](https://user-images.githubusercontent.com/64629858/149288908-503ad37f-37da-4038-a58a-fbf6da2a5672.png)
I have orafce version 3.7. Running PostgreSql version is 13. It is running on windows 10 environment. When executing the util_file getting below error "Utl_file package is not supported on Microsoft Windows". Refer the attached screen shot

**Comment by okbob** [comment]
čt 13. 1. 2022 v 11:46 odesílatel deepakp555 ***@***.***>
napsal:

> [image: uti file issue]
> <https://user-images.githubusercontent.com/64629858/149288908-503ad37f-37da-4038-a58a-fbf6da2a5672.png>
> I have orafce version 3.7. Running PostgreSql version is 13. It is running
> on windows 10 environment. When executing the util_file getting below error
> "Utl_file package is not supported on Microsoft Windows". Refer the
> attached screen shot
>

you need Orafce 3.13.4

https://github.com/orafce/orafce/releases/tag/VERSION_3_13_4
