### ISSUE TITLE
Can't create extension orafce in postgres 12.5

### ISSUE THREAD

**Issue by Hanane-Amghar** [orafce/orafce#167]
Hello , 
I am getting this error while running :  create extension orafce;
Can you please help me with this issue?
Thanks in advance ^^

admin=# CREATE EXTENSION orafce;
ERROR:  could not load library "/opt/pgsql/na/12.5/lib/orafce.so": /opt/pgsql/na/12.5/lib/orafce.so: undefined symbol: NumScanKeywords

template1=# select version();
                                                 version
---------------------------------------------------------------------------------------------------------
 PostgreSQL 12.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
(1 row)

template1=# select *  from pg_catalog.pg_available_extensions;
        name        | default_version | installed_version |                                            comment
--------------------+-----------------+-------------------+-----------------------------------------------------------------------------------------------
 orafce             | 3.8             |                   | Functions and operators that emulate a subset of functions and packages from the Oracle 
 plpgsql            | 1.0             | 1.0               | PL/pgSQL procedural language

[root@opprqpra-b var]# echo $LD_LIBRARY_PATH
/opt/rh/llvm-toolset-7/root/usr/lib64:/opt/rh/llvm-toolset-7/root/usr/lib64:/opt/pgsql/na/12.5/lib/:/opt/oracle/instantclient_21_4/libclntsh.so.18.1

**Comment by okbob** [comment]
looks so you use wrong orafce.so. PostgreSQL extensions (like Orafce) should be compiled against major Postgres release. So if you use pg 12, then you need Orafce for pg 12. Probably you have installed Orafce for Pg 11.

**Comment by Hanane-Amghar** [comment]
Yes that was the problem, thank you. 
I've installed orafce for pg 12 and I managed to create an orafce extension . 
admin=# CREATE extension orafce;
CREATE EXTENSION
