### ISSUE TITLE
VERSION_3_18_1 does not belong to any branch on this repository

### ISSUE THREAD

**Issue by Denchick** [orafce/orafce#168]
Hello!
It's really stupid, but after `git clone` I cannot checkout `VERSION_3_18_1` tag. Seems like the last release is ahead of the master branch. Even GitHub says that something is [wrong](https://github.com/orafce/orafce/tree/VERSION_3_18_1):
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
Could you merge VERSION_3_18_1 to master?

**Comment by okbob** [comment]
I am not sure what I did wrong, because it is worked - I uploaded 3.18.1 to pgxn two weeks ago. But anyway, it should be fixed now. Please, check.
