### ISSUE TITLE
Behavior of the oracle.substr() function

### ISSUE THREAD

**Issue by darold** [orafce/orafce#169]
Hi Pavel,

In Oracle when a call to substr() doesn't match it returns NULL.
```
SQL> set null '¤'
SQL> SELECT substr('hello', 6, 4) AS SUB FROM DUAL;

SUB
------
   ¤
```

Using Orafce substr() function it returns an empty string like the PostgreSQL substr() builtin function. 
```
dev=# \pset null ¤;
Null display is "¤".
dev=# SELECT oracle.substr('hello', 6, 4);
 substr
--------

(1 row)
```

Is this something intentional?

The only reason I see is that it avoid nullify the entire result of a concat with a substr() call returning NULL. I see that you have also implemented the concat operator with varchar2 for null safe concat when `orafce.varchar2_null_safe_concat` is enables. I have tried with the oracle.substr() function but the behavior doesn't change, it always returns an empty string.
```
dev=# \pset null ¤;
Null display is "¤".
tws1e_dev=#SET orafce.varchar2_null_safe_concat TO off;
SET
tws1e_dev=# SELECT oracle.substr('hello'::varchar2, 6, 4);
 substr 
--------
 
(1 row)

tws1e_dev=# SET orafce.varchar2_null_safe_concat TO on;
SET
tws1e_dev=# SELECT oracle.substr('hello'::varchar2, 6, 4);
 substr 
--------
 
(1 row)
```
 Perhaps it make sens that oracle.substr() returns NULL when `orafce.varchar2_null_safe_concat` is enable and an empty string otherwise?

Actually I have an issue where the call to substr() a la postgresql returns wrong results when used in an index.
```
CREATE INDEX foo_idx ON bar_tb ("col_a", TO_NUMBER(SUBSTR("col_b",2,1)));
```
Do you think there is something to fix here and how or that it should stay like that?

**Comment by okbob** [comment]
st 9. 3. 2022 v 16:19 odesílatel Gilles Darold ***@***.***>
napsal:

> Hi Pavel,
>
> In Oracle when a call to substr() doesn't match it returns NULL.
>
> SQL> set null '¤'
>
> SQL> SELECT substr('hello', 6, 4) AS SUB FROM DUAL;
>
>
>
> SUB
>
> ------
>
>    ¤
>
>
> Using Orafce substr() function it returns an empty string like the
> PostgreSQL substr() builtin function.
>
> dev=# \pset null ¤;
>
> Null display is "¤".
>
> dev=# SELECT oracle.substr('hello', 6, 4);
>
>  substr
>
> --------
>
>
>
> (1 row)
>
>
> Is this something intentional?
>
If I remember correctly, this is one of the old codes of Orafce. At this
time I did not have good knowledge of this specific part, and there is not
consistent design related to this issue. Probably I just rewroted plpgsql
code from documentation to C.


> The only reason I see is that it avoid nullify the entire result of a
> concat with a substr() call returning NULL. I see that you have also
> implemented the concat operator with varchar2 for null safe concat when
> orafce.varchar2_null_safe_concat is enables. I have tried with the
> oracle.substr() function but the behavior doesn't change, it always returns
> an empty string.
>
> dev=# \pset null ¤;
>
> Null display is "¤".
>
> tws1e_dev=#SET orafce.varchar2_null_safe_concat TO off;
>
> SET
>
> tws1e_dev=# SELECT oracle.substr('hello'::varchar2, 6, 4);
>
>  substr
>
> --------
>
>
>
> (1 row)
>
>
>
> tws1e_dev=# SET orafce.varchar2_null_safe_concat TO on;
>
> SET
>
> tws1e_dev=# SELECT oracle.substr('hello'::varchar2, 6, 4);
>
>  substr
>
> --------
>
>
>
> (1 row)
>
>
> Perhaps it make sens that oracle.substr() returns NULL when
> orafce.varchar2_null_safe_concat is enable and an empty string otherwise?
>
It requires oracle.substr for varchar2 and for nvarchar2 types. And there
can be problems with compatibility.


> Actually I have an issue where the call to substr() a la postgresql
> returns wrong results when used in an index.
>
> CREATE INDEX foo_idx ON bar_tb ("col_a", TO_NUMBER(SUBSTR("col_b",2,1)));
>
>
> Do you think there is something to fix here and how or that it should stay
> like that?
>
It is ugly issue. Any fix of this issue can break compatibility.

Maybe I can support a new GUC like
orafce.substr_replace_returned_empty_str, that can enforce returning NULL
instead of an empty string. But in this case reindex is necessary.

?

Regards

Pavel

**Comment by okbob** [comment]
so 12. 3. 2022 v 19:55 odesílatel Pavel Stehule ***@***.***>
napsal:

>
>
> st 9. 3. 2022 v 16:19 odesílatel Gilles Darold ***@***.***>
> napsal:
>
>> Hi Pavel,
>>
>> In Oracle when a call to substr() doesn't match it returns NULL.
>>
>> SQL> set null '¤'
>>
>> SQL> SELECT substr('hello', 6, 4) AS SUB FROM DUAL;
>>
>>
>>
>> SUB
>>
>> ------
>>
>>    ¤
>>
>>
>> Using Orafce substr() function it returns an empty string like the
>> PostgreSQL substr() builtin function.
>>
>> dev=# \pset null ¤;
>>
>> Null display is "¤".
>>
>> dev=# SELECT oracle.substr('hello', 6, 4);
>>
>>  substr
>>
>> --------
>>
>>
>>
>> (1 row)
>>
>>
>> Is this something intentional?
>>
> If I remember correctly, this is one of the old codes of Orafce. At this
> time I did not have good knowledge of this specific part, and there is not
> consistent design related to this issue. Probably I just rewroted plpgsql
> code from documentation to C.
>
>
>> The only reason I see is that it avoid nullify the entire result of a
>> concat with a substr() call returning NULL. I see that you have also
>> implemented the concat operator with varchar2 for null safe concat when
>> orafce.varchar2_null_safe_concat is enables. I have tried with the
>> oracle.substr() function but the behavior doesn't change, it always returns
>> an empty string.
>>
>> dev=# \pset null ¤;
>>
>> Null display is "¤".
>>
>> tws1e_dev=#SET orafce.varchar2_null_safe_concat TO off;
>>
>> SET
>>
>> tws1e_dev=# SELECT oracle.substr('hello'::varchar2, 6, 4);
>>
>>  substr
>>
>> --------
>>
>>
>>
>> (1 row)
>>
>>
>>
>> tws1e_dev=# SET orafce.varchar2_null_safe_concat TO on;
>>
>> SET
>>
>> tws1e_dev=# SELECT oracle.substr('hello'::varchar2, 6, 4);
>>
>>  substr
>>
>> --------
>>
>>
>>
>> (1 row)
>>
>>
>> Perhaps it make sens that oracle.substr() returns NULL when
>> orafce.varchar2_null_safe_concat is enable and an empty string otherwise?
>>
> It requires oracle.substr for varchar2 and for nvarchar2 types. And there
> can be problems with compatibility.
>
>
>> Actually I have an issue where the call to substr() a la postgresql
>> returns wrong results when used in an index.
>>
>> CREATE INDEX foo_idx ON bar_tb ("col_a", TO_NUMBER(SUBSTR("col_b",2,1)));
>>
>>
>> Do you think there is something to fix here and how or that it should
>> stay like that?
>>
> It is ugly issue. Any fix of this issue can break compatibility.
>
> Maybe I can support a new GUC like
> orafce.substr_replace_returned_empty_str, that can enforce returning NULL
> instead of an empty string. But in this case reindex is necessary.
>

I checked code, and orafce substr is based on PostgreSQL substr, and almost
all orafce string functions have the same behaviour.

The changing of this needs significant revision of orafce. It can be hard
to break compatibility. I don't see an available solution on orafce side
related to substr function

But I have another idea. In this case I can allow empty string on the
TO_NUMBER side function.There is clear semantics, and easy implementation.

Regards

Pavel

**Comment by okbob** [comment]
see last commit

Pavel

ne 13. 3. 2022 v 8:58 odesílatel Pavel Stehule ***@***.***>
napsal:

**Comment by darold** [comment]
I'm fine with allowing empty string to to_number() with returning NULL, especially that this is also the behavior of Oracle TO_NUMBER. Thanks Pavel.

**Comment by okbob** [comment]
ne 13. 3. 2022 v 17:59 odesílatel Gilles Darold ***@***.***>
napsal:

> I'm fine with allowing empty string to to_number() with returning NULL,
> especially that this is also the behavior of Oracle TO_NUMBER. Thanks Pavel.
>
super :)

Thank you for hint
