### ISSUE TITLE
nvl and decode not working for different numbers data types like oracle 

### ISSUE THREAD

**Issue by ihamza** [orafce/orafce#17]
when using nvl or decode with different numeric data types like numeric and integer 
like
select nvl(0,1.0) from dual;
it generates  error
function nvl(integer, numeric) does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

the workaround may be using select nvl(0.0,1.0) from dual;

**Comment by vinpokale** [comment]
I think we can create more function using coalesce().
Example:
CREATE OR REPLACE FUNCTION public.NVL(NUMERIC,INT)
RETURNS NUMERIC AS $$
SELECT COALESCE($1,$2);
$$ LANGUAGE SQL IMMUTABLE;
There are more cases which works in Oracle.
Is it possible to add more functions with different arguments.
Comment?

**Comment by okbob** [comment]
It doesn't help too much, bacause you have to enumerate all type's
combinations.  But it is probably only one solutions.

Second possibility is fix behave of polymorphic parameters. But it is long
way

Pavel



2015-02-06 13:49 GMT+01:00 Vinayak <notifications@github.com>:

**Comment by okbob** [comment]
I checked this issue again and I am thinking so current behave is not nice, but is best what is possible. I can fix NVL(0,0.1), but there is trap for migration. On Oracle if first parameter is text, then result is text, when first parameter is numeric, then result type is common type for both parameters. This behave I cannot to do in Postgres (without hacking parser). So it is safer when user have to choose target type explicitly. I can fix a numbers, but I'll break a text type.

**Comment by okbob** [comment]
Closing - impossible to solve this issues correctly with PostgreSQL type system.
