### ISSUE TITLE
Can orafce support sysdate without parentheses ?

### ISSUE THREAD

**Issue by zyl6628156** [orafce/orafce#170]
-- oracle
SQL> select sysdate from dual;

SYSDATE
-------------------
2022-04-01 17:29:39

-- orafce
postgres=# select sysdate from dual;
ERROR:  column "sysdate" does not exist
LINE 1: select sysdate from dual;
               ^
postgres=# select sysdate() from dual;
       sysdate
---------------------
 2022-04-01 17:30:56
(1 row)

Can orafce support sysdate without parentheses ?
thanks

**Comment by okbob** [comment]
pá 1. 4. 2022 v 11:32 odesílatel zyl6628156 ***@***.***>
napsal:

> -- oracle
> SQL> select sysdate from dual;
> SYSDATE
>
> 2022-04-01 17:29:39
> -- orafce
> postgres=# select sysdate from dual;
> ERROR: column "sysdate" does not exist
> LINE 1: select sysdate from dual;
> ^
> postgres=# select sysdate() from dual;
> sysdate
>
> 2022-04-01 17:30:56
> (1 row)
>
> Can orafce support sysdate without parentheses ?
> thanks
>

Unfortunately It cannot. Postgres doesn't allow this syntax

Regards

Pavel

**Comment by darold** [comment]
Hi,

A possible workaround could be:
```
orafce=# CREATE OR REPLACE VIEW public.dual AS SELECT 'X'::character varying AS dummy, statement_timestamp() as sysdate;
CREATE VIEW


orafce=# SELECT SYSDATE FROM DUAL;
            sysdate            
-------------------------------
 2022-04-01 12:30:36.678775+02
(1 line)
```

**Comment by zyl6628156** [comment]
thanks
