### ISSUE TITLE
REGEXP_INSTR

### ISSUE THREAD

**Issue by zyl6628156** [orafce/orafce#171]
https://github.com/orafce/orafce/blob/master/doc/orafce_documentation/Orafce_Documentation_05.md

SELECT REGEXP_INSTR('123 123456 1234567, 1234567 1234567 12', '[^ ]+', 1, 6) FROM DUAL;
 regexp_instr 
--------------
           37

-- oracle 
SQL> SELECT REGEXP_INSTR('123 123456 1234567, 1234567 1234567 12', '[^ ]+', 1, 6) FROM DUAL;

REGEXP_INSTR('1231234561234567,1234567123456712','[^]+',1,6)
------------------------------------------------------------
                                                          37

-- orafce 3.18

postgres=# \dx
                                                       List of installed extensions
        Name        | Version |   Schema   |                                          Description
--------------------+---------+------------+-----------------------------------------------------------------------------------------------
 orafce             | 3.18    | public     | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS
 pg_stat_statements | 1.8     | public     | track planning and execution statistics of all SQL statements executed
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
(3 rows)

postgres=# SELECT REGEXP_INSTR('123 123456 1234567, 1234567 1234567 12', '[^ ]+', 1, 6) FROM DUAL;
 regexp_instr
--------------
            1
(1 row)

**Comment by darold** [comment]
@okbob I will have a look to this issue.

**Comment by okbob** [comment]
I cannot to verify this issue
<pre>
(2022-04-03 12:51:24) postgres=# SELECT REGEXP_INSTR('123 123456 1234567, 1234567 1234567 12', '[^ ]+', 1, 6) FROM DUAL;
┌──────────────┐
│ regexp_instr │
╞══════════════╡
│           37 │
└──────────────┘
(1 row)
</pre>

Can you describe your environment? I have default setting.

**Comment by zyl6628156** [comment]
[root@pgtest1 orafce-master]# psql
psql (13.3)
Type "help" for help.

postgres=# show search_path;
             search_path
-------------------------------------
 "$user", public, oracle, pg_catalog
(1 row)

postgres=# \dx
                                                       List of installed extensions
        Name        | Version |   Schema   |                                          Description
--------------------+---------+------------+-----------------------------------------------------------------------------------------------
 orafce             | 3.19    | public     | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS
 pg_stat_statements | 1.8     | public     | track planning and execution statistics of all SQL statements executed
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
(3 rows)

postgres=# SELECT REGEXP_INSTR('123 123456 1234567, 1234567 1234567 12', '[^ ]+', 1, 6) FROM DUAL;
 regexp_instr
--------------
            1
(1 row)

**Comment by okbob** [comment]
ne 3. 4. 2022 v 13:46 odesílatel zyl6628156 ***@***.***>
napsal:

> ***@***.*** orafce-master]# psql
> psql (13.3)
> Type "help" for help.
> postgres=# show search_path;
> search_path
>
> "$user", public, oracle, pg_catalog
> (1 row)
>
> postgres=# \dx
> List of installed extensions
> Name | Version | Schema | Description
>
> --------------------+---------+------------+-----------------------------------------------------------------------------------------------
> orafce | 3.19 | public | Functions and operators that emulate a subset of
> functions and packages from the Oracle RDBMS
> pg_stat_statements | 1.8 | public | track planning and execution
> statistics of all SQL statements executed
> plpgsql | 1.0 | pg_catalog | PL/pgSQL procedural language
> (3 rows)
> postgres=# SELECT REGEXP_INSTR('123 123456 1234567, 1234567 1234567 12',
> '[^ ]+', 1, 6) FROM DUAL;
> regexp_instr
>
>         1
> re
>
> (1 row)
>

Now, I am able to reproduce this issue. I did tests on Postgres 15 where
regexp_instr is built in function.

Orafce's implementation that is implemented in PLpgSQL is buggy.

searching position of some pattern like

v_pos := (SELECT position((SELECT (regexp_matches(substr($1, $3),
v_pattern, 'pg'))[1] OFFSET $4 - 1 LIMIT 1) IN $1));

can produce wrong result in some cases like here, where 6th pattern is 12,
and tis substring can be find more times in input string

Maybe C implementation can be backported - I checked it, and the SQL API
for regexp doesn't return position, so correct implementation in PLpgSQL
isn't easy

Regards

Pavel

**Comment by okbob** [comment]
ne 3. 4. 2022 v 15:36 odesílatel Pavel Stehule ***@***.***>
napsal:

>
>
> ne 3. 4. 2022 v 13:46 odesílatel zyl6628156 ***@***.***>
> napsal:
>
>> ***@***.*** orafce-master]# psql
>> psql (13.3)
>> Type "help" for help.
>> postgres=# show search_path;
>> search_path
>>
>> "$user", public, oracle, pg_catalog
>> (1 row)
>>
>> postgres=# \dx
>> List of installed extensions
>> Name | Version | Schema | Description
>>
>> --------------------+---------+------------+-----------------------------------------------------------------------------------------------
>> orafce | 3.19 | public | Functions and operators that emulate a subset of
>> functions and packages from the Oracle RDBMS
>> pg_stat_statements | 1.8 | public | track planning and execution
>> statistics of all SQL statements executed
>> plpgsql | 1.0 | pg_catalog | PL/pgSQL procedural language
>> (3 rows)
>> postgres=# SELECT REGEXP_INSTR('123 123456 1234567, 1234567 1234567 12',
>> '[^ ]+', 1, 6) FROM DUAL;
>> regexp_instr
>>
>>         1
>> re
>>
>> (1 row)
>>
>
> Now, I am able to reproduce this issue. I did tests on Postgres 15 where
> regexp_instr is built in function.
>
> Orafce's implementation that is implemented in PLpgSQL is buggy.
>
> searching position of some pattern like
>
> v_pos := (SELECT position((SELECT (regexp_matches(substr($1, $3),
> v_pattern, 'pg'))[1] OFFSET $4 - 1 LIMIT 1) IN $1));
>
> can produce wrong result in some cases like here, where 6th pattern is 12,
> and tis substring can be find more times in input string
>
> Maybe C implementation can be backported - I checked it, and the SQL API
> for regexp doesn't return position, so correct implementation in PLpgSQL
> isn't easy
>

So I don't think so backport is easy too, but maybe using regex API can be
still more simple and faster than implementation in PLpgSQL.

**Comment by okbob** [comment]
New form of plpgsql implementation of regexp_instr
<pre>
CREATE OR REPLACE FUNCTION public.regexp_instr(text, text, integer, integer)
 RETURNS integer
 LANGUAGE plpgsql
 STRICT
AS $function$
DECLARE
  v_pos integer;
  v_pattern text;
  r record;
  start_pos integer DEFAULT 1;
  new_start integer;
BEGIN
  IF $3 < 1 THEN
    RAISE EXCEPTION 'argument ''position'' must be a number greater than 0';
  END IF;
  IF $4 < 1 THEN
    RAISE EXCEPTION 'argument ''occurence'' must be a number greater than 0';
  END IF;

  -- Without subexpression specified, assume 0 which mean that the first
  -- position for the substring matching the whole pattern is returned.
  -- We need to enclose the pattern between parentheses.
  v_pattern := '(' || $2 || ')';

  -- Oracle default behavior is newline-sensitive,
  -- PostgreSQL not, so force 'p' modifier to affect
  -- newline-sensitivity but not ^ and $ search.
  
  $1 := substr($1, $3);
  start_pos := $3; 

  FOR r IN SELECT (regexp_matches($1, v_pattern, 'pg'))[1]
  LOOP
    v_pos := position(r.regexp_matches IN $1);
    
    IF $4 = 1 THEN
      RETURN v_pos + start_pos - 1;
    ELSE
      $4 := $4 - 1;
    END IF;

    new_start := v_pos + length(r.regexp_matches);
    $1 := substr($1, new_start);
    start_pos := start_pos + new_start - 1;
  END LOOP;

  RETURN 0;
END;
$function$
</pre>

**Comment by zyl6628156** [comment]
thanks, problem solved,  worship you

**Comment by okbob** [comment]
should be fixed in 3.20
