### ISSUE TITLE
SUBSTRB

### ISSUE THREAD

**Issue by zyl6628156** [orafce/orafce#172]
`
-- oracle

SQL> SELECT SUBSTRB('aaabbbccc',-4,1) FROM DUAL;

S
-
b

SQL> SELECT SUBSTRB('aaabbbccc',-4,2) FROM DUAL;

SU
--
bc

SQL> SELECT SUBSTRB('aaabbbccc',-4,3) FROM DUAL;

SUB
---
bcc

SQL> SELECT SUBSTRB('aaabbbccc',-4,6) FROM DUAL;

SUBS
----
bccc

-- orafce 3.18

postgres=# SELECT SUBSTRB('aaabbbccc',-4,1) FROM DUAL;
 substrb
---------

(1 row)

postgres=# SELECT SUBSTRB('aaabbbccc',-4,2) FROM DUAL;
 substrb
---------

(1 row)

postgres=# SELECT SUBSTRB('aaabbbccc',-4,3) FROM DUAL;
 substrb
---------

(1 row)

postgres=# SELECT SUBSTRB('aaabbbccc',-4,6) FROM DUAL;
 substrb
---------
 a
(1 row)

`

**Comment by okbob** [comment]
The `substrb` call is forward to call PostgreSQL `bytea_substr` function. These functions doesn't support negative arguments.  I'll try to fix it.

**Comment by okbob** [comment]
It should be fixed in master branch - see last commit 7206c10f817b4a0ed71946b90f4f655e7c437968

**Comment by zyl6628156** [comment]
thanks
