### ISSUE TITLE
NVL2

### ISSUE THREAD

**Issue by zyl6628156** [orafce/orafce#173]
drop table tt;
create table tt (col1 int,col3 int);
insert into tt values (1001,1000),(1002,2000),(2002,null),(3001,3000);

-- oracle
SQL> SELECT col1, NVL2(col3,'IS NOT NULL','IS NULL') FROM tt;

      COL1 NVL2(COL3,'
---------- -----------
      1001 IS NOT NULL
      1002 IS NOT NULL
      2002 IS NULL
      3001 IS NOT NULL

-- orafce number is ok
postgres=# SELECT col1, NVL2(col3,0,1) FROM tt;
 col1 | nvl2
------+------
 1001 |    0
 1002 |    0
 2002 |    1
 3001 |    0
(4 rows)

-- orafce char not ok
postgres=# SELECT col1, NVL2(col3,'IS NOT NULL','IS NULL') FROM tt;
ERROR:  invalid input syntax for type integer: "IS NOT NULL"
LINE 1: SELECT col1, NVL2(col3,'IS NOT NULL','IS NULL') FROM tt;
                               ^

**Comment by okbob** [comment]
I modified signature of nvl2 function. Now it is more close to Oracle. Unfortunately, it can break extension update due function signature change 3bb56174c9e0df11aea43ecf16326450351ec752

**Comment by zyl6628156** [comment]
Thanks, my test environment, no effect.
