### ISSUE TITLE
Error：File“PG_HOME/orafce.dll” “orafce_regexp_instr_no_start”function does not exist.

### ISSUE THREAD

**Issue by salix2022** [orafce/orafce#176]
Hello,

I am install the Orafce.dll in the PostgreSQL on Windows OS. I used "create extension orafce"  command to extend orafce. But an error occurred. The function of “orafce_regexp_instr_no_start” does not exist in the file of “PG_HOME/orafce.dll” 
Use the command of "dumpbin /exports orafce.dll" to find the function of "orafce_regexp_instr_no_start". But it isn't found in the orafce.dll file.
regexp.c file can be compiled correctlly. I don't know why there is no corresponding function in the DLL file.

**Comment by okbob** [comment]
Hi

so 23. 4. 2022 v 15:48 odesílatel salix2022 ***@***.***>
napsal:

> Hello,
>
> I am install the Orafce.dll in the PostgreSQL on Windows OS. I used
> "create extension orafce" command to extend orafce. But an error occurred.
> The function of “orafce_regexp_instr_no_start” does not exist in the file
> of “PG_HOME/orafce.dll”
> Use the command of "dumpbin /exports orafce.dll" to find the function of
> "orafce_regexp_instr_no_start". But it isn't found in the orafce.dll file.
> regexp.c file can be compiled correctlly. I don't know why there is no
> corresponding function in the DLL file.
>

do you have fresh build of orafce.dll?

**Comment by salix2022** [comment]
yes, I rebuild the solution of Orafce.2010. fresh ⇒ rebuild?

**Comment by salix2022** [comment]
Hello,

A part of orafce.dll's functions is listed. The functions related to PostgreSQL 15 don't be generated. 
     97   60 00012670 oracle_substrb3
         98   61 00018720 orafce_bpcharlen
         99   62 00019480 orafce_concat2
        100   63 00007490 orafce_dbtimezone
        101   64 0000B350 orafce_dump
        102   65 00001190 orafce_listagg1_transfn
        103   66 00001250 orafce_listagg2_transfn
        104   67 00001260 orafce_listagg_finalfn
        105   68 00018800 orafce_lpad
        106   69 000013F0 orafce_median4_finalfn
        107   6A 00001270 orafce_median4_transfn
        108   6B 00001610 orafce_median8_finalfn
        109   6C 00001490 orafce_median8_transfn
        110   6D 000142A0 orafce_replace_empty_strings
        111   6E 000145E0 orafce_replace_null_strings
        112   6F 00018BC0 orafce_rpad
        113   70 00007470 orafce_sessiontimezone
        114   71 00007420 orafce_sysdate
        115   72 000043C0 orafce_to_char_float4
        116   73 00004430 orafce_to_char_float8
        117   74 00004340 orafce_to_char_int4
        118   75 00004380 orafce_to_char_int8
        119   76 000044A0 orafce_to_char_numeric
        120   77 00004570 orafce_to_char_timestamp
        121   78 00004700 orafce_to_multi_byte
        122   79 000045F0 orafce_to_number
        123   7A 00004840 orafce_to_single_byte
        124   7B 00004C20 orafce_unistr
        125   7C 00019360 orafce_varchar_transform
        126   7D 000011F0 orafce_wm_concat_transfn
        127   7E 00005400 pg_finfo_add_months

**Comment by okbob** [comment]
so 23. 4. 2022 v 16:02 odesílatel salix2022 ***@***.***>
napsal:

> yes, I rebuild the solution of Orafce.2010. fresh ⇒ rebuild?
>

you need to attach new file regexp.c to solution

**Comment by salix2022** [comment]
> so 23. 4. 2022 v 16:02 odesílatel salix2022 ***@***.***> napsal:
> yes, I rebuild the solution of Orafce.2010. fresh ⇒ rebuild?
> you need to attach new file regexp.c to solution —
Thank you for your reply. Yes, I have added regexp.c file to solution'src folder, and then recompile the project. 
The same result was added with the latest version of regexp.c(Master version) .
The development environment is as follows：
  VS 2022
  postgresql-14.2-2-windows-x64-binaries
  icu4c-71_1-Win64-MSVC2019
  orafce-VERSION_3_21_0

On the console of vs2002，I see that the regexp.c file is compiled normally correctly. 
And regexp.obj file is generated in the path of "orafce-VERSION_3_21_0/msvc/obj/x64/10.3/orafce".
It's strange why it's not compiled into a orafce.dll file?

**Comment by salix2022** [comment]
Thank you for your reply. 
Yes, I have added regexp.c file to solution'src folder, and then recompile the project.
The same result was added with the latest version of regexp.c(Master version) .
The development environment is as follows：
VS 2022
postgresql-14.2-2-windows-x64-binaries
icu4c-71_1-Win64-MSVC2019
orafce-VERSION_3_21_0

On the console of vs2002，I see that the regexp.c file is compiled normally correctly.
And regexp.obj file is generated in the path of "orafce-VERSION_3_21_0/msvc/obj/x64/10.3/orafce".
It's strange why it's not compiled into a orafce.dll file?

> so 23. 4. 2022 v 16:02 odesílatel salix2022 ***@***.***> napsal:
> yes, I rebuild the solution of Orafce.2010. fresh ⇒ rebuild?
> you need to attach new file regexp.c to solution —

Thank you for your reply. Yes, I have added regexp.c file to solution'src folder, and then recompile the project.
The same result was added with the latest version of regexp.c(Master version) .
The development environment is as follows：
VS 2022
postgresql-14.2-2-windows-x64-binaries
icu4c-71_1-Win64-MSVC2019
orafce-VERSION_3_21_0

On the console of vs2002，I see that the regexp.c file is compiled normally correctly.
And regexp.obj file is generated in the path of "orafce-VERSION_3_21_0/msvc/obj/x64/10.3/orafce".
It's strange why it's not compiled into a orafce.dll file?

**Comment by salix2022** [comment]
> so 23. 4. 2022 v 16:02 odesílatel salix2022 ***@***.***> napsal:
> yes, I rebuild the solution of Orafce.2010. fresh ⇒ rebuild?
> you need to attach new file regexp.c to solution —

Thank you for your reply. Yes, I have added regexp.c file to solution'src folder, and then recompile the project.
The same result was added with the latest version of regexp.c(Master version) .
The development environment is as follows：
VS 2022
postgresql-14.2-2-windows-x64-binaries
icu4c-71_1-Win64-MSVC2019
orafce-VERSION_3_21_0

On the console of vs2002，I see that the regexp.c file is compiled normally correctly.
And regexp.obj file is generated in the path of "orafce-VERSION_3_21_0/msvc/obj/x64/10.3/orafce".
It's strange why it's not compiled into a orafce.dll file?

**Comment by salix2022** [comment]
I tried again. If the following SQL code is commented out, orafce can be extended to Postgres. Regexp_Instr related functions are not used in my projects, so even if commented out, no problem.But I still hope to find out the reason.Functions may be used in the future。

--  REGEXP_INSTR( string text, pattern text ) -> integer
CREATE OR REPLACE FUNCTION oracle.regexp_instr(text, text)
RETURNS integer
AS 'MODULE_PATHNAME','orafce_regexp_instr_no_start'
LANGUAGE 'c' IMMUTABLE;

--  REGEXP_INSTR( string text, pattern text, position int ) -> integer
CREATE OR REPLACE FUNCTION oracle.regexp_instr(text, text, integer)
RETURNS integer
AS 'MODULE_PATHNAME','orafce_regexp_instr_no_n'
LANGUAGE 'c' IMMUTABLE;

--  REGEXP_INSTR( string text, pattern text, position int, occurence int ) -> integer
CREATE OR REPLACE FUNCTION oracle.regexp_instr(text, text, integer, integer)
RETURNS integer
AS 'MODULE_PATHNAME','orafce_regexp_instr_no_endoption'
LANGUAGE 'c' IMMUTABLE;

--  REGEXP_INSTR( string text, pattern text, position int, occurence int, return_opt int ) -> integer
CREATE OR REPLACE FUNCTION oracle.regexp_instr(text, text, integer, integer, integer)
RETURNS integer
AS 'MODULE_PATHNAME','orafce_regexp_instr_no_flags'
LANGUAGE 'c' IMMUTABLE;

--  REGEXP_INSTR( string text, pattern text, position int, occurence int, return_opt int, flags text ) -> integer
CREATE OR REPLACE FUNCTION oracle.regexp_instr(text, text, integer, integer, integer, text)
RETURNS integer
AS 'MODULE_PATHNAME','orafce_regexp_instr_no_subexpr'
LANGUAGE 'c' IMMUTABLE;

--  REGEXP_INSTR( string text, pattern text, position int, occurence int, return_opt int, flags text, group int ) -> integer
CREATE OR REPLACE FUNCTION oracle.regexp_instr(text, text, integer, integer, integer, text, integer)
RETURNS integer
AS 'MODULE_PATHNAME','orafce_regexp_instr'
LANGUAGE 'c' IMMUTABLE;

**Comment by okbob** [comment]
ne 24. 4. 2022 v 0:45 odesílatel salix2022 ***@***.***>
napsal:

> so 23. 4. 2022 v 16:02 odesílatel salix2022 *@*.***> napsal:
> yes, I rebuild the solution of Orafce.2010. fresh ⇒ rebuild?
> you need to attach new file regexp.c to solution —
>
> Thank you for your reply. Yes, I have added regexp.c file to solution'src
> folder, and then recompile the project.
> The same result was added with the latest version of regexp.c(Master
> version) .
> The development environment is as follows：
> VS 2022
> postgresql-14.2-2-windows-x64-binaries
> icu4c-71_1-Win64-MSVC2019
> orafce-VERSION_3_21_0
>
> On the console of vs2002，I see that the regexp.c file is compiled normally
> correctly.
> And regexp.obj file is generated in the path of
> "orafce-VERSION_3_21_0/msvc/obj/x64/10.3/orafce".
> It's strange why it's not compiled into a orafce.dll file?
>
It can be compiled but maybe not linked.

**Comment by okbob** [comment]
ne 24. 4. 2022 v 8:22 odesílatel Pavel Stehule ***@***.***>
napsal:

>
>
> ne 24. 4. 2022 v 0:45 odesílatel salix2022 ***@***.***>
> napsal:
>
>> so 23. 4. 2022 v 16:02 odesílatel salix2022 *@*.***> napsal:
>> yes, I rebuild the solution of Orafce.2010. fresh ⇒ rebuild?
>> you need to attach new file regexp.c to solution —
>>
>> Thank you for your reply. Yes, I have added regexp.c file to solution'src
>> folder, and then recompile the project.
>> The same result was added with the latest version of regexp.c(Master
>> version) .
>> The development environment is as follows：
>> VS 2022
>> postgresql-14.2-2-windows-x64-binaries
>> icu4c-71_1-Win64-MSVC2019
>> orafce-VERSION_3_21_0
>>
>> On the console of vs2002，I see that the regexp.c file is compiled
>> normally correctly.
>> And regexp.obj file is generated in the path of
>> "orafce-VERSION_3_21_0/msvc/obj/x64/10.3/orafce".
>> It's strange why it's not compiled into a orafce.dll file?
>>
> It can be compiled but maybe not linked.
>

The function orafce_regexp_instr_no_start is correctly marked as
PGDLLEXPORT in builtins.h so it looks like an issue somewhere in the
solution file. Unfortunately, I have not MS Window environment and I have
very minimalistic and obsolete knowledge of msvs

**Comment by salix2022** [comment]
Hi Pavel Stehule，

I found the reason. In the regexp.c file is missing include command. So don't  export to orafce.dll.

regexp.c
#include "builtins.h"

(replace_empty_string.c  Line 14  is including builtins.h)

orafce.dll
        108   6B 000016D0 orafce_median8_finalfn
        109   6C 000015A0 orafce_median8_transfn
        110   6D 000198C0 orafce_regexp_instr
        111   6E 00019B60 orafce_regexp_instr_no_endoption
        112   6F 00019B60 orafce_regexp_instr_no_flags
        113   70 00019B60 orafce_regexp_instr_no_n
        114   71 00019B60 orafce_regexp_instr_no_start
        115   72 00019B60 orafce_regexp_instr_no_subexpr
        116   73 000134C0 orafce_replace_empty_strings
        117   74 00013810 orafce_replace_null_strings
        118   75 00017F90 orafce_rpad
        119   76 00007090 orafce_sessiontimezone
        120   77 00007040 orafce_sysdate
        121   78 00019C20 orafce_textregexreplace
        122   79 00019E30 orafce_textregexreplace_extended
        123   7A 0001A070 orafce_textregexreplace_extended_no_flags

I find orafce_regexp_instr functions. The Error Problem is solved.
Thank you very much!

**Comment by okbob** [comment]
it was orafce bug.

I fixed this.

Thank you for report

Pavel

ne 24. 4. 2022 v 14:15 odesílatel salix2022 ***@***.***>
napsal:
