### ISSUE TITLE
some of the build time generated files are not present in .gitignore and also checked into the repository

### ISSUE THREAD

**Issue by ashucoek** [orafce/orafce#178]
Hi,

The below files in orafce contrib module are generated at build time.
However, these are checked into the repository. Shouldn't these files
be removed from the repository and added to the .gitignore file so
that they get ignored in the future commits.

sqlparse.c
sqlscan.c
sqlparse.h

thoughts?

--
Regards,
Ashutosh Sharma.

**Comment by okbob** [comment]
These files are stored for simplification build for MS where lexer and parser compiler should not be available.
