### ISSUE TITLE
small bug in plvdate_isleapyear(), plvdate.c:883

### ISSUE THREAD

**Issue by liu5192** [orafce/orafce#184]
Hello, i find a small bug in plvdate_isleapyear(), plvdate.c:883.

`result = ((( y % 4) == 0) && ((y % 100) != 0)) || ((y / 400) == 0);`

Leap year calculations should be "year % 400", not "year / 400".

**Comment by okbob** [comment]
should be fixed in orafce 3.23.0

Thank you for bug report
