### ISSUE TITLE
nlssort test fails on Windows, FreeBSD and macOS

### ISSUE THREAD

**Issue by shinderuk** [orafce/orafce#185]
In sql/nlssort.sql:
```
CREATE TABLE test_sort (name TEXT);
INSERT INTO test_sort VALUES ('red'), ('brown'), ('yellow'), ('Purple');
SELECT * FROM test_sort ORDER BY NLSSORT(name, 'en_US.utf8');
```

The problem is "en_US.utf8" doesn't work everywhere. On Windows Server 2016 it doesn't work at all, setlocale returns NULL. On Windows Server 2019 version 1809 it doesn't work either, but in a subtler way. setlocale accepts it, but then strxfrm returns EILSEQ. On Windows 11 it works.

FreeBSD and macOS don't support "en_US.utf8", only "en_US.UTF-8". Also, macOS gives a different order, where "Purple" comes before "brown".

It seems there is no such locale (apart from C) that is supported everywhere and gives consistent ordering across different platforms. Maybe this test should limit itself to Linux/glibc, like the PostgreSQL test [collate.linux.utf8](https://github.com/postgres/postgres/blob/master/src/test/regress/sql/collate.linux.utf8.sql) does?

What do you think?

**Comment by okbob** [comment]
pá 5. 8. 2022 v 14:49 odesílatel Sergey Shinderuk ***@***.***>
napsal:

> In sql/nlssort.sql:
>
> CREATE TABLE test_sort (name TEXT);
> INSERT INTO test_sort VALUES ('red'), ('brown'), ('yellow'), ('Purple');
> SELECT * FROM test_sort ORDER BY NLSSORT(name, 'en_US.utf8');
>
> The problem is "en_US.utf8" doesn't work everywhere. On Windows Server
> 2016 it doesn't work at all, setlocale returns NULL. On Windows Server 2019
> version 1809 it doesn't work either, but in a subtler way. setlocale
> accepts it, but then strxfrm returns EILSEQ. On Windows 11 it works.
>
> FreeBSD and macOS don't support "en_US.utf8", only "en_US.UTF-8". Also,
> macOS gives a different order, where "Purple" comes before "brown".
>
> It seems there is no such locale (apart from C) that is supported
> everywhere and gives consistent ordering across different platforms. Maybe
> this test should limit itself to Linux/glibc, like the PostgreSQL test
> collate.linux.utf8
> <https://github.com/postgres/postgres/blob/master/src/test/regress/sql/collate.linux.utf8.sql>
> does?
>
> What do you think?
>
has sense, please send PR
