### ISSUE TITLE
Error on update from less and equal  than 3.22 version to upper version

### ISSUE THREAD

**Issue by shab2** [orafce/orafce#189]
Hi.
Here log how I updated extention. Postgres 13.1

[postgres@pcft]# alter extension orafce update to '3.16';
ALTER EXTENSION
PCFT@db-dev-70:5458
[postgres@pcft]# alter extension orafce update to '3.19';
ALTER EXTENSION
PCFT@db-dev-70:5458
[postgres@pcft]# alter extension orafce update to '3.21';
ALTER EXTENSION
PCFT@db-dev-70:5458
[postgres@pcft]# alter extension orafce update to '3.22';
ALTER EXTENSION
PCFT@db-dev-70:5458
[postgres@pcft]# alter extension orafce update to '3.23';
ERROR:  function oracle.mod(smallint, smallint) does not exist
CONTEXT:  SQL statement "ALTER FUNCTION oracle.mod(SMALLINT, SMALLINT) PARALLEL SAFE"
PL/pgSQL function inline_code_block line 4 at SQL statement
PCFT@db-dev-70:5458
[postgres@pcft]# select * from pg_extension where extname='orafce';
   oid   | extname | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition
---------+---------+----------+--------------+----------------+------------+-----------+--------------
 4254377 | orafce  |       10 |         2200 | f              | 3.22       |           |
(1 row)

PCFT@db-dev-70:5458
[postgres@pcft]# select * from pg_available_extension_versions() where name='orafce';
  name  | version | superuser | trusted | relocatable | schema | requires |                                            comment
--------+---------+-----------+---------+-------------+--------+----------+-----------------------------------------------------------------------------------------------
 orafce | 3.15    | t         | f       | f           |        |          | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS
 orafce | 3.19    | t         | f       | f           |        |          | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS
 orafce | 3.20    | t         | f       | f           |        |          | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS
 orafce | 3.17    | t         | f       | f           |        |          | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS
 orafce | 3.18    | t         | f       | f           |        |          | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS
 orafce | 3.16    | t         | f       | f           |        |          | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS
 orafce | 3.21    | t         | f       | f           |        |          | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS
 orafce | 3.22    | t         | f       | f           |        |          | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS
 orafce | 3.23    | t         | f       | f           |        |          | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS
 orafce | 3.24    | t         | f       | f           |        |          | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS
(10 rows)

PCFT@db-dev-70:5458
[postgres@pcft]#

**Comment by okbob** [comment]
Please, try 3.24.2 release

**Comment by okbob** [comment]
Hi


st 17. 8. 2022 v 16:08 odesílatel Alexander Shaburov <
***@***.***> napsal:

> Hi.
> Here log how I updated extention. Postgres 13.1
>
> ***@***.***# alter extension orafce update to '3.16';
> ALTER EXTENSION
> ***@***.***:5458
> ***@***.***# alter extension orafce update to '3.19';
> ALTER EXTENSION
> ***@***.***:5458
> ***@***.***# alter extension orafce update to '3.21';
> ALTER EXTENSION
> ***@***.***:5458
> ***@***.***# alter extension orafce update to '3.22';
> ALTER EXTENSION
> ***@***.***:5458
> ***@***.***# alter extension orafce update to '3.23';
> ERROR: function oracle.mod(smallint, smallint) does not exist
> CONTEXT: SQL statement "ALTER FUNCTION oracle.mod(SMALLINT, SMALLINT)
> PARALLEL SAFE"
> PL/pgSQL function inline_code_block line 4 at SQL statement
> ***@***.***:5458
> ***@***.***# select * from pg_extension where extname='orafce';
> oid | extname | extowner | extnamespace | extrelocatable | extversion |
> extconfig | extcondition
>
> ---------+---------+----------+--------------+----------------+------------+-----------+--------------
> 4254377 | orafce | 10 | 2200 | f | 3.22 | |
> (1 row)
>
> ***@***.***:5458
> ***@***.***# select * from pg_available_extension_versions() where
> name='orafce';
> name | version | superuser | trusted | relocatable | schema | requires |
> comment
>
> --------+---------+-----------+---------+-------------+--------+----------+-----------------------------------------------------------------------------------------------
> orafce | 3.15 | t | f | f | | | Functions and operators that emulate a
> subset of functions and packages from the Oracle RDBMS
> orafce | 3.19 | t | f | f | | | Functions and operators that emulate a
> subset of functions and packages from the Oracle RDBMS
> orafce | 3.20 | t | f | f | | | Functions and operators that emulate a
> subset of functions and packages from the Oracle RDBMS
> orafce | 3.17 | t | f | f | | | Functions and operators that emulate a
> subset of functions and packages from the Oracle RDBMS
> orafce | 3.18 | t | f | f | | | Functions and operators that emulate a
> subset of functions and packages from the Oracle RDBMS
> orafce | 3.16 | t | f | f | | | Functions and operators that emulate a
> subset of functions and packages from the Oracle RDBMS
> orafce | 3.21 | t | f | f | | | Functions and operators that emulate a
> subset of functions and packages from the Oracle RDBMS
> orafce | 3.22 | t | f | f | | | Functions and operators that emulate a
> subset of functions and packages from the Oracle RDBMS
> orafce | 3.23 | t | f | f | | | Functions and operators that emulate a
> subset of functions and packages from the Oracle RDBMS
> orafce | 3.24 | t | f | f | | | Functions and operators that emulate a
> subset of functions and packages from the Oracle RDBMS
> (10 rows)
>
> ***@***.***:5458
> ***@***.***#
>
Unfortunately, there is a bug in the update script from between 3.21 and
3.22 :-(, but it can be fixed in update script 3.22-3.23.

please try fresh release 3.24.2

Regards

Pavel

**Comment by shab2** [comment]
Hi!
update passed. OK
I see only 3.24 version as available. I suggest I should to see 3.23 or low vesions before 3,24 for case. Isnt it?

PCFT@db-dev-70:5458
[postgres@pcft]# select * from pg_available_extension_versions() where name='orafce';
  name  | version | superuser | trusted | relocatable | schema | requires |                                            comment
--------+---------+-----------+---------+-------------+--------+----------+-----------------------------------------------------------------------------------------------
 orafce | 3.24    | t         | f       | f           |        |          | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS
(1 row)

PCFT@db-dev-70:5458
[postgres@pcft]# select * from pg_extension where extname='orafce';
   oid   | extname | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition
---------+---------+----------+--------------+----------------+------------+-----------+--------------
 4255196 | orafce  |       10 |         2200 | f              | 3.22       |           |
(1 row)

PCFT@db-dev-70:5458
[postgres@pcft]# alter extension orafce update;
ALTER EXTENSION

**Comment by shab2** [comment]
Why I dont see ever minor release number 3.24.(2) . Where can I see it?

**Comment by okbob** [comment]
st 17. 8. 2022 v 17:30 odesílatel Alexander Shaburov <
***@***.***> napsal:

> Why I dont see ever minor release number 3.24.(2) . Where can I see it?
>
this number is not available from SQL. This is something like build number

It can be visible if there will be some function like oracle.version(), but
there is nothing similar

**Comment by okbob** [comment]
st 17. 8. 2022 v 17:28 odesílatel Alexander Shaburov <
***@***.***> napsal:

> Hi!
> update passed. OK
> I see only 3.24 version as available. I suggest I should to see 3.23 or
> low vesions before 3,24 for case. Isnt it?
>
Usually not - the library is compiled for 3.24, and then you cannot to use
version lower than 3.24 - the orafce.so is not versioned (like any others
extensions), so for C extensions can be dangerous to use a different
version of extension than is build of library.
