### ISSUE TITLE
Upgrade error again

### ISSUE THREAD

**Issue by danielgustafsson** [orafce/orafce#191]
Looks like I spoke too soon in #190, the upgrade from 3.21 to 3.24.3 does work in Postgres 11 but now it fails in Postgres 14:
```
db=# alter extension orafce update;
ERROR:  function pg_catalog.listagg1_transfn(internal, text) does not exist
CONTEXT:  SQL statement "ALTER FUNCTION pg_catalog.listagg1_transfn(internal,text) SET SCHEMA oracle"
PL/pgSQL function inline_code_block line 46 at SQL statement
```
It looks like the upgrade file changes brought in new function definitions?

**Comment by okbob** [comment]
so 20. 8. 2022 v 23:41 odesílatel Daniel Gustafsson <
***@***.***> napsal:

> Looks like I spoke too soon in #190
> <https://github.com/orafce/orafce/issues/190>, the upgrade from 3.21 to
> 3.24.3 does work in Postgres 11 but now it fails in Postgres 14:
>
> db=# alter extension orafce update;
> ERROR:  function pg_catalog.listagg1_transfn(internal, text) does not exist
> CONTEXT:  SQL statement "ALTER FUNCTION pg_catalog.listagg1_transfn(internal,text) SET SCHEMA oracle"
> PL/pgSQL function inline_code_block line 46 at SQL statement
>
> It looks like the upgrade file changes brought in new function definitions?
>
yes, copy/paste error :-(

should be fixed now - in 3.24.4

please check

Pavel
