### ISSUE TITLE
operator is not unique: date = varchar2

### ISSUE THREAD

**Issue by junfx** [orafce/orafce#192]
```
postgres=# select '1234-1-1'::date = '1234-1-1'::varchar2;
ERROR:  operator is not unique: date = varchar2
LINE 1: select '1234-1-1'::date = '1234-1-1'::varchar2;
                                ^
HINT:  Could not choose a best candidate operator. You might need to add explicit type casts.
```
By invesgating the code and testing, I guess following CASTs in orafce-3.24.sql produce the confusion.
```sql
CREATE CAST (varchar2 AS date)
WITH INOUT
AS IMPLICIT;

CREATE CAST (date AS varchar2)
WITH INOUT
AS IMPLICIT;

CREATE CAST (varchar2 AS timestamp)
WITH INOUT
AS IMPLICIT;

CREATE CAST (timestamp AS varchar2)
WITH INOUT
AS IMPLICIT;
```

Deleting one cast pair (date, or timestamp), ERROR disappears.

**Comment by okbob** [comment]
Unfortunatelly, this is feature - is not possible to reduce these casts - and unfortunately isn't possible to fix this issue in an extension. You should to fix your query on application side like:
   
    select '1234-1-1'::date = '1234-1-1'::varchar2::date;

or 

    select '1234-1-1'::date::varchar2 = '1234-1-1'::varchar2;

**Comment by okbob** [comment]
st 7. 9. 2022 v 11:05 odesílatel junfx ***@***.***> napsal:

> postgres=# select '1234-1-1'::date = '1234-1-1'::varchar2;
> ERROR:  operator is not unique: date = varchar2
> LINE 1: select '1234-1-1'::date = '1234-1-1'::varchar2;
>                                 ^
> HINT:  Could not choose a best candidate operator. You might need to add explicit type casts.
>
> By invesgating the code and testing, I guess following CASTs in
> orafce-3.24.sql make the confusions.
>
> CREATE CAST (varchar2 AS date)
> WITH INOUTAS IMPLICIT;
>
> CREATE CAST (date AS varchar2)
> WITH INOUTAS IMPLICIT;
>
> CREATE CAST (varchar2 AS timestamp)
> WITH INOUTAS IMPLICIT;
>
> CREATE CAST (timestamp AS varchar2)
> WITH INOUTAS IMPLICIT;
>
> Deleting one cast pair (date, or timestamp), ERROR disappears.
>
Unfortunately, this is a feature - due limits of PostgreSQL type system.
Removing some casts is not good solution, because you will fix one problem
and you create a second.

I cannot fix it :-(. It should be fixed in application code. You should to
write

select '1234-1-1'::date = '1234-1-1'::varchar2::date;
