### ISSUE TITLE
Incompatibility with PostgreSQL v11

### ISSUE THREAD

**Issue by sergeydeg** [orafce/orafce#194]
Cannot install extension on PostgreSQL v11 because call to sinh and cosh doesn't contain schema name. 
IMHO starting from v12 this extension can work wrong also, because this line references to default PostgreSQL hyperbolic functions implementation, as they are added in v12.

https://github.com/orafce/orafce/blob/98bde64fec595ebb3e1e9143a19b873667176d8b/orafce--3.24.sql#L208

Also from previous version, trying to install got syntax error

```
CREATE EXTENSION orafce;
ERROR:  syntax error at or near "SUPPORT"
LINE 4: ...TER FUNCTION varchar2(varchar2, integer, boolean) SUPPORT va...
                                                             ^
QUERY:
BEGIN
  IF EXISTS(SELECT * FROM pg_settings WHERE name = 'server_version_num' AND setting::int >= 120000) THEN
    ALTER FUNCTION varchar2(varchar2, integer, boolean) SUPPORT varchar2_transform;
  ELSE
    UPDATE pg_proc SET protransform= 'varchar2_transform'::regproc::oid WHERE proname='varchar2';

    INSERT INTO pg_depend (classid, objid, objsubid,
                           refclassid, refobjid, refobjsubid, deptype)
       VALUES('pg_proc'::regclass::oid, 'varchar2'::regproc::oid, 0,
              'pg_proc'::regclass::oid, 'varchar2_transform'::regproc::oid, 0, 'n');
  END IF;
END
```

**Comment by okbob** [comment]
what is your search_path setting? I install orafce on pg 11 without any problems.

**Comment by sergeydeg** [comment]
Hi Pavel, I use default sarch_path ` "$user", public` and trying to install from precompiled extension from Postgres RPM repo orafce_11-3.24.4-1.rhel7.x86_64.
I see you just patched SQl in master branch with fully qualified function names.
But what about second error wih unrecognized SUPPORT verb in PSQL v11?

**Comment by sergeydeg** [comment]
name        | setting |
--------------------+---------+
 server_version_num | 110005  |

Maybe it's triggered because PSQL do full statement syntax check before actual execution.

WBR,
Sergejs

**Comment by okbob** [comment]
po 12. 9. 2022 v 16:17 odesílatel Sergejs Degtjars ***@***.***>
napsal:

>     name        | setting |
>
> --------------------+---------+
> server_version_num | 110005 |
>
> Maybe it's triggered because PSQL do full statement syntax check before
> actual execution.
>
It does, but the INSIDE CREATE EXTENSION it is working little bit
differently

It is strange so it is working on my computer, and doesn't work on yours.

I wrapped all possible not supported DDL to dynamic SQL. Please, can you
check last commit?
