### ISSUE TITLE
Difference between oracle and orafce in timestamp to date conversion

### ISSUE THREAD

**Issue by AnatolyKap** [orafce/orafce#199]
In Oracle:
```
select cast((TIMESTAMP '2022-01-01 01:01:01.555') as date) from dual
```
returns 2022-01-01 01:01:01

In PostgreSQL with orafce: 
```
select ('01-01-2022 01:01:01.555'::timestamp)::oracle.date
```
returns 2022-01-01 01:01:02 <= !!!

**Comment by okbob** [comment]
Hi


út 25. 10. 2022 v 12:16 odesílatel AnatolyKap ***@***.***>
napsal:

> In Oracle:
>
> select cast((TIMESTAMP '2022-01-01 01:01:01.555') as date) from dual
>
> returns 2022-01-01 01:01:01
>
> In PostgreSQL with orafce:
>
> select ('01-01-2022 01:01:01.555'::timestamp)::oracle.date
>
> returns 2022-01-01 01:01:02 <= !!!
>
> In Oracle:
>
> select cast((TIMESTAMP '2022-01-01 01:01:01.555') as date) from dual
>
> returns 2022-01-01 01:01:01
>
> In PostgreSQL with orafce:
>
> select ('01-01-2022 01:01:01.555'::timestamp)::oracle.date
>
> returns 2022-01-01 01:01:02 <= !!!
>

Unfortunately, I cannot change this behavior. oracle.date type is domain of
PostgreSQL's timestamp(0) type. Oracle does trimming, PostgreSQL rounding,
but it is not possible to change it,

Regards

Pavel

**Comment by AnatolyKap** [comment]
Thank you for the prompt response
