### ISSUE TITLE
The contents of utl_file.utl_file_dir is not dumped with pg_dump

### ISSUE THREAD

**Issue by gleu** [orafce/orafce#205]
Hi,

One of our customers has an issue with orafce. The table utl_file.utl_file_dir is not declared as dumpable, and so pg_dump doesn't dump its content while dumping a database. Would it be possible to declare utl_file.utl_file_dir as dumpable by executing "SELECT pg_extension_config_dump('utl_file.utl_file_dir')" in the schema script of the extension?

Thanks a lot.

Regards.

**Comment by okbob** [comment]
please, can you check 33cea9cd5ef6f839d0fcd9336a6767733a515c6e ?

**Comment by gleu** [comment]
Sure, I've compiled orafce with your new commit, installed it, and updated the extension. Now pg_dump gets this table's content. Thanks of lot!

**Comment by okbob** [comment]
super, thank you for tip for enhancing

**Comment by gleu** [comment]
You're welcome.
