### ISSUE TITLE
Want to add sys_guid compatible

### ISSUE THREAD

**Issue by sun-hchao** [orafce/orafce#210]
`test=> set search_path to "$user", public,oracle;
SET
test=> select sys_guid() from dual;
错误:  函数 sys_guid() 不存在
第1行select sys_guid() from dual;
            ^
提示:  没有匹配指定名称和参数类型的函数. 您也许需要增加明确的类型转换.
test=> \dx
                                                       已安装扩展列表
  名称   | 版本 |  架构模式  |                                             描述
---------+------+------------+-----------------------------------------------------------------------------------------------
 orafce  | 4.1  | public     | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS
 plpgsql | 1.0  | pg_catalog | PL/pgSQL procedural language
(2 行记录)

test=>
`

**Comment by okbob** [comment]
please, can you check 8d3a9e3?

**Comment by sun-hchao** [comment]
I've seen it Thank you very much
