### ISSUE TITLE
Implicit Cast ´1234,5’ to numeric

### ISSUE THREAD

**Issue by legrandlegrand** [orafce/orafce#211]
Hello,
Migrating an oracle db using
Create table tt ( num numeric)
Alter session set nls_numeric_characters=‘, ‘;
Insert into tt values (‘1234,5’);

this fails with postgres, even after setting lc_numeric … you should tell us to use TO_NUMBER function … but this would ask us to rewrite a big part of the application.

Is there a way to make this work with postgres ? May by creating an implicit CAST that would replace the comma by a dot, before to convert to numeric ?

thanks in advance for your feedback.
Regards
PAscal

**Comment by okbob** [comment]
Hi


pá 24. 2. 2023 v 17:53 odesílatel legrandlegrand ***@***.***>
napsal:

> Hello,
> Migrating an oracle db using
> Create table tt ( num numeric)
> Alter session set nls_numeric_characters=‘, ‘;
> Insert into tt values (‘1234,5’);
>
> this fails with postgres, even after setting lc_numeric … you should tell
> us to use TO_NUMBER function … but this would ask us to rewrite a big part
> of thé application.
>
> Is there a way to mâle this World with postgres ? May by creating an
> implicit CAST that would replace the comma by a dot, bécote to convert to
> numeric ?
>
> thanks in advance for your feedback.
>
I recheck source codes, and type numeric uses dot as decimal point every
time. The type float (or double) used for parsing function strtod, that
should use locale, but (and it looks strange) although I have czech locale
with decimal point comma, it doesn't allow numbers with comma. In regress
tests, LC_NUMERIC is used just for testing the to_number function, so it
really looks so the comma is not supported as a decimal point. But it is
described

 *
 * The other categories, LC_MONETARY, LC_NUMERIC, and LC_TIME are also
 * settable at run-time.  However, we don't actually set those locale
 * categories permanently.  This would have bizarre effects like no
 * longer accepting standard floating-point literals in some locales.
 * Instead, we only set these locale categories briefly when needed,
 * cache the required information obtained from localeconv() or
 * strftime(), and then set the locale categories back to "C".
 * The cached information is only used by the formatting functions
 * (to_char, etc.) and the money type.  For the user, this should all be
 * transparent.


Implicit cast cannot help you. I think there is no way to fix it - just to
write your own type :-/

Regards

Pavel

**Comment by legrandlegrand** [comment]
Thanks for this answer.

I was dreaming about something like:

CREATE or replace FUNCTION tonum(varchar)
  RETURNS numeric
  STRICT IMMUTABLE LANGUAGE SQL AS
'SELECT cast(replace($1,'',''::char,''.''::char) as numeric);';

CREATE CAST (varchar AS numeric) WITH FUNCTION tonum(varchar) AS IMPLICIT;

CREATE TABLE tt (num numeric);
INSERT INTO tt VALUES ('123,4');
--> ERROR:  invalid input syntax for type numeric: "123,4" at character 24

INSERT INTO tt VALUES ('123,4'::varchar);
--> works

but it seems not possible to make it recognize '123,4' field as varchar.

Regards
PAscal

**Comment by okbob** [comment]
so 25. 2. 2023 v 11:24 odesílatel legrandlegrand ***@***.***>
napsal:

> Thanks for this answer.
>
> I was dreaming about something like:
>
> CREATE or replace FUNCTION tonum(varchar)
> RETURNS numeric
> STRICT IMMUTABLE LANGUAGE SQL AS
> 'SELECT cast(replace($1,'',''::char,''.''::char) as numeric);';
>
> CREATE CAST (varchar AS numeric) WITH FUNCTION tonum(varchar) AS IMPLICIT;
>
> CREATE TABLE tt (num numeric);
> INSERT INTO tt VALUES ('123,4');
> --> ERROR: invalid input syntax for type numeric: "123,4" at character 24
>
> INSERT INTO tt VALUES ('123,4'::varchar);
> --> works
>
> but it seems not possible to make it recognize '123,4' field as varchar.
>
It is not possible - because any string literal is "unknown" type - and
then Postgres uses "in" function

(2023-02-25 13:45:00) postgres=# select 'unknown'::regtype::oid;
┌─────┐
│ oid │
╞═════╡
│ 705 │
└─────┘
(1 row)

(2023-02-25 13:45:50) postgres=# CREATE or replace FUNCTION tonum(unknown)
RETURNS numeric
STRICT IMMUTABLE LANGUAGE SQL AS
'SELECT cast(replace($1,'',''::char,''.''::char) as numeric);';
ERROR:  SQL functions cannot have arguments of type unknown

Regards

Pavel

Regards

**Comment by legrandlegrand** [comment]
Arf
Thank you for that explanation
And for your time.

Regards
PAscal
