### ISSUE TITLE
orafce 4 and above: ERROR:  relation "dual" does not exist

### ISSUE THREAD

**Issue by PawelCzerwonka** [orafce/orafce#212]
Could you tell me what is wrong with orafce 4? Oracle command which should work on PostgreSQL 15 only work when I downgrade orafce from 4 to 3.18. It happens on my all servers. I did not find any Oracle command which works with orafce 4. Example:

[postgres@vm110 ~]$ psql -p5433
psql (15.2)
Type "help" for help.

postgres=# \dx
                                                  List of installed extensions
  Name   | Version |   Schema   |                                          Description
---------+---------+------------+-----------------------------------------------------------------------------------------------
 orafce  | 4.1     | public     | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS

postgres=# SELECT SINH(1.414) FROM DUAL;
ERROR:  relation "dual" does not exist
LINE 1: SELECT SINH(1.414) FROM DUAL;
                                ^
postgres=# \dx
                                                       List of installed extensions
        Name        | Version |   Schema   |                                          Description
--------------------+---------+------------+-----------------------------------------------------------------------------------------------
 orafce             | 3.18    | public     | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS

postgres=# SELECT SINH(1.414) FROM DUAL;
        sinh
--------------------
 1.9346016882495567
(1 row)

postgres=#

**Comment by okbob** [comment]
Hi

st 1. 3. 2023 v 9:36 odesílatel Pawel Czerwonka ***@***.***>
napsal:

> Could you tell me what is wrong with orafce 4? Oracle command which should
> work on PostgreSQL 15 only work when I downgrade orafce from 4 to 3.18. It
> happens on my all servers. I did not find any Oracle command which works
> with orafce 4. Example:
>
all orafce's objects was moved from public schema to oracle schema.

So you should to:

a) use qualified identifiers like oracle.dual

or b) set search_path to public, oracle, ..

set search_path to 'oracle, pg_catalog, "$user", public'

you can do it in postgresql.conf too

**Comment by PawelCzerwonka** [comment]
Now everything is clear. Thank you.

# I confirm, the following command solved the problem (without single quotation mark)
SET search_path to oracle,"$user",public;

**Comment by okbob** [comment]
st 1. 3. 2023 v 10:38 odesílatel Pawel Czerwonka ***@***.***>
napsal:

> Now everything is clear. Thank you.
> I confirm, the following command solved the problem (without single
> quotation mark)
>
> SET search_path to oracle,"$user",public;
>
:-)
