### ISSUE TITLE
CREATE EXTENSION orafce - error. Build from HEAD

### ISSUE THREAD

**Issue by sgrinko** [orafce/orafce#213]
Hi,

OS - CentOS 7.9
Postgres 15.2
build successfully - from head github

CREATE EXTENSION orafce;
```
CREATE EXTENSION ERROR:  could not load library "/usr/pgsql-15/lib/orafce.so": /usr/pgsql-15/lib/orafce.so: undefined symbol: get_extension_schema
```

**Comment by sgrinko** [comment]
Thank you!
Now everything is fine.
There are no errors.

**Comment by okbob** [comment]
čt 9. 3. 2023 v 9:46 odesílatel sergey grinko ***@***.***>
napsal:

> Thank you!
> Now everything is fine.
> There are no errors.
>

Thank you for report
