### ISSUE TITLE
How do I specify the character set of the file name

### ISSUE THREAD

**Issue by salix2022** [orafce/orafce#214]
Hello okbob
I use utl_file.fopen method of the util_file package opens the file. When the file does not exist, it will automatically create a file with the specified file name, but the file name is garbled. How can I make the automatically generated file name not garbled?
for example: 
file_pointer :=
	utl_file.fopen(
			'c:\test'
                        ,'エスカレーションkamsai'
			,'w'
			,32767
	);
OS encoding is SJIS. DB encoding is UTF8

file.c
line  271~273
#if NOT_USED
	fullname = convert_encoding_server_to_platform(fullname);
#endif

line 227~237
	if (PG_NARGS() > 4 && !PG_ARGISNULL(4))
	{
		const char *encname = NameStr(*PG_GETARG_NAME(4));
		encoding = pg_char_to_encoding(encname);
		if (encoding < 0)
			ereport(ERROR,
				(errcode(ERRCODE_INVALID_PARAMETER_VALUE),
				 errmsg("invalid encoding name \"%s\"", encname)));
	}
	else
		encoding = GetDatabaseEncoding();

It seems to be able to achieve multilingual changes, but I can't find that function of convert_encoding_server_to_platform.
How can I solve this problem?
Hope to get your reply

salix
best regard

**Comment by salix2022** [comment]
fmode_in = 'w' 
file_pointer :=
utl_file.fopen(
filepath
,'エスカレーションkamsai'
,'w'
,max_linesize
);

**Comment by okbob** [comment]
please, can you check 14638f4 commit?

**Comment by salix2022** [comment]
Hi,okbob

I used this version of code, but the specified Japanese file name was not created. An error was threw, then a new file with a garbled name was created.
Error: [The requested file could not be opened. It seems to be caused by OS permissions.]

Yesterday, I have tried other solutions and threw the same exception.
filename=encode_ text(PG_UTF8)

I feel that the file name has not been converted to SJIS character set.

**Comment by salix2022** [comment]
hi okbob
thank you very much!
the japanese name of file is opened.

salix

**Comment by salix2022** [comment]
report: I found a mistake in comments.
 
Line 201
 * charset. Conversion fro server encoding to wide strings
 
fro →　for is corrected.

**Comment by okbob** [comment]
should be fixed now
