### ISSUE TITLE
4.2.0 build error against PostgreSQL 15

### ISSUE THREAD

**Issue by devrimgunduz-edb** [orafce/orafce#215]
Hi,

4.2.0 fails to build against PostgreSQL 15. Can you please take a look? No problems against PostgreSQL v11 through v14.

Thanks! Devrim

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I. -I./ -I/usr/pgsql-15/include/server -I/usr/pgsql-15/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o plvsubst.o plvsubst.c
others.c: In function 'get_extension_schema':
others.c:77:9: error: unknown type name 'SysScanDesc'
   77 |         SysScanDesc scandesc;
      |         ^~~~~~~~~~~
others.c:83:15: warning: implicit declaration of function 'table_open' [-Wimplicit-function-declaration]
   83 |         rel = table_open(ExtensionRelationId, AccessShareLock);
      |               ^~~~~~~~~~
others.c:83:13: warning: assignment to 'Relation' {aka 'struct RelationData *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
   83 |         rel = table_open(ExtensionRelationId, AccessShareLock);
      |             ^
others.c:101:20: warning: implicit declaration of function 'systable_beginscan' [-Wimplicit-function-declaration]
  101 |         scandesc = systable_beginscan(rel, ExtensionOidIndexId, true,
      |                    ^~~~~~~~~~~~~~~~~~
others.c:104:17: warning: implicit declaration of function 'systable_getnext' [-Wimplicit-function-declaration]
  104 |         tuple = systable_getnext(scandesc);
      |                 ^~~~~~~~~~~~~~~~
others.c:104:15: warning: assignment to 'HeapTuple' {aka 'HeapTupleData *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
  104 |         tuple = systable_getnext(scandesc);
      |               ^
others.c:112:9: warning: implicit declaration of function 'systable_endscan' [-Wimplicit-function-declaration]
  112 |         systable_endscan(scandesc);
      |         ^~~~~~~~~~~~~~~~
others.c:116:9: warning: implicit declaration of function 'table_close' [-Wimplicit-function-declaration]
  116 |         table_close(rel, AccessShareLock);
      |         ^~~~~~~~~~~
make[1]: *** [<builtin>: others.o] Error 1
make[1]: *** Waiting for unfinished jobs....

**Comment by vbwagner** [comment]
As far as I can understand, it is just a typo:

Line 5 of others.c contains condition 


#if PG_VERSION_NUM <= 150000

and under this condition there are bunch of #include statements

Line 73 contain s condition 

#if PG_VERSION_NUM < 160000

And under this condition types from these include files are used.
These condintions shoudl match, and wrong one seems to be one in line 5

**Comment by vbwagner** [comment]
Here is the patch which I use to build rpm and deb packages of orafce 4.2.0 for postgres 15.2
```
--- orafce-4.2.0.orig/others.c
+++ orafce-4.2.0/others.c
@@ -2,7 +2,7 @@
 #include <stdlib.h>
 #include <locale.h>
 
-#if PG_VERSION_NUM <= 150000
+#if PG_VERSION_NUM < 160000
 
 #include "access/genam.h"
 #include "access/heapam.h"
```

**Comment by vbwagner** [comment]
I've rebuild 4.2.1 packages for couple of dozen linux distribution for postgres from 11 to 15, it builds ok.

**Comment by okbob** [comment]
> I've rebuild 4.2.1 packages for couple of dozen linux distribution for postgres from 11 to 15, it builds ok. For Window I've tested buidls only from 11 to 14.

Thank you for info
