### ISSUE TITLE
The filename of util_file.frename is garbled.

### ISSUE THREAD

**Issue by iceriver20002000** [orafce/orafce#217]
Hello okbob

I use the util_file.frename method to rename a file.
If rename to a english name,the filename is ok.
But, if rename to a japanese name,the filename is garbled.
For example:
utl_file.frename('c:\filepath', '111.csv' ,'c:\filepath', '経費.csv');
The result is 邨瑚ｲｻ.csv.

Windows encoding is SJIS.
PostgreSQL encoding is UTF-8.

**Comment by okbob** [comment]
please, can you check 25048ad2b0571bd1b7796ab9c961a09c91073917

**Comment by iceriver20002000** [comment]
> please, can you check [25048ad](https://github.com/orafce/orafce/commit/25048ad2b0571bd1b7796ab9c961a09c91073917)

excellent!
The problem has been solved.
Thank you so much.

**Comment by okbob** [comment]
čt 30. 3. 2023 v 3:16 odesílatel rabbit ***@***.***> napsal:

> Closed #217 <https://github.com/orafce/orafce/issues/217> as completed.
>

thank you for report
