### ISSUE TITLE
Infinite recursion due to non-static shmem_request_hook_type

### ISSUE THREAD

**Issue by DishonJordan** [orafce/orafce#218]
https://github.com/orafce/orafce/blob/27c1a3b774ec3d465489e3d7f955f5c4e1ceb9ec/orafce.c#L35

The above shmem_request_hook_type definition should be static. Without it, trying to load orafce and any other extension in shared_preload_libraries will cause infinite recursion and crash with the below stack when starting the postgres server. (Tested on postgres 15.1)

```
 (gdb) bt
 #0  0x00007f2d45471d10 in orafce_shmem_request () at orafce.c:43
 #1  0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
 #2  0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
 #3  0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
 #4  0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
 #5  0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
 #6  0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
 #7  0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
 #8  0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
 #9  0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
 #10 0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
 #11 0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
 ... 
```

**Comment by okbob** [comment]
Hi


so 1. 4. 2023 v 8:49 odesílatel Dishon Jordan ***@***.***>
napsal:

>
> https://github.com/orafce/orafce/blob/27c1a3b774ec3d465489e3d7f955f5c4e1ceb9ec/orafce.c#L35
>
> The above shmem_request_hook_type definition should be static. Without it,
> trying to load orafce and any other extension in shared_preload_libraries
> will cause infinite recursion and crash with the below stack when starting
> the postgres server. (Tested on postgres 15.1)
>
>  (gdb) bt
>  #0  0x00007f2d45471d10 in orafce_shmem_request () at orafce.c:43
>  #1  0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
>  #2  0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
>  #3  0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
>  #4  0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
>  #5  0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
>  #6  0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
>  #7  0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
>  #8  0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
>  #9  0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
>  #10 0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
>  #11 0x00007f2d45471d12 in orafce_shmem_request () at orafce.c:43
>  ...
>
>
should be fixed by fda7dceeee3aa87d93ed478ad6e881be578ffda3

Regards

Pavel

**Comment by DishonJordan** [comment]
Looks good, thank you!

**Comment by okbob** [comment]
Thank you for report
