### ISSUE TITLE
utl_file.frename not working on  Windows OS with overwrite flag 

### ISSUE THREAD

**Issue by kav23alex** [orafce/orafce#219]
I found a test failure on Windows OS. Here's reproduction:
SELECT utl_file.frename(utl_file.tmpdir(), 'regress_orafce2.txt', utl_file.tmpdir(), 'regress_orafce.txt', true);
+ERROR:  UTL_FILE_INVALID_OPERATION

[In the test above we tried to rename file 'regress_orafce2.txt' to 'regress_orafce.txt' that already exists. _wrename() and rename() can't overwrite old file when trying to change new file's name]

In documentation here - https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/rename-wrename?view=msvc-170 - it says:
 _The new name must not be the name of an existing file or directory_

I tried to make a fix, with the attached patch the test files pass and utl_file.frename works correctly

[file.c.patch](https://github.com/orafce/orafce/files/11183477/file.c.patch)

**Comment by okbob** [comment]
so 8. 4. 2023 v 11:51 odesílatel kav23alex ***@***.***>
napsal:

> I found a test failure on Windows OS. Here's reproduction:
> SELECT utl_file.frename(utl_file.tmpdir(), 'regress_orafce2.txt',
> utl_file.tmpdir(), 'regress_orafce.txt', true);
> +ERROR: UTL_FILE_INVALID_OPERATION
>
> [In the test above we tried to rename file 'regress_orafce2.txt' to
> 'regress_orafce.txt' that already exists. _wrename() and rename() can't
> overwrite old file when trying to change new file's name]
>
> In documentation here -
> https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/rename-wrename?view=msvc-170
> - it says:
> *The new name must not be the name of an existing file or directory*
>
> I tried to make a fix, with the attached patch the test files pass and
> utl_file.frename works correctly
>
> file.c.patch
> <https://github.com/orafce/orafce/files/11182858/file.c.patch>
>

please, check  08cd09dc4f26964d0a01fb17fc1e846f069cbdb4

**Comment by okbob** [comment]
po 10. 4. 2023 v 5:38 odesílatel kav23alex ***@***.***>
napsal:

> Closed #219 <https://github.com/orafce/orafce/issues/219> as completed.
>

Thank you for enhancing and check
