### ISSUE TITLE
oracle.instr function is not fully comatible with Oracle's counterpart

### ISSUE THREAD

**Issue by portnov** [orafce/orafce#221]
Oracle: `select instr('ab;cd', ';', 0) from dual` returns 0.
PG: `select instr('ab;cd', ';', 0)` returns 3.

It seems this has something to do with difference between "less or equals" and "less". Oracle documentation:
https://docs.oracle.com/cd/B13789_01/server.101/b10759/functions058.htm
states
> position is an nonzero integer indicating the character of string where Oracle Database begins the search. If position is negative, then Oracle counts and searches backward from the end of string.

It seems that in orafce behaviour changes for values of third parameter equal to zero or less than zero. While in Oracle it is for negative values only.

**Comment by okbob** [comment]
should be fixed by 58eb58c9045c016f71d9ba8e6b46ba356ba1a130

**Comment by okbob** [comment]
čt 20. 4. 2023 v 9:53 odesílatel Ilya V. Portnov ***@***.***>
napsal:

> Thank you for fast reply and fix!
>
> Do you have some plans when the release will be available with this fix
> included?
>

This doesn't look like a critical bug, so I can wait until the end of April
- if it is ok?

**Comment by portnov** [comment]
I think it is okay, thanks.

**Comment by okbob** [comment]
fixed in released 4.2.6

**Comment by portnov** [comment]
Thanks! I think this issue can be closed then.

**Comment by okbob** [comment]
po 1. 5. 2023 v 8:17 odesílatel Ilya V. Portnov ***@***.***>
napsal:

> Thanks! I think this issue can be closed then.
>

sure

thank you for bug report

Pavel
