### ISSUE TITLE
dbms_random should not be immutable

### ISSUE THREAD

**Issue by FranckPachot** [orafce/orafce#222]
When calling dbms_random multiple times in a query, the same value is returned:
```
yugabyte=# create extension orafce;
CREATE EXTENSION
yugabyte=# select dbms_random.string('X',4), random() from generate_series(1,5);
 string |       random
--------+--------------------
 LCK5   | 0.0651973173953593
 LCK5   |  0.389594652689993
 LCK5   |  0.730435273144394
 LCK5   |  0.279673664364964
 LCK5   | 0.0491841086186469
(5 rows)
```
This is because the function is declared immutable. With volatile, each row has a random value:
```
yugabyte=# alter function dbms_random.string volatile;
ALTER FUNCTION
yugabyte=# select dbms_random.string('X',4), random() from generate_series(1,5);
 string |      random
--------+-------------------
 EHEP   | 0.811485387850553
 B4MS   | 0.237645495682955
 ZKWY   | 0.170328844804317
 X9V4   | 0.145491427741945
 1KRD   |  0.12441247748211
(5 rows)
```
This is the right behavor to be compatible with Oracle:
```
DEMO@o21c_tp> select dbms_random.string ('X',5) from xmltable('1 to 5');

DBMS_RANDOM.STRING('X',5)
____________________________
5GAV3
NT1KD
CMDQE
PJA9C
VVMM6
```
It is also closer to the `random()` behavior

**Comment by okbob** [comment]
Hi


st 3. 5. 2023 v 21:10 odesílatel Franck Pachot (YB) <
***@***.***> napsal:

> When calling dbms_random multiple times in a query, the same value is
> returned:
>
> yugabyte=# create extension orafce;
> CREATE EXTENSION
> yugabyte=# select dbms_random.string('X',4), random() from generate_series(1,5);
>  string |       random
> --------+--------------------
>  LCK5   | 0.0651973173953593
>  LCK5   |  0.389594652689993
>  LCK5   |  0.730435273144394
>  LCK5   |  0.279673664364964
>  LCK5   | 0.0491841086186469
> (5 rows)
>
> This is because the function is declared immutable. With volatile, each
> row has a random value:
>
> yugabyte=# alter function dbms_random.string volatile;
> ALTER FUNCTION
> yugabyte=# select dbms_random.string('X',4), random() from generate_series(1,5);
>  string |      random
> --------+-------------------
>  EHEP   | 0.811485387850553
>  B4MS   | 0.237645495682955
>  ZKWY   | 0.170328844804317
>  X9V4   | 0.145491427741945
>  1KRD   |  0.12441247748211
> (5 rows)
>
> This is the right behavor to be compatible with Oracle:
>
> ***@***.***_tp> select dbms_random.string ('X',5) from xmltable('1 to 5');
>
> DBMS_RANDOM.STRING('X',5)
> ____________________________
> 5GAV3
> NT1KD
> CMDQE
> PJA9C
> VVMM6
>
> It is also closer to the random() behavior
>
should be fixed by 06ee5d2fe6c8a2c142932c98a474c2480c390e25
