### ISSUE TITLE
dbms_random.string('P') misses 2 characters

### ISSUE THREAD

**Issue by FranckPachot** [orafce/orafce#223]
The `P` option of `dbms_random.string()` doesn't return `\` and `~` which are returned by the Oracle one.
Not sure it matters a lot, but probably better to do the same.

Checking the ASCII 32 to 127 that are never returned
```
yugabyte=# select a, chr(a) from generate_series(32,127) a 
                     where a not in ( 
                              --  with the volatile version of the function
                             select distinct ascii(dbms_random.string('P',1)) p from generate_series(1,1000000)
                     );
  a  | chr
-----+------
  92 | \
 126 | ~
 127 | \x7F
(3 rows)
```
This is defined in https://github.com/orafce/orafce/blob/master/random.c#L205

In Oracle the equivalent shows that only `chr(127)` is not in the returned set.

This is confirmed by the ORACLE_HOME/rdbms/admin/dbmsrand.sql:
```
        ELSIF optx = 'p' THEN    -- any printable char (ASCII subset)                                                                                                 
            ccs := ' !"#$%&''()*+,-./' || '0123456789' || ':;<=>?@' ||
                  'ABCDEFGHIJKLMNOPQRSTUVWXYZ' || '[\]^_`' ||
                  'abcdefghijklmnopqrstuvwxyz' || '{|}~' ;
            rng := 95;
        ELSE
```

**Comment by okbob** [comment]
should be fixed by 1a0d3366928e4b990a069fb7b4e4966ab694569f

**Comment by FranckPachot** [comment]
Great, thanks

**Comment by okbob** [comment]
Thank you for report


pá 5. 5. 2023 v 8:41 odesílatel Franck Pachot (YB) ***@***.***>
napsal:
