### ISSUE TITLE
how to update the extension if an old update script file changed

### ISSUE THREAD

**Issue by winter-loo** [orafce/orafce#224]
In this commit of orafce `7b9d494b64905d6ca99875fcf819a3c572b200ff`, an old update script file `orafce--3.10--3.11.sql` is changed. How could I update orafce extension if my current orafce extension is 3.17.

**Comment by okbob** [comment]
čt 6. 7. 2023 v 9:59 odesílatel winter-loo ***@***.***>
napsal:

> In this commit of orafce 7b9d494b64905d6ca99875fcf819a3c572b200ff, an old
> update script file orafce--3.10--3.11.sql is changed. How could I update
> orafce extension if my current orafce extension is 3.17.
>

just run necessary changes manually

ALTER FUNCTION utl_file.fopen(text, text, text, integer, name) SECURITY
INVOKER;
ALTER FUNCTION utl_file.fopen(text, text, text, integer) SECURITY INVOKER;
GRANT SELECT ON TABLE utl_file.utl_file_dir TO PUBLIC;
GRANT EXECUTE ON FUNCTION utl_file.tmpdir() TO PUBLIC;
