### ISSUE TITLE
dbms_random output variation on big-endian s390x

### ISSUE THREAD

**Issue by df7cb** [orafce/orafce#226]
Hi,

on Debian's s390x architecture, I'm seeing this output variation in the regression tests:

```
diff -U3 /<<PKGBUILDDIR>>/expected/dbms_random_1.out /<<PKGBUILDDIR>>/results/dbms_random.out
--- /<<PKGBUILDDIR>>/expected/dbms_random_1.out 2023-08-05 03:51:43.000000000 +0000
+++ /<<PKGBUILDDIR>>/results/dbms_random.out    2023-08-07 09:23:27.150277693 +0000
@@ -44,7 +44,7 @@
 SELECT dbms_random.string('P',2);
 string
 --------
- R`
+ T`
 (1 row)

 SELECT dbms_random.string('x',4);
```

I don't know if srand+rand() are supposed to be reproducible across little+big endian systems, but given everything else in that file matches, it looks like it is. That leaves the question why this single character comes out differently - perhaps the floating point math in `random_string` is at fault.

In the Debian package, I'm going to paper over this by adding yet another `expected/dbms_random_3.out` file, but a proper fix would be appreciated.

**Comment by okbob** [comment]
I have not any idea what can be wrong - I try to reformulate an expression. Please, can you check the patch
```
diff --git a/random.c b/random.c
index 89a4ff5..395561e 100644
--- a/random.c
+++ b/random.c
@@ -182,7 +182,7 @@ random_string(const char *charset, size_t chrset_size, int len)
    str = makeStringInfo();
    for (i = 0; i < len; i++)
    {
-       int pos = (int) ((double) rand() / ((double) RAND_MAX + 1) * chrset_size);
+       int pos = (int) floor(((double) rand() / ((double) RAND_MAX + 1)) * chrset_size);
        
        appendStringInfoChar(str, charset[pos]);
    }
```

**Comment by df7cb** [comment]
Good idea, but unfortunately no change. Attaching floor() to the outer expression makes no difference either:
```
int pos = (int) floor((double) rand() / ((double) RAND_MAX + 1) * chrset_size);
```

**Comment by okbob** [comment]
po 7. 8. 2023 v 20:50 odesílatel Christoph Berg ***@***.***>
napsal:

> Good idea, but unfortunately no change. Attaching floor() to the outer
> expression makes no difference either:
>
> int pos = (int) floor((double) rand() / ((double) RAND_MAX + 1) * chrset_size);
>
>
Can you print the values in the expression ? Can be interesting to see
which part of the expression is different.  Maybe the rand() function
returns a slightly different value. I am not mathematician, and I have no
idea which form of this expression can reduce a calculating error. There
are other possibilities like  (r * chs) / (rm + 1).
