### ISSUE TITLE
Fail test dbms_random on windows after commit 1a0d336

### ISSUE THREAD

**Issue by kav23alex** [orafce/orafce#227]
on windows, I'm seeing this output variation in the regression tests:

```
SELECT dbms_random.string('P',2);
  string 
 --------
- fo
+ go
```

I think the problem is after commit 1a0d336
Length variable printable has changed and return another result
```int pos = (int) ((double) rand() / ((double) RAND_MAX + 1) * chrset_size);```

output in debugger 
value pos from printable length = 96
value pos from printable length = 95

![2023-08-10_13-31-10](https://github.com/orafce/orafce/assets/3829359/c181b97a-bd15-4332-9b54-0c6e33cdb812)

I think you need to change the alternative output in dbms_random_2.out

**Comment by okbob** [comment]
Hi

should be fixed by 891fa4e99fad1e46403340f7890e9fb45c35a949

čt 10. 8. 2023 v 8:50 odesílatel kav23alex ***@***.***>
napsal:
