### ISSUE TITLE
Regression test for to_char(string) failed?

### ISSUE THREAD

**Issue by japinli** [orafce/orafce#241]
Hi,

When I try to use orafce, and there is an error about `to_char(string)`.
Here is the regression test output:

```
diff -U3 /home/japin/Codes/orafce/expected/orafce.out /home/japin/Codes/orafce/results/orafce.out
--- /home/japin/Codes/orafce/expected/orafce.out        2023-11-15 11:39:34.563618685 +0800
+++ /home/japin/Codes/orafce/results/orafce.out 2023-11-15 11:46:37.076579245 +0800
@@ -2439,59 +2439,50 @@
 (1 row)

 select to_char('-44444');
- to_char
----------
- -44444
-(1 row)
-
+ERROR:  function to_char(unknown) is not unique
+LINE 1: select to_char('-44444');
+               ^
+HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
 select to_char('1234567890123456');
-     to_char
-------------------
- 1234567890123456
-(1 row)
-
+ERROR:  function to_char(unknown) is not unique
+LINE 1: select to_char('1234567890123456');
+               ^
+HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
 select to_char('123.456');
- to_char
----------
- 123.456
-(1 row)
-
+ERROR:  function to_char(unknown) is not unique
+LINE 1: select to_char('123.456');
+               ^
+HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
 select to_char('123abc');
- to_char
----------
- 123abc
-(1 row)
-
+ERROR:  function to_char(unknown) is not unique
+LINE 1: select to_char('123abc');
+               ^
+HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
 select to_char('你好123@$%abc');
-    to_char
----------------
- 你好123@$%abc
-(1 row)
-
+ERROR:  function to_char(unknown) is not unique
+LINE 1: select to_char('你好123@$%abc');
+               ^
+HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
 select to_char('1234567890123456789012345678901234567890123456789012345678901234567890');
-                                to_char
-------------------------------------------------------------------------
- 1234567890123456789012345678901234567890123456789012345678901234567890
-(1 row)
-
+ERROR:  function to_char(unknown) is not unique
+LINE 1: select to_char('12345678901234567890123456789012345678901234...
+               ^
+HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
 select to_char('');
- to_char
----------
-
-(1 row)
-
+ERROR:  function to_char(unknown) is not unique
+LINE 1: select to_char('');
+               ^
+HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
 select to_char(' ');
- to_char
----------
-
-(1 row)
-
+ERROR:  function to_char(unknown) is not unique
+LINE 1: select to_char(' ');
+               ^
+HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
 select to_char(null);
- to_char
----------
-
-(1 row)
-
+ERROR:  function to_char(unknown) is not unique
+LINE 1: select to_char(null);
+               ^
+HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
 SELECT to_number('123'::text);
  to_number
 -----------
```

Both PG 14 and 15 has the same errors.

**Comment by okbob** [comment]
st 15. 11. 2023 v 5:00 odesílatel Japin Li ***@***.***>
napsal:

> Hi,
>
> When I try to use orafce, and there is an error about to_char(string).
> Here is the regression test output:
>
> diff -U3 /home/japin/Codes/orafce/expected/orafce.out /home/japin/Codes/orafce/results/orafce.out
> --- /home/japin/Codes/orafce/expected/orafce.out        2023-11-15 11:39:34.563618685 +0800
> +++ /home/japin/Codes/orafce/results/orafce.out 2023-11-15 11:46:37.076579245 +0800
> @@ -2439,59 +2439,50 @@
>  (1 row)
>
>  select to_char('-44444');
> - to_char
> ----------
> - -44444
> -(1 row)
> -
> +ERROR:  function to_char(unknown) is not unique
> +LINE 1: select to_char('-44444');
> +               ^
> +HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
>  select to_char('1234567890123456');
> -     to_char
> -------------------
> - 1234567890123456
> -(1 row)
> -
> +ERROR:  function to_char(unknown) is not unique
> +LINE 1: select to_char('1234567890123456');
> +               ^
> +HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
>  select to_char('123.456');
> - to_char
> ----------
> - 123.456
> -(1 row)
> -
> +ERROR:  function to_char(unknown) is not unique
> +LINE 1: select to_char('123.456');
> +               ^
> +HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
>  select to_char('123abc');
> - to_char
> ----------
> - 123abc
> -(1 row)
> -
> +ERROR:  function to_char(unknown) is not unique
> +LINE 1: select to_char('123abc');
> +               ^
> +HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
>  select to_char('你好123@$%abc');
> -    to_char
> ----------------
> - 你好123@$%abc
> -(1 row)
> -
> +ERROR:  function to_char(unknown) is not unique
> +LINE 1: select to_char('你好123@$%abc');
> +               ^
> +HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
>  select to_char('1234567890123456789012345678901234567890123456789012345678901234567890');
> -                                to_char
> -------------------------------------------------------------------------
> - 1234567890123456789012345678901234567890123456789012345678901234567890
> -(1 row)
> -
> +ERROR:  function to_char(unknown) is not unique
> +LINE 1: select to_char('12345678901234567890123456789012345678901234...
> +               ^
> +HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
>  select to_char('');
> - to_char
> ----------
> -
> -(1 row)
> -
> +ERROR:  function to_char(unknown) is not unique
> +LINE 1: select to_char('');
> +               ^
> +HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
>  select to_char(' ');
> - to_char
> ----------
> -
> -(1 row)
> -
> +ERROR:  function to_char(unknown) is not unique
> +LINE 1: select to_char(' ');
> +               ^
> +HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
>  select to_char(null);
> - to_char
> ----------
> -
> -(1 row)
> -
> +ERROR:  function to_char(unknown) is not unique
> +LINE 1: select to_char(null);
> +               ^
> +HINT:  Could not choose a best candidate function. You might need to add explicit type casts.
>  SELECT to_number('123'::text);
>   to_number
>  -----------
>
> Both PG 14 and 15 has the same errors.
>

master branch is broken now - it is known issue - use released version
https://github.com/orafce/orafce/releases

**Comment by japinli** [comment]
@okbob Thank you! Got it. Is there a plan to fix this? It seems you have give the solutions in https://github.com/orafce/orafce/pull/236.

**Comment by okbob** [comment]
it should be fixed now
