### ISSUE TITLE
Unable to drop extension orafce

### ISSUE THREAD

**Issue by brunre01** [orafce/orafce#245]
I'm performing an upgrade from postgres 11 to postgres 16 however the upgrade fails with the following error.

**pg_restore: from TOC entry 3641; 1255 256445868 FUNCTION nvarchar2_transform("internal") npp
pg_restore: error: could not execute query: ERROR:  there is no built-in function named "varchar_transform"
Command was: CREATE FUNCTION "public"."nvarchar2_transform"("internal") RETURNS "internal"
    LANGUAGE "internal" IMMUTABLE STRICT
    AS $$varchar_transform$$;**

-- For binary upgrade, handle extension membership the hard way
ALTER EXTENSION "orafce" ADD FUNCTION "public"."nvarchar2_transform"("internal");

The function was created by the orafce extension.

When i try to remove the function i get the message that I need to drop extension orafce

**DBNAME=# drop function public.nvarchar2_transform;
ERROR:  cannot drop function nvarchar2_transform(internal) because extension orafce requires it
HINT:  You can drop extension orafce instead.**

When trying to drop orafce i get error.

**DBNAME=# drop extension orafce cascade;
ERROR:  cache lookup failed for type 256445494
DBNAME=#**

Any assistance/ ideas on how to resolve would be appreciated.

**Comment by okbob** [comment]
po 27. 11. 2023 v 19:08 odesílatel brunre01 ***@***.***>
napsal:

> I'm performing an upgrade from postgres 11 to postgres 16 however the
> upgrade fails with the following error.
>
>
>
>
>
> *pg_restore: from TOC entry 3641; 1255 256445868 FUNCTION
> nvarchar2_transform("internal") npp pg_restore: error: could not execute
> query: ERROR: there is no built-in function named "varchar_transform"
> Command was: CREATE FUNCTION "public"."nvarchar2_transform"("internal")
> RETURNS "internal" LANGUAGE "internal" IMMUTABLE STRICT AS
> $$varchar_transform$$;*
>
> -- For binary upgrade, handle extension membership the hard way
> ALTER EXTENSION "orafce" ADD FUNCTION
> "public"."nvarchar2_transform"("internal");
>
> The function was created by the orafce extension.
>
> When i try to remove the function i get the message that I need to drop
> extension orafce
>
>
>
> *DBNAME=# drop function public.nvarchar2_transform; ERROR: cannot drop
> function nvarchar2_transform(internal) because extension orafce requires it
> HINT: You can drop extension orafce instead.*
>
> When trying to drop orafce i get error.
>
>
>
> *DBNAME=# drop extension orafce cascade; ERROR: cache lookup failed for
> type 256445494 DBNAME=#*
>
> Any assistance/ ideas on how to resolve would be appreciated.
>

Please, try to upgrade to some modern version of orafce before upgrading.
If it is possible, don't mix upgrade PostgreSQL and upgrade orafce in one
step.
