### ISSUE TITLE
Consider supporting DEFAULT XX ON CONVERSION ERROR syntax?

### ISSUE THREAD

**Issue by Xue0325** [orafce/orafce#250]
In Oracle，in some TO_* conversion functions, an error handling function has been added, which allows a default value to be returned if a record is converted incorrectly：
```
SQL> SELECT TO_TIMESTAMP ('10-Sept-02 14:10:10.123000'DEFAULT NULL ON CONVERSION ERROR,'DD-Mon-RR HH24:MI:SS.FF') "Value" FROM DUAL;

Value
---------------------------------------------------------------------------


```

So is it possible to support this syntax?

**Comment by okbob** [comment]
Hi

st 20. 12. 2023 v 2:27 odesílatel Jocker ***@***.***> napsal:

> In Oracle，in some TO_* conversion functions, an error handling function
> has been added, which allows a default value to be returned if a record is
> converted incorrectly：
>
> SQL> SELECT TO_TIMESTAMP ('10-Sept-02 14:10:10.123000'DEFAULT NULL ON CONVERSION ERROR,'DD-Mon-RR HH24:MI:SS.FF') "Value" FROM DUAL;
>
> Value
> ---------------------------------------------------------------------------
>
>
>  So is it possible to support this syntax?
>
Unfortunately not. Orafce cannot support syntax that is not supported by
PostgreSQL parser, because it is not possible to extend SQL parser.

Regards

Pavel

**Comment by Xue0325** [comment]
Okay, I understand now. Thank you for your response.
