### ISSUE TITLE
dbms_random.string Enhancement

### ISSUE THREAD

**Issue by Leo-XM-Zeng** [orafce/orafce#252]
Hello, I think the "dbms_random.string" function could be improved a bit more
```plpgsql
SELECT dbms_random.string('uu', 10) FROM dual;  -- should error
SELECT dbms_random.string('w', 10) FROM dual;   -- SELECT dbms_random.string('u', 10) FROM dual;
``` 
Postgresql:
<img width="509" alt="b2c35a9287eea5ebc0feb4b6767c676" src="https://github.com/orafce/orafce/assets/69310610/6c5fa387-abe8-4ec4-8b75-18eb84c982f0">

Oracle:
<img width="404" alt="f208b5112e06d62e4787cd361f78e7b" src="https://github.com/orafce/orafce/assets/69310610/49f75810-50b4-4cfc-8b91-7b9263316fc3">

**Comment by okbob** [comment]
I merged your pull request. Thank you for you
