### ISSUE TITLE
Unable to compile orafce 3.15.0 or 3.18.1 on both PostgreSQL 11 and 16.2

### ISSUE THREAD

**Issue by pedro375** [orafce/orafce#259]
Unable to compile orafce 3.15.0 or 3.18.1 on both PostgreSQL 11 and 16.2
The error is always:

**make USE_PGXS=1**
/contrib/contrib-global.mk:4: /src/makefiles/pgxs.mk: No such file or directory
make: ***  No rules to generate the target "/src/makefiles/pgxs.mk".  Stop.

**Installed packages:**
postgresql11-contrib, postgresql16-contrib, postgresql11-devel and postgresql16-devel  are installed,

**Orafce in;**
/tmp/orafce-VERSION_3_15_0
/tmp/orafce-VERSION_3_18_1

**pgxs.mk:**
/usr/pgsql-11/lib/pgxs/src/makefiles/pgxs.mk
/usr/pgsql-16/lib/pgxs/src/makefiles/pgxs.mk

Whats going wrong?

**Comment by okbob** [comment]
pá 8. 3. 2024 v 18:04 odesílatel Paolo Pedrelli ***@***.***>
napsal:

> Unable to compile orafce 3.15.0 or 3.18.1 on both PostgreSQL 11 and 16.2
> The error is always:
>
> *make USE_PGXS=1*
> /contrib/contrib-global.mk:4: /src/makefiles/pgxs.mk: No such file or
> directory
> make: *** No rules to generate the target "/src/makefiles/pgxs.mk". Stop.
>
> *Installed packages:*
> postgresql11-contrib, postgresql16-contrib, postgresql11-devel and
> postgresql16-devel are installed,
>
> *Orafce in;*
> /tmp/orafce-VERSION_3_15_0
> /tmp/orafce-VERSION_3_18_1
>
> *pgxs.mk <http://pgxs.mk>:*
> /usr/pgsql-11/lib/pgxs/src/makefiles/pgxs.mk
> /usr/pgsql-16/lib/pgxs/src/makefiles/pgxs.mk
>
> Whats going wrong?
>

maybe you have wrong path to pg_config

when you run pg_config --version, what do you get?

***@***.***:~/src/pspg-master$ /usr/local/pgsql/12/bin/pg_config --version
PostgreSQL 12.18

before make, there should be PATH set correctly, and pg_config should be
used for correct version

**Comment by pedro375** [comment]
pg_config is reacheable

[root@erpdbt orafce-VERSION_3_15_0]# which pg_config
/usr/pgsql-11/bin/pg_config

there is something else wrong. The error is the same:

 *make USE_PGXS=1*
 /contrib/contrib-global.mk:4: /src/makefiles/pgxs.mk: No such file or
 directory
 make: *** No rules to generate the target "/src/makefiles/pgxs.mk". Stop.

**Comment by okbob** [comment]
so 9. 3. 2024 v 20:54 odesílatel Paolo Pedrelli ***@***.***>
napsal:

> pg_config is reacheable
>
> ***@***.*** orafce-VERSION_3_15_0]# which pg_config
> /usr/pgsql-11/bin/pg_config
>
> there is something else wrong. The error is the same:
>
> *make USE_PGXS=1*
> /contrib/contrib-global.mk:4: /src/makefiles/pgxs.mk: No such file or
> directory
>

I have these files in directory  /usr/local/pgsql/12/lib/pgxs/src/pgxs/src

Maybe there are some system environments with set prefix (in my case
/usr/local/pgsql/12) to some other directory.

Try to check your system variables


make: *** No rules to generate the target "/src/makefiles/pgxs.mk". Stop.

**Comment by okbob** [comment]
@pedro375 any progress?

**Comment by pedro375** [comment]
No. We cloned the production VM (that is ok) to the test one to have a
quick solution. But we have to solve it. I will work about it as soon as
possible. Thanks.

Il giorno gio 21 mar 2024 alle ore 06:49 Pavel Stehule <
***@***.***> ha scritto:

**Comment by zscAZA** [comment]
You can solve this problem by executing the "sudo yum install postgresql-devel" command
