### ISSUE TITLE
UTL_FILE File Protection

### ISSUE THREAD

**Issue by nikodemusP** [orafce/orafce#261]
Postgres sets the default umask to 0077, only log-files are modified to 0022

```
[root@sgalcgms14 /]# grep '^Umask:' "/proc/449330/status"
Umask:  0077
```

This results, that created files are only set to
```
-rw------- 1 postgres postgres 14 Apr 10 07:46 hallo.txt
```

so no one can access the file, except the "postgres" user. Is there a possibility that the umask is set to a postgres-configured parameter or as it is for log-file 0022.

**Comment by okbob** [comment]
Hi

st 10. 4. 2024 v 10:27 odesílatel nikodemus.p ***@***.***>
napsal:

> Postgres sets the default umask to 0077, only log-files are modified to
> 0022
>
> ***@***.*** /]# grep '^Umask:' "/proc/449330/status"
> Umask:  0077
>
> This results, that created files are only set to
>
> -rw------- 1 postgres postgres 14 Apr 10 07:46 hallo.txt
>
> so no one can access the file, except the "postgres" user. Is there a
> possibility that the umask is set to a postgres-configured parameter or as
> it is for log-file 0022.
>

In this case, I am not sure, what is correct solution - I read Oracle's
documentation

On UNIX systems, a file created by the FOPEN function has as its owner the
owner of the shadow process running the instance. In the normal case, this
owner is *oracle*. Files created using FOPEN are always writable and
readable using the UTL_FILE subprograms, but non-privileged users who need
to read these files outside of PL/SQL might need their system administrator
to give them access.

Now, I have no strong opinion about this problem, but I am afraid about
possible security issues.

**Comment by okbob** [comment]
st 10. 4. 2024 v 21:40 odesílatel Pavel Stehule ***@***.***>
napsal:

> Hi
>
> st 10. 4. 2024 v 10:27 odesílatel nikodemus.p ***@***.***>
> napsal:
>
>> Postgres sets the default umask to 0077, only log-files are modified to
>> 0022
>>
>> ***@***.*** /]# grep '^Umask:' "/proc/449330/status"
>> Umask:  0077
>>
>> This results, that created files are only set to
>>
>> -rw------- 1 postgres postgres 14 Apr 10 07:46 hallo.txt
>>
>> so no one can access the file, except the "postgres" user. Is there a
>> possibility that the umask is set to a postgres-configured parameter or as
>> it is for log-file 0022.
>>
>
> In this case, I am not sure, what is correct solution - I read Oracle's
> documentation
>
> On UNIX systems, a file created by the FOPEN function has as its owner
> the owner of the shadow process running the instance. In the normal case,
> this owner is *oracle*. Files created using FOPEN are always writable and
> readable using the UTL_FILE subprograms, but non-privileged users who
> need to read these files outside of PL/SQL might need their system
> administrator to give them access.
>
> Now, I have no strong opinion about this problem, but I am afraid about
> possible security issues.
>

I implemented GUC variable orafce.umask

do $$
declare
  f utl_file.file_type;
begin
  set orafce.umask to '002';
  f := utl_file.fopen('/tmp', 'samplex.txt', 'w');
  perform utl_file.put_line(f, 'ahoj');
  perform utl_file.fclose_all();
end;
$$;

This variable can be set only by user with rights of role orafce_set_umask

please check ae9d0302be607f86bdfecbf24e962678e6282e75

**Comment by okbob** [comment]
supported by 4.10.0
