### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by zscAZA** [orafce/orafce#262]
when I use command "make" oe "make install",It reminds me of an error that 'MAX_MULTIBYTE_CHAR_LEN' is not declared in the convert.c file

**Comment by KonstantinL** [comment]
I've encountered the same issue as described. I noticed that the issue has been closed as completed. Could you please share how the issue was solved?

**Comment by okbob** [comment]
MAX_MULTIBYTE_CHAR_LEN is defined in postgres's header file pg_wchar.h 

if you missing this header file, then, probably, you miss postgres devel environment (package)
