### ISSUE TITLE
Oracle procdures are implemented as functions

### ISSUE THREAD

**Issue by glr72** [orafce/orafce#263]
Some functions (i.e. dbms_output.put_line) must be procedures. This will simplify the porting between the two RDBMS.

**Comment by okbob** [comment]
Hi

pá 3. 5. 2024 v 15:52 odesílatel glr72 ***@***.***> napsal:

> Some functions (i.e. dbms_output.put_line) must be procedures. This will
> simplify the porting between the two RDBMS.
>
It was implemented years ago (15 years) , when Postgres had no procedures.
Now, it is not possible to change it due to a compatibility break.
