### ISSUE TITLE
Regression tests for dbms_random failed on Illumos

### ISSUE THREAD

**Issue by japinli** [orafce/orafce#264]
Hi,

When attempting to use orafce with PostgreSQL 16.3 on Illumos, there were some failed regression tests for dbms_random.

```diff
[japin@db_build ~/extensions/orafce]$ cat regression.diffs
diff -U3 /home/japin/extensions/orafce/expected/dbms_random_2.out /home/japin/extensions/orafce/results/dbms_random.out
--- /home/japin/extensions/orafce/expected/dbms_random_2.out    2024-05-13 06:21:39.162760522 +0000
+++ /home/japin/extensions/orafce/results/dbms_random.out       2024-05-13 06:33:11.011606724 +0000
@@ -8,13 +8,13 @@
 SELECT dbms_random.normal()::numeric(10, 8);
    normal
 -------------
- -2.88076095
+ -1.22160768
 (1 row)

 SELECT dbms_random.normal()::numeric(10, 8);
    normal
 ------------
- 1.07890275
+ 0.91471634
 (1 row)

 SELECT dbms_random.seed(8);
@@ -26,7 +26,7 @@
 SELECT dbms_random.random();
  random
 --------
- -32638
+ -25498
 (1 row)

 SELECT dbms_random.seed('test');
@@ -38,31 +38,31 @@
 SELECT dbms_random.string('U',5);
  string
 --------
- XXEJF
+ VPQID
 (1 row)

 SELECT dbms_random.string('P',2);
  string
 --------
- go
+ *c
 (1 row)

 SELECT dbms_random.string('x',4);
  string
 --------
- V3W9
+ QY4P
 (1 row)

 SELECT dbms_random.string('a',2);
  string
 --------
- GC
+ gK
 (1 row)

 SELECT dbms_random.string('l',3);
  string
 --------
- pbr
+ dyl
 (1 row)

 SELECT dbms_random.seed(5);
@@ -74,13 +74,13 @@
 SELECT dbms_random.value()::numeric(10, 8);
    value
 ------------
- 0.00164795
+ 0.56930542
 (1 row)

 SELECT dbms_random.value(10,15)::numeric(10, 8);
     value
 -------------
- 14.37820435
+ 11.29043579
 (1 row)

 SELECT dbms_random.terminate();
@@ -92,31 +92,31 @@
 SELECT dbms_random.string('u', 10);
    string
 ------------
- JTVYSOVZEW
+ IZIUOSZPXQ
 (1 row)

 SELECT dbms_random.string('l', 10);
    string
 ------------
- knadjpjaji
+ sqinwaztpt
 (1 row)

 SELECT dbms_random.string('a', 10);
    string
 ------------
- XSPLgEQeBm
+ qKQoQidmEl
 (1 row)

 SELECT dbms_random.string('x', 10);
    string
 ------------
- 5H7G1H2ERS
+ 6ZTOV69J73
 (1 row)

 SELECT dbms_random.string('p', 10);
    string
 ------------
- km:uKzx??E
+ `f# tQP~r*
 (1 row)

 SELECT dbms_random.string('uu', 10); -- error
@@ -124,6 +124,6 @@
 SELECT dbms_random.string('w', 10);
    string
 ------------
- MJCOVPXTET
+ GIDLUOCSZH
 (1 row)

```

Here are my environments:

```bash
[japin@db_build ~/extensions/orafce]$ gcc --version
gcc (GCC) 10.4.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[japin@db_build ~/extensions/orafce]$ uname -a
SunOS db_build 5.11 hunghu-20231216T132436Z i86pc i386 i86pc illumos
[japin@db_build ~/extensions/orafce]$ pg_config
BINDIR = /home/japin/postgres/build/pg/bin
DOCDIR = /home/japin/postgres/build/pg/share/doc
HTMLDIR = /home/japin/postgres/build/pg/share/doc
INCLUDEDIR = /home/japin/postgres/build/pg/include
PKGINCLUDEDIR = /home/japin/postgres/build/pg/include
INCLUDEDIR-SERVER = /home/japin/postgres/build/pg/include/server
LIBDIR = /home/japin/postgres/build/pg/lib
PKGLIBDIR = /home/japin/postgres/build/pg/lib
LOCALEDIR = /home/japin/postgres/build/pg/share/locale
MANDIR = /home/japin/postgres/build/pg/share/man
SHAREDIR = /home/japin/postgres/build/pg/share
SYSCONFDIR = /home/japin/postgres/build/pg/etc
PGXS = /home/japin/postgres/build/pg/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE =  '--prefix=/home/japin/postgres/build/pg' '--enable-cassert' '--enable-debug' '--enable-depend' '--enable-nls' '--enable-rpath' '--enable-tap-tests' '--enable-thread-safety' '--with-gssapi' '--with-icu' '--with-ldap' '--with-libxml' '--with-libxslt' '--with-lz4' '--with-openssl' '--with-pam' '--with-perl' '--with-python' '--with-uuid=e2fs' '--with-zstd' 'CFLAGS=-Wsign-compare -Wno-error=implicit-function-declaration -ggdb -O0 -ftree-vectorize -pipe -fexceptions -Wl,-rpath,/home/japin/postgres/build/pg/lib'
CC = gcc
CPPFLAGS = -I/opt/local/include -D_POSIX_PTHREAD_SEMANTICS -I/opt/local/include/libxml2 -I/opt/local/include -I/opt/local/include -I/opt/local/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -Wsign-compare -Wno-error=implicit-function-declaration -ggdb -O0 -ftree-vectorize -pipe -fexceptions -Wl,-rpath,/home/japin/postgres/build/pg/lib
CFLAGS_SL = -fPIC
LDFLAGS = -L/opt/local/lib -L/opt/local/lib -L/opt/local/lib -Wl,-rpath,'/home/japin/postgres/build/pg/lib'
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lzstd -llz4 -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lsocket -lm
VERSION = PostgreSQL 16.3
```

It seems that this failure is caused by the rand function.  Here is a example:

```c
#include <stdio.h>
#include <stdlib.h>

int
main(void)
{
        int n;
        srand(8);

        n = rand();
        printf("%d\n", n);

        return 0;
}
```

On Ubuntu 22.04,

```bash
japin@ubuntu64g:~$ uname -a
Linux ubuntu64g 5.19.0-50-generic #50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
japin@ubuntu64g:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
japin@ubuntu64g:~$ gcc --version
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

japin@ubuntu64g:~$ gcc rand-test.c -o rand-test
japin@ubuntu64g:~$ ./rand-test
757547896
```

However, on Illumos,

```bash
[japin@db_build ~]$ gcc rand-test.c -o rand-test
[japin@db_build ~]$ ./rand-test
3634
```

**Comment by okbob** [comment]
po 13. 5. 2024 v 10:00 odesílatel Japin Li ***@***.***>
napsal:

> Hi,
>
> When attempting to use orafce with PostgreSQL 16.3 on Illumos, there were
> some failed regression tests for dbms_random.
>
> ***@***.***_build ~/extensions/orafce]$ cat regression.diffsdiff -U3 /home/japin/extensions/orafce/expected/dbms_random_2.out /home/japin/extensions/orafce/results/dbms_random.out--- /home/japin/extensions/orafce/expected/dbms_random_2.out    2024-05-13 06:21:39.162760522 +0000+++ /home/japin/extensions/orafce/results/dbms_random.out       2024-05-13 06:33:11.011606724 +0000@@ -8,13 +8,13 @@
>  SELECT dbms_random.normal()::numeric(10, 8);
>     normal
>  -------------- -2.88076095+ -1.22160768
>  (1 row)
>
>  SELECT dbms_random.normal()::numeric(10, 8);
>     normal
>  ------------- 1.07890275+ 0.91471634
>  (1 row)
>
>  SELECT dbms_random.seed(8);@@ -26,7 +26,7 @@
>  SELECT dbms_random.random();
>   random
>  --------- -32638+ -25498
>  (1 row)
>
>  SELECT dbms_random.seed('test');@@ -38,31 +38,31 @@
>  SELECT dbms_random.string('U',5);
>   string
>  --------- XXEJF+ VPQID
>  (1 row)
>
>  SELECT dbms_random.string('P',2);
>   string
>  --------- go+ *c
>  (1 row)
>
>  SELECT dbms_random.string('x',4);
>   string
>  --------- V3W9+ QY4P
>  (1 row)
>
>  SELECT dbms_random.string('a',2);
>   string
>  --------- GC+ gK
>  (1 row)
>
>  SELECT dbms_random.string('l',3);
>   string
>  --------- pbr+ dyl
>  (1 row)
>
>  SELECT dbms_random.seed(5);@@ -74,13 +74,13 @@
>  SELECT dbms_random.value()::numeric(10, 8);
>     value
>  ------------- 0.00164795+ 0.56930542
>  (1 row)
>
>  SELECT dbms_random.value(10,15)::numeric(10, 8);
>      value
>  -------------- 14.37820435+ 11.29043579
>  (1 row)
>
>  SELECT dbms_random.terminate();@@ -92,31 +92,31 @@
>  SELECT dbms_random.string('u', 10);
>     string
>  ------------- JTVYSOVZEW+ IZIUOSZPXQ
>  (1 row)
>
>  SELECT dbms_random.string('l', 10);
>     string
>  ------------- knadjpjaji+ sqinwaztpt
>  (1 row)
>
>  SELECT dbms_random.string('a', 10);
>     string
>  ------------- XSPLgEQeBm+ qKQoQidmEl
>  (1 row)
>
>  SELECT dbms_random.string('x', 10);
>     string
>  ------------- 5H7G1H2ERS+ 6ZTOV69J73
>  (1 row)
>
>  SELECT dbms_random.string('p', 10);
>     string
>  ------------- km:uKzx??E+ `f# tQP~r*
>  (1 row)
>
>  SELECT dbms_random.string('uu', 10); -- error@@ -124,6 +124,6 @@
>  SELECT dbms_random.string('w', 10);
>     string
>  ------------- MJCOVPXTET+ GIDLUOCSZH
>  (1 row)
>
> Here are my environments:
>
> ***@***.***_build ~/extensions/orafce]$ gcc --version
> gcc (GCC) 10.4.0
> Copyright (C) 2020 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
>
> ***@***.***_build ~/extensions/orafce]$ uname -a
> SunOS db_build 5.11 hunghu-20231216T132436Z i86pc i386 i86pc illumos
> ***@***.***_build ~/extensions/orafce]$ pg_config
> BINDIR = /home/japin/postgres/build/pg/bin
> DOCDIR = /home/japin/postgres/build/pg/share/doc
> HTMLDIR = /home/japin/postgres/build/pg/share/doc
> INCLUDEDIR = /home/japin/postgres/build/pg/include
> PKGINCLUDEDIR = /home/japin/postgres/build/pg/include
> INCLUDEDIR-SERVER = /home/japin/postgres/build/pg/include/server
> LIBDIR = /home/japin/postgres/build/pg/lib
> PKGLIBDIR = /home/japin/postgres/build/pg/lib
> LOCALEDIR = /home/japin/postgres/build/pg/share/locale
> MANDIR = /home/japin/postgres/build/pg/share/man
> SHAREDIR = /home/japin/postgres/build/pg/share
> SYSCONFDIR = /home/japin/postgres/build/pg/etc
> PGXS = /home/japin/postgres/build/pg/lib/pgxs/src/makefiles/pgxs.mk
> CONFIGURE =  '--prefix=/home/japin/postgres/build/pg' '--enable-cassert' '--enable-debug' '--enable-depend' '--enable-nls' '--enable-rpath' '--enable-tap-tests' '--enable-thread-safety' '--with-gssapi' '--with-icu' '--with-ldap' '--with-libxml' '--with-libxslt' '--with-lz4' '--with-openssl' '--with-pam' '--with-perl' '--with-python' '--with-uuid=e2fs' '--with-zstd' 'CFLAGS=-Wsign-compare -Wno-error=implicit-function-declaration -ggdb -O0 -ftree-vectorize -pipe -fexceptions -Wl,-rpath,/home/japin/postgres/build/pg/lib'
> CC = gcc
> CPPFLAGS = -I/opt/local/include -D_POSIX_PTHREAD_SEMANTICS -I/opt/local/include/libxml2 -I/opt/local/include -I/opt/local/include -I/opt/local/include
> CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -Wsign-compare -Wno-error=implicit-function-declaration -ggdb -O0 -ftree-vectorize -pipe -fexceptions -Wl,-rpath,/home/japin/postgres/build/pg/lib
> CFLAGS_SL = -fPIC
> LDFLAGS = -L/opt/local/lib -L/opt/local/lib -L/opt/local/lib -Wl,-rpath,'/home/japin/postgres/build/pg/lib'
> LDFLAGS_EX =
> LDFLAGS_SL =
> LIBS = -lpgcommon -lpgport -lzstd -llz4 -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lsocket -lm
> VERSION = PostgreSQL 16.3
>
> It seems that this failure is caused by the rand function. Here is a
> example:
>
> #include <stdio.h>#include <stdlib.h>
> intmain(void)
> {
>         int n;
>         srand(8);
>
>         n = rand();
>         printf("%d\n", n);
>
>         return 0;
> }
>
> On Ubuntu 22.04,
>
> ***@***.***:~$ uname -a
> Linux ubuntu64g 5.19.0-50-generic #50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
> ***@***.***:~$ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 22.04.4 LTS
> Release:        22.04
> Codename:       jammy
> ***@***.***:~$ gcc --version
> gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
> Copyright (C) 2021 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
>
> ***@***.***:~$ gcc rand-test.c -o rand-test
> ***@***.***:~$ ./rand-test
> 757547896
>
> However, on Illumos,
>
> ***@***.***_build ~]$ gcc rand-test.c -o rand-test
> ***@***.***_build ~]$ ./rand-test
> 3634
>
> It is common, please, send PR for new alternative
expected/dbms_random_4.out

Regards

Pavel

**Comment by japinli** [comment]
@okbob Thank you for your quick reply.  Create a PR (#265) to fix this.
