### ISSUE TITLE
DBMS_ASSERT.SIMPLE_SQL_NAME allows identifiers with leading numeric

### ISSUE THREAD

**Issue by jabrwoky** [orafce/orafce#267]
Oracle:
select DBMS_ASSERT.SIMPLE_SQL_NAME('1COL01') from dual;
SQL Error [44003] [99999]: ORA-44003: invalid SQL name
ORA-06512: at "SYS.DBMS_ASSERT", line 215

Orafce:
 select DBMS_ASSERT.SIMPLE_SQL_NAME('1COL01');
 1COL01
 
 No error is thrown on leading numeric

**Comment by okbob** [comment]
should be fixed by 362c6237fe68a7c89c00ff24f49f8e8425be323f

**Comment by okbob** [comment]
fixed 4.10.1
