### ISSUE TITLE
FATAL: failed to initialize orafce.umask to "0077"

### ISSUE THREAD

**Issue by ionutursuleanu** [orafce/orafce#268]
Hi @okbob,

I receive the following error for any user/schema, except superuser(the user who also creates the extension): `FATAL: failed to initialize orafce.umask to "0077"`. Could be related to https://github.com/orafce/orafce/commit/ae9d0302be607f86bdfecbf24e962678e6282e75 commit?

Can be reproduced by running:
```sql
select oracle.decode(1, 1, 1, 0);
```

On the other hand, `nvl` works fine...
```sql
select oracle.nvl(1, 1);
```

I use docker for running posgtres with orafce:
```dockerfile
FROM postgres:16.3
RUN apt-get update && apt-get install -y postgresql-16-orafce
```

**Comment by okbob** [comment]
Hi

po 20. 5. 2024 v 18:30 odesílatel Ionuț Ursuleanu ***@***.***>
napsal:

> Hi @okbob <https://github.com/okbob>,
>
> Starting with 4.10.0 I receive the following error for any user/schema,
> except superuser(the user who also creates the extension): FATAL: failed
> to initialize orafce.umask to "0077". Maybe is related to ae9d030
> <https://github.com/orafce/orafce/commit/ae9d0302be607f86bdfecbf24e962678e6282e75>
> commit?
>
> Can be reproduced by running:
>
> select oracle.decode(1, 1, 1, 0);
>
> On the other hand, nvl works fine...
>
> select oracle.nvl(1, 1);
>
> I use docker for running posgtres with orafce:
>
> FROM postgres:16.3RUN apt-get update && apt-get install -y postgresql-16-orafce
>
>
I am able to reproduce it. I'll fix it.

**Comment by okbob** [comment]
should be fixed now, please check

**Comment by ionutursuleanu** [comment]
Thanks for the fix! `apt-get install postgresql-16-orafce` still on 4.10.0. I will come back with feedback after 4.10.2 is available as debian package.

**Comment by Fuzip** [comment]
We had the same problem in our company (on RedHat 8.6) :
```
2024-05-25 22:37:55.926 CEST [1944785] DÉTAIL:  Only roles with privileges of the "orafce_set_umask" can set "orafce.umask".
2024-05-25 22:37:55.927 CEST [1944785] FATAL:  failed to initialize orafce.umask to "0077"
```

I confirm upgrade orafce 4.10 to 4.10.2 fix this.

**Comment by okbob** [comment]
Thank you for echo

**Comment by ionutursuleanu** [comment]
I can also confirm that it works with 4.10.3. Thanks
