### ISSUE TITLE
Question on function dbms_alert.defered_signal

### ISSUE THREAD

**Issue by esiaero** [orafce/orafce#276]
I noticed there was a commit 6fd1526dbd63972688dcde82404e960f7087cded that deletes the `dbms_alert.defered_signal` function from the main SQL script, but upgrade scripts are not changed. 

Doesn't it also make sense to change the upgrade script so the function is removed on existing installs? Or am I misunderstanding the intention here?

It would also avoid situation like https://github.com/orafce/orafce/issues/231, if the extension is updated to drop the function first before `pg_upgrade`. Though in this case, the header has been returned as a workaround in https://github.com/orafce/orafce/commit/bc45ed4e8d8e93951a3d20ee60cedb5cebba0fb7

Thanks

**Comment by okbob** [comment]
yes, it should be removed - the C implementation should be here, because I have not an idea about starting point of migration, but SQL signature is garbage.

e49c44c984c880553f2798be421b125bf4dcbb99

**Comment by okbob** [comment]
should be fixed in 4.13.0
