### ISSUE TITLE
invalid ECHO statement breaks tests with PostgreSQL 9.4.1

### ISSUE THREAD

**Issue by martinpitt** [orafce/orafce#28]
PostgreSQL 9.4.1 now writes an error message on invalid values of `\set ECHO`. orafce's tests have two invalid statements:

    sql/dbms_pipe_session_B.sql:\set ECHO all;
    sql/dbms_pipe_session_A.sql:\set ECHO all;

The semicolon is invalid and interpreted as part of the value, so tests fail with:
```
*** /tmp/adt-run.kPtv9H/build.I1z/orafce-3.0.7/expected/dbms_pipe_session_A.out	2014-07-27 20:10:01.000000000 +0000
--- /tmp/adt-run.kPtv9H/build.I1z/orafce-3.0.7/results/dbms_pipe_session_A.out	2015-02-08 10:12:42.305125312 +0000
***************
*** 9,14 ****
--- 9,15 ----
              0
  (1 row)
  
+ unrecognized value "all;" for "ECHO"; assuming "none"
   createimplicitpipe 
  --------------------
```   
(same for the _B test). Merely dropping the semicolon isn't enough as the expected values aren't actually containing the echoed commands. So I suggest to either just drop the two `\set ECHO all;` lines, or drop the semicolon and add the echoed commands to the expected output.

**Comment by amitlan** [comment]
PR #29 including a commit to fix this issue has been merged.
