### ISSUE TITLE
4.13 not installable, control file still on 4.12

### ISSUE THREAD

**Issue by df7cb** [orafce/orafce#280]
```
CREATE EXTENSION orafce;
ERROR:  extension "orafce" has no installation script nor update path for version "4.12"
```

orafce.control is still on 4.12:
```
default_version = '4.12'
```

**Comment by okbob** [comment]
should be fixed now, please, check

**Comment by df7cb** [comment]
Working now, thanks!

**Comment by okbob** [comment]
čt 26. 9. 2024 v 23:55 odesílatel Christoph Berg ***@***.***>
napsal:

> Working now, thanks!
>

Thank you for check and bug report
