### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by leopoldev404** [orafce/orafce#282]
I am trying to setup a custom docker container image using a docker file based on ubuntu that has a postgres 9.6 database.

I do not have the NPGX client, so I am trying to build orafce it from the source.

I have followed the steps in the installation guide but I get this error:

![image](https://github.com/user-attachments/assets/91031317-f97f-426e-8d32-4a3461552c26)

Should I assume I need some prerequisites?

**Comment by okbob** [comment]
Hi

po 7. 10. 2024 v 18:05 odesílatel Leonardo Pol ***@***.***>
napsal:

> I am trying to setup a custom docker container image using a docker file
> based on ubuntu that has a postgres 9.6 database.
> I need to install orafce, but in the install.md all I can read is make
> install, but I get the error
>

I am sure, so PostgreSQL 9.6 is not supported - support for this release
was removed minimally three years ago

**Comment by leopoldev404** [comment]
thank you so much for the answer!
Anyway I saw in the INSTALLING guide that `"This module is normally distributed as a PostgreSQL 'contrib' module"`.

What does this mean? Does it mean that when installing postgres I get access to it?

**Comment by leopoldev404** [comment]
also, besides the postgres version, I just want to install orafce in an ubuntu container, but the steps reported in the guide are not working, am I missing something?

**Comment by okbob** [comment]
po 7. 10. 2024 v 21:43 odesílatel Leonardo Pol ***@***.***>
napsal:

> thank you so much for the answer!
> Anyway I saw in the INSTALLING guide that "This module is normally
> distributed as a PostgreSQL 'contrib' module".
>
> What does this mean? Does it mean that when installing postgres I get
> access to it?
>

This sentence is obsolete. Years ago the extensions was compiled inside
contrib directory. And the people has not idea what is an extension. But
this is obsolete now.

**Comment by okbob** [comment]
po 7. 10. 2024 v 21:45 odesílatel Leonardo Pol ***@***.***>
napsal:

> also, besides the postgres version, I just want to install orafce in an
> ubuntu container, but the steps reported in the guide are not working, am I
> missing something?
>
I don't know, I newer did it. But I think it cannot work, because the
compilation should fail. pgxn doesn't support compiled libraries. It is
compiled on the client side, and then against PostgreSQL 9.6 it should fail.

PostgreSQL extensions are compiled for specified Postgres version and
platform, and cannot be used for different version or platform.

**Comment by leopoldev404** [comment]
ok, thank you so much for the answer, really appreciated it!
