### ISSUE TITLE
Create extension fail on Windows: could not find function orafce_sys_extract_utc

### ISSUE THREAD

**Issue by kav23alex** [orafce/orafce#287]
Hello!
On windows after command "create extension orafce;" get error could not find function orafce_sys_extract_utc.
In commit 607ce0ce added functions orafce_sys_extract_utc and orafce_sys_extract_utc_oracle_date, but miss exports in builtins.h

**Comment by okbob** [comment]
please, check 4.13.5

**Comment by kav23alex** [comment]
Thank you, it works

**Comment by okbob** [comment]
Thank you for bug report

čt 24. 10. 2024 v 4:49 odesílatel kav23alex ***@***.***>
napsal:
