### ISSUE TITLE
Request to support specifying schema

### ISSUE THREAD

**Issue by squishypenguin** [orafce/orafce#292]
We are migrating from Oracle to Postgres but someone way back in time, made the bad decision to have a schema named "oracle". So now in our Postgres instance, we have a schema called "oracle" and to rename that just isn't feasible. But we want to use the orafce to get access to the alerting so we don't have to rewrite that. But your code has the schema hardcoded to "oracle" instead of something like "orafce" that would be guaranteed to be unique. Asking that there be a way to specify the schema. 
We might just have to fork and do this on our own but I wanted to submit this to get thoughts.

**Comment by okbob** [comment]
út 17. 12. 2024 v 1:02 odesílatel Julie Mather ***@***.***>
napsal:

> We are migrating from Oracle to Postgres but someone way back in time,
> made the bad decision to have a schema named "oracle". So now in our
> Postgres instance, we have a schema called "oracle" and to rename that just
> isn't feasible. But we want to use the orafce to get access to the alerting
> so we don't have to rewrite that. But your code has the schema hardcoded to
> "oracle" instead of something like "orafce" that would be guaranteed to be
> unique. Asking that there be a way to specify the schema.
> We might just have to fork and do this on our own but I wanted to submit
> this to get thoughts.
>
Postgres allows to specify install schema for extensions - but Orafce
doesn't support it. I think it can support it, it needs about a week of
work.
Unfortunately, it is across all Orafce parts + all sql update scripts +
very probably changes in regress tests.

"Dirty" solution like a fork and hardcode replacement of an oracle by
something else is easy - almost mechanical work, but it is dirty.

**Comment by squishypenguin** [comment]
Thanks @okbob . I also think the forking would be not ideal but it was the thought for a quick turnaround so we can move forward with our migration. My thinking was no contributor dev could/would be able to get this change in by end of year.

**Comment by okbob** [comment]
I was wrong, the possibility to specify target schema is not posible to use
for orafce, because it uses more than just one schema. So you should to
make fork.

Dne út 17. 12. 2024 7:14 uživatel Pavel Stehule ***@***.***>
napsal:

**Comment by squishypenguin** [comment]
Ok I'll close this. Thanks.
