### ISSUE TITLE
Overflow problem on median compute

### ISSUE THREAD

**Issue by olivierayache** [orafce/orafce#35]
In aggregate.c the following method is erroneous:

int orafce_float8_cmp(const void *a, const void *b)
{
	return (int) (*((float8 *) a) - *((float8*) b));
}

cast float8 to int can lead to overflow problems.

On 32 bits platforms orafce_float4_cmp is erroneous too.

This code correct the problem:

int orafce_float8_cmp(const void *a, const void *b)
{
  float8 diff = *((float8 *) a) - *((float8*) b);
  if(diff==0)
    return 0;
  else if(diff<0)
    return -1;
}
return 1;

**Comment by okbob** [comment]
fixed - thank you for report
