### ISSUE TITLE
9.5 build error

### ISSUE THREAD

**Issue by devrimgunduz** [orafce/orafce#36]
Hi,

I'm getting these while trying to build orafce against 9.5:

+ make -j3
pipe.c: In function 'dbms_pipe_create_pipe':
pipe.c:1093:72: error: too few arguments to function 'GetUserNameFromId'
     user = (char*)DirectFunctionCall1(namein, CStringGetDatum(GetUserNameFromId(p->uid)));
                                                                        ^
In file included from pipe.c:11:0:
/usr/pgsql-9.5/include/server/miscadmin.h:299:14: note: declared here
 extern char *GetUserNameFromId(Oid roleid, bool noerr);
              ^
make[1]: *** [pipe.o] Error 1
make[1]: *** Waiting for unfinished jobs....

**Comment by okbob** [comment]
It should be fixed by https://github.com/orafce/orafce/commit/4b421f0e499c4d3fc9ae60bb6627864e1e06cdb1 - I'll release new version 3.0.14

**Comment by okbob** [comment]
Should be fixed on 3.1.2 http://pgxn-tester.org/distributions/orafce/3.1.2

**Comment by devrimgunduz** [comment]
Confirmed, thanks!
