### ISSUE TITLE
sysdate() function

### ISSUE THREAD

**Issue by legrandlegrand** [orafce/orafce#40]
would it be possible to add SYSDATE() funtion

based on
CREATE or REPLACE FUNCTION SYSDATE()
RETURNS oracle.date AS $$
SELECT statement_timestamp()::oracle.date ;
$$ LANGUAGE sql ...

that returns the current date and time when statement starts (not transaction start) set for the operating system on which the database resides. The datatype of the returned value is (Oracle) DATE, and the format returned depends on the value of the NLS_DATE_FORMAT initialization parameter. The function requires no arguments.

**Comment by okbob** [comment]
here is proposed code http://planet.postgresql.org/

**Comment by okbob** [comment]
merged,

thank you for postcard - nice land
