### ISSUE TITLE
utl_file P0001 UTL_FILE_INVALID_PATH

### ISSUE THREAD

**Issue by walpino** [orafce/orafce#43]
Hi there
I'm using this extension to write a file

I know every directory must be in the utl_file.utl_file_dir table

if I add /tmp then it works

if I add /tmp/wam then I always get an UTL_FILE_INVALID_PATH error

Is there a bug?

Thanks

Martin

**Comment by okbob** [comment]
Hi

2016-04-26 9:34 GMT+02:00 walpino <notifications@github.com>:

> Hi there
> I'm using this extension to write a file
>
> I know every directory must be in the utl_file.utl_file_dir table
>
> if I add /tmp then it works
>
> if I add /tmp/wam then I always get an UTL_FILE_INVALID_PATH error
>

Have you some other informations about this error? errdetail or errhint?

The reason can be

a) missing rights to this directory for user "postgres"

b) eny directory should be explicitly allowed in table utl_file_dir

Regards

Pavel

**Comment by walpino** [comment]
it was the missing rights to overwirte an existing file

the error UTL_FILE_INVALID_PATH  is a little bit misleading in this situation

**Comment by walpino** [comment]
but I have still one question to you

is there a way to set the permissions on the created files?

**Comment by okbob** [comment]
2016-04-26 17:21 GMT+02:00 walpino <notifications@github.com>:

> it was the missing rights to overwirte an existing file
>
> the error UTL_FILE_INVALID_PATH is a little bit misleading in this
> situation
>

the more info is from additional error fields.

Regards

Pavel

**Comment by okbob** [comment]
2016-04-26 17:21 GMT+02:00 walpino <notifications@github.com>:

> but I have still one question to you
>
> is there a way to set the permissions on the created files?
>
no, it is not possible - there is not any function for this purpose. It use
default rights for directory.

New versions of Oracle has command CREATE DIRECTORY and you can set rights
for these object, but this feature is not implemented in Orafce. Probably
it can be emulated by Row Security

Now, I am looking on new version of this library in Oracle and this
supports more errors like ACCESS_DENIED, so the error message can be fixed
in future in Orafce.

The rights can be changed from PLPerlu or PLPythonu.

**Comment by walpino** [comment]
So that means the file I Write with the utl_file.fopen
This file have always the same permissions?
Only rw for the postgres User?

So no other OS User can read them

**Comment by okbob** [comment]
Hi

2016-04-26 20:55 GMT+02:00 walpino <notifications@github.com>:

> So that means the file I Write with the utl_file.fopen
> This file have always the same permissions?
> Only rw for the postgres User?
>
The owner is postgres user. Permissions depends on directory default.
Orafce does nothing settings.

Regards

Pavel
