### ISSUE TITLE
ROUND(double precision, integer)

### ISSUE THREAD

**Issue by legrandlegrand** [orafce/orafce#44]
It seems that ROUND(double precision, integer) is not supported in PostgreSQL.

But it is supported in Oracle:

**ROUND(n, integer)**

ROUND returns n rounded to integer places to the right of the decimal point. If you omit integer, then n is rounded to 0 places. The argument integer can be negative to round off digits left of the decimal point.

n can be any numeric datatype or any nonnumeric datatype that can be implicitly converted to a numeric datatype. The argument integer must be an integer. If you omit integer, then the function returns the same datatype as the numeric datatype of the argument. **If you include integer, then the function returns NUMBER.**

This also applyes to TRUNC(double precision, integer)

Here are the founctions that could be added to solve this issue:

    CREATE or REPLACE FUNCTION oracle.round(double precision, int)
    RETURNS numeric
    AS $$SELECT pg_catalog.round($1::numeric, $2)$$
    LANGUAGE sql;

    CREATE or REPLACE FUNCTION oracle.trunc(double precision, int)
    RETURNS numeric
    AS $$SELECT pg_catalog.trunc($1::numeric, $2)$$
    LANGUAGE sql;

**Comment by okbob** [comment]
tested on vanilla Postgres
 
postgres=# select round(1.2233,1), trunc(1.234,2);
┌───────┬───────┐
│ round │ trunc │
╞═══════╪═══════╡
│   1.2 │  1.23 │
└───────┴───────┘
(1 row)

**Comment by okbob** [comment]
https://github.com/orafce/orafce/commit/18215d55460736ed2d12665d5a27d9e3a519ef4d
