### ISSUE TITLE
hi everyone, Issue with UTL_FILE package

### ISSUE THREAD

**Issue by kamfasage** [orafce/orafce#49]
I'm looking out how to use UTL_FILE package..
Every time i do"perform UTL_FILE.PUT_LINE ( myUTLfileType, ' text i want to add');"
I've my pgadmin server disconnect...and my application crashes...
what could be the problem?
thanks for your help in advance..

**Comment by okbob** [comment]
2016-12-23 15:17 GMT+01:00 kamfasage <notifications@github.com>:

> I'm looking out how to use UTL_FILE package..
> Every time i do"perform UTL_FILE.PUT_LINE ( myUTLfileType, ' text i want
> to add');"
> I've my pgadmin server disconnect...and my application crashes...
> what could be the problem?
> thanks for your help in advance..
>
It looks on server crash - but there are too less information about your
issue.

Can you send complete test case?

**Comment by kamfasage** [comment]
hi, my apologies for not answering earlier.. i wasn't doing fine (i was sick) :)

`CREATE OR REPLACE FUNCTION gen_file(
    mydir text,
    infile text,
    outfile text,
    copyfile text)
  RETURNS void AS
$BODY$
DECLARE
  v1 VARCHAR(32767);
  inf UTL_FILE.FILE_TYPE;
  otf UTL_FILE.FILE_TYPE;
BEGIN
  inf := UTL_FILE.FOPEN(mydir, infile,'r',256);
  otf := UTL_FILE.FOPEN(mydir, outfile,'w');
  v1 := UTL_FILE.GET_LINE(inf,256);
  PERFORM UTL_FILE.PUT_LINE(otf,v1,TRUE);
  v1 := UTL_FILE.GET_LINE(inf,256);
  PERFORM UTL_FILE.PUTF(otf,'%s\n',v1);
  v1 := UTL_FILE.GET_LINE(inf, 256);
  PERFORM UTL_FILE.PUT(otf,v1);
  PERFORM UTL_FILE.NEW_LINE(otf);
  PERFORM UTL_FILE.FFLUSH(otf);

  inf := UTL_FILE.FCLOSE(inf);
  otf := UTL_FILE.FCLOSE(otf);

  PERFORM UTL_FILE.FCOPY(mydir, outfile, mydir, copyfile, 2, 3);
  PERFORM UTL_FILE.FRENAME(mydir, outfile, mydir, 'rename.txt');

END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;`

so when i do a 
`SELECT gen_file('c:/symfo', 'input.txt', 'output.txt', 'copyfile.txt');`

my server (pgadmin)(in loclahost) disconnect

**Comment by kamfasage** [comment]
the server craches by the moment i use
' utl_file.GET_LINE ' function
i don't really why..
please help

**Comment by okbob** [comment]
Hi

2017-01-09 11:17 GMT+01:00 kamfasage <notifications@github.com>:

> the server craches by the moment i use
> ' utl_file.GET_LINE ' function
> i don't really why..
> please help
>
I checked your code on linux - I have not a MS Windows - and it is working
well on Linux

Possible issues

some security issues

a) target dictionary should be registered in table utl_file.utl_file_dir.

Before using package you have to set table utl_file.utl_file_dir. This
contains all allowed directories without ending symbol ('/' or '\'). On
WinNT platform you have to put locality parametr with ending symbol '\'
everytime.

see doc https://github.com/orafce/orafce

b) the target dictionary should be accessible by user "postgres" or user
account used for execution postgresql service.

I checked the code - and I don't see a reason why Postgres can be killed -
maybe you hit some Microsoft security feature.

Are you able send me a backtrace?

Regards

Pavel


Regards

Pavel

**Comment by kamfasage** [comment]
Thanks for your answer.. 
For a)  i have made sure the target dictionary is registered because i could use fopen without any path error.. 
B)  the target is accessible by the user postgres i think  (how do i check this) 

What do you mean by backtrace ?

**Comment by kamfasage** [comment]
Best regards

**Comment by okbob** [comment]
2017-01-09 21:51 GMT+01:00 kamfasage <notifications@github.com>:

> Thanks for your answer..
> For a) i have made sure the target dictionary is registered because i
> could use fopen without any path error..
> B) the target is accessible by the user postgres i think (how do i check
> this)
>
I am not a expert on windows - try to set rights to this directory to
everyone


> What do you mean by backtrace ?
>

It is information where Postgres crash and stack of functions calls.

But you need some debug tools on windows.

Regards

Pavel

**Comment by kamfasage** [comment]
hi 
may be it's the way i install orafce into windows..
can you please explain to me how to do it?
so i can compare with what i did..
because i did this method from the net 
[(https://groups.google.com/forum/#!topic/orafce-general/tUEPnrECO1E`))]

**Comment by okbob** [comment]
2017-01-10 9:34 GMT+01:00 kamfasage <notifications@github.com>:

> hi
> may be it's the way i install orafce into windows..
> can you please explain to me how to do it?
> so i can compare with what i did..
> because i did this method from the net
> [(https://groups.google.com/forum/#!topic/orafce-general/tUEPnrECO1E`)
> <https://groups.google.com/forum/#!topic/orafce-general/tUEPnrECO1E)>)]
>

if you check any other function from Orafce package, then your Orafce will
be ok.

**Comment by kamfasage** [comment]
there is just fopen functions that work and fclose the other 's make my server crashes

**Comment by okbob** [comment]
2017-01-10 10:30 GMT+01:00 kamfasage <notifications@github.com>:

> there is just fopen functions that work and fclose the other 's make my
> server crashes
>
Please, check your system log, maybe there will be some interesting info

Pavel

**Comment by kamfasage** [comment]
i have this on my systeme log

> Nom de l’application défaillante pgAdmin3.exe, version : 1.22.1.1, horodatage : 0x57316441
> Nom du module défaillant : MSVCR120.dll, version : 12.0.21005.1, horodatage : 0x524f83ff
> Code d’exception : 0xc0000417
> Décalage d’erreur : 0x000000000006dd3d
> ID du processus défaillant : 0xeb0
> Heure de début de l’application défaillante : 0x01d26a60f3f656b5
> Chemin d’accès de l’application défaillante : C:\apps\POSTGRESQL\PostgreSQL9.5\bin\pgAdmin3.exe
> Chemin d’accès du module défaillant: C:\windows\system32\MSVCR120.dll
> ID de rapport : 1f842515-d655-11e6-b4c7-24be051202b5
>

**Comment by kamfasage** [comment]
for more detail 

Provider 

   [ Name]  Application Error 
 
  - EventID 1000 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 100 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2017-01-09T10:19:38.000000000Z 
 
   EventRecordID 190701 
 
   Channel Application 
 
   Computer XXXXXXXXXX 
 
   Security 
 

- EventData 

   pgAdmin3.exe 
   1.22.1.1 
   57316441 
   MSVCR120.dll 
   12.0.21005.1 
   524f83ff 
   c0000417 
   000000000006dd3d 
   eb0 
   01d26a60f3f656b5 
   C:\apps\POSTGRESQL\PostgreSQL9.5\bin\pgAdmin3.exe 
   C:\windows\system32\MSVCR120.dll 
   1f842515-d655-11e6-b4c7-24be051202b5

**Comment by okbob** [comment]
Maybe I am able to reproduce it on MSWindows. Unfortunately have no idea how to fix it. Microsoft API returns broken data - have not a idea why.

**Comment by okbob** [comment]
Looks like some hard issue between PostgreSQL implementation and basic MSVC function implementation. I am not able do fopen/fclose call without a exception.

**Comment by okbob** [comment]
I am able to fix a exception by using _xxx_nolock functions, but it still doesn't work - because opened file is very immediately closed without my request, and any other operations fails. Now I have plan to block this functionality on win 32 platform, where it is doesn't work.

**Comment by okbob** [comment]
Hi
I didn't find a reason why dis function doesn't work on MS Windows. Probably it is related to some security, maybe some other. Unfortunately, then there is only one solution. I disabled this function on MS Windows platform :(
