### ISSUE TITLE
acces to file via UTL_FILE 

### ISSUE THREAD

**Issue by kamfasage** [orafce/orafce#50]
Hi , i've an issue (how do the package works)..
if i've understood, when you have install Orafce for using UTL_FILE,
It creates a table "utl_file.utl_file_dir " where directory path is stored.
To access to it i have just in my "PUT_LINE" function to specify the **path directory** not to make a select into that table?
that works if the directory is in the same computer (server) where postgresql is install..
if i want to acces to a specific directory in another server where there is not postgres install , how do i do?

help me

**Comment by okbob** [comment]
2017-01-12 17:33 GMT+01:00 kamfasage <notifications@github.com>:

> Hi , i've an issue (how do the package works)..
> if i've understood, when you have install Orafce for using UTL_FILE,
> It creates a table "utl_file.utl_file_dir " where directory path is stored.
> To access to it i have just in my "PUT_LINE" function to specify the *path
> directory* not to make a select into that table?
> that works if the directory is in the same computer (server) where
> postgresql is install..
> if i want to acces to a specific directory in another server where there
> is not postgres install , how do i do?
>

It requires a absolute path - but this path can be mounted to some network
filesystem, or some network sources. Orafce doesn't check if this directory
is on physical server or else where.

Regards

Pavel

**Comment by kamfasage** [comment]
But how does he point to the external folder??

**Comment by okbob** [comment]
The Orafce should not to know if some folder is external or not. http://serverfault.com/questions/105633/mount-remote-cifs-smb-share-as-a-folder-not-a-drive-letter

**Comment by okbob** [comment]
Hi
I didn't find a reason why dis function doesn't work on MS Windows. Probably it is related to some security, maybe some other. Unfortunately, then there is only one solution. I disabled this function on MS Windows platform :(
