### ISSUE TITLE
plvlex_tokens not found into orafce.dll

### ISSUE THREAD

**Issue by kamfasage** [orafce/orafce#51]
Hi ,
i have got the orafce 3.3.1  compile for windows here "https://groups.google.com/forum/#!topic/orafce-general/bZNUXXR1RsQ"
but when i try creating the extension i have an error due to "plvlex_tokens" missing into orafce.dll.

I' m using the "orafce.dll" for postgres 9.5 install in windows 64 bit.
thanks for your answer

**Comment by okbob** [comment]
The orafce-3.3.sql is broken in the zip file - please use orafce-3.3.sql attached to last mail in this thread

**Comment by kamfasage** [comment]
Ok thanks, i thought the problem was the orafce version .. but still having my server disconnecting when i call " utl_file.put_line " function.. 
What could be the problem???

**Comment by okbob** [comment]
Without backtrace and exact error number I can say nothing, I am sorry
