### ISSUE TITLE
regression test error in PG9.6 (RHEL/CentOS7 RPM)

### ISSUE THREAD

**Issue by kfuru** [orafce/orafce#53]
Hello,

I tried the orafce 3.4.0 source, but an error occurs in the regression test.

RHEL/CentOS 7 posrgresql9.6 RPM provided by the community,
regression test will coredump.
Because the configure option "-enable-dtrace" is enabled in PG9.6 (RHEL/CentOS7).

I used the postgresql RPM below.
 https://yum.postgresql.org/9.6/redhat/rhel-7-x86_64/repoview/postgresqldbserver96.group.html

But, there is no problem as PG9.6(RHEL/CentOS 6) RPM by the community does not have "-enable-dtrace" option.
PostgreSQL RPM configure option is different in RHEL/CentOS 6 and 7.

***** regression test *****
<pre>
$ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
$ psql --version
psql (PostgreSQL) 9.6.2
$
$ make installcheck
/usr/pgsql-9.6/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/pgsql-9.6/bin'    --load-language=plpgsql --schedule=parallel_schedule --encoding=utf8 --dbname=contrib_regression orafce orafce2 dbms_output dbms_utility files varchar2 nvarchar2 aggregates nlssort dbms_random
(using postmaster on Unix socket, default port)
============== dropping database "contrib_regression" ==============
DROP DATABASE
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== installing plpgsql                     ==============
CREATE LANGUAGE
============== running regression test queries        ==============
test init                     ... ok
parallel group (2 tests):  dbms_pipe_session_A dbms_pipe_session_B
     dbms_pipe_session_A      ... FAILED (test process exited with exit code 2)
     dbms_pipe_session_B      ... FAILED (test process exited with exit code 2)
parallel group (3 tests):  dbms_alert_session_B dbms_alert_session_A dbms_alert_session_C
     dbms_alert_session_A     ... FAILED (test process exited with exit code 2)
     dbms_alert_session_B     ... FAILED (test process exited with exit code 2)
     dbms_alert_session_C     ... FAILED (test process exited with exit code 2)
test orafce                   ... FAILED (test process exited with exit code 2)
test orafce2                  ... ok
test dbms_output              ... ok
test dbms_utility             ... ok
test files                    ... ok
test varchar2                 ... ok
test nvarchar2                ... ok
test aggregates               ... ok
test nlssort                  ... ok
test dbms_random              ... ok

=======================
 6 of 16 tests failed.
=======================

***** backtrace from coredump. ******

$ gdb postgres core
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/pgsql-9.6/bin/postgres...Reading symbols from /usr/lib/debug/usr/pgsql-9.6/bin/postgres.debug...done.
done.
[New LWP 828]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `postgres: postgres contrib_r'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000006c2265 in LWLockAcquire (lock=lock@entry=0x7f58f1e8ea08, mode=mode@entry=LW_EXCLUSIVE) at lwlock.c:1314
1314            TRACE_POSTGRESQL_LWLOCK_ACQUIRE(T_NAME(lock), T_ID(lock), mode);
Missing separate debuginfos, use: debuginfo-install audit-libs-2.6.5-3.el7_3.1.x86_64 bzip2-libs-1.0.6-13.el7.x86_64 cyrus-sasl-lib-2.1.26-20.el7_2.x86_64 elfutils-libelf-0.166-2.el7.x86_64 elfutils-libs-0.166-2.el7.x86_64 glibc-2.17-157.el7_3.1.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.14.1-27.el7_3.x86_64 libattr-2.4.46-12.el7.x86_64 libcap-2.22-8.el7.x86_64 libcap-ng-0.7.5-4.el7.x86_64 libcom_err-1.42.9-9.el7.x86_64 libgcc-4.8.5-11.el7.x86_64 libgcrypt-1.5.3-13.el7_3.1.x86_64 libgpg-error-1.12-3.el7.x86_64 libselinux-2.5-6.el7.x86_64 libxml2-2.9.1-6.el7_2.3.x86_64 nspr-4.13.1-1.0.el7_3.x86_64 nss-3.28.2-1.6.el7_3.x86_64 nss-softokn-freebl-3.16.2.3-14.4.el7.x86_64 nss-util-3.28.2-1.1.el7_3.x86_64 openldap-2.4.40-13.el7.x86_64 openssl-libs-1.0.1e-60.el7_3.1.x86_64 pam-1.1.8-18.el7.x86_64 pcre-8.32-15.el7_2.1.x86_64 systemd-libs-219-30.el7_3.7.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00000000006c2265 in LWLockAcquire (lock=lock@entry=0x7f58f1e8ea08, mode=mode@entry=LW_EXCLUSIVE) at lwlock.c:1314
#1  0x00007f58e9091edb in ora_lock_shmem (size=size@entry=30720, max_pipes=max_pipes@entry=30, max_events=max_events@entry=30, max_locks=max_locks@entry=256,
    reset=reset@entry=0 '\000') at pipe.c:323
#2  0x00007f58e9092bd7 in add_to_pipe (limit_is_valid=0 '\000', limit=0, ptr=0x294ef40, pipe_name=0x290fb88) at pipe.c:506
#3  dbms_pipe_send_message (fcinfo=<optimized out>) at pipe.c:937
#4  0x00000000005c4132 in ExecMakeFunctionResultNoSets (fcache=0x293d950, econtext=0x293d760, isNull=0x293e3f8 "\020", isDone=<optimized out>)
    at execQual.c:2041
#5  0x00000000005c9c5e in ExecTargetList (tupdesc=<optimized out>, isDone=0x7ffdcce3cf94, itemIsDone=0x293e510, isnull=0x293e3f8 "\020", values=0x293e3e0,
    econtext=0x293d760, targetlist=0x293e4e0) at execQual.c:5423
#6  ExecProject (projInfo=<optimized out>, isDone=isDone@entry=0x7ffdcce3cf94) at execQual.c:5647
#7  0x00000000005dec42 in ExecResult (node=node@entry=0x293d650) at nodeResult.c:155
#8  0x00000000005c3208 in ExecProcNode (node=node@entry=0x293d650) at execProcnode.c:392
#9  0x00000000005bf577 in ExecutePlan (dest=0x293b6f0, direction=<optimized out>, numberTuples=0, sendTuples=1 '\001', operation=CMD_SELECT,
    use_parallel_mode=<optimized out>, planstate=0x293d650, estate=0x293d540) at execMain.c:1569
#10 standard_ExecutorRun (queryDesc=0x28b4d10, direction=<optimized out>, count=0) at execMain.c:338
#11 0x00000000006d20e7 in PortalRunSelect (portal=portal@entry=0x28ad030, forward=forward@entry=1 '\001', count=0, count@entry=9223372036854775807,
    dest=dest@entry=0x293b6f0) at pquery.c:948
#12 0x00000000006d34fb in PortalRun (portal=0x28ad030, count=9223372036854775807, isTopLevel=<optimized out>, dest=0x293b6f0, altdest=0x293b6f0,
    completionTag=0x7ffdcce3d420 "") at pquery.c:789
#13 0x00000000006d1146 in PostgresMain (argc=<optimized out>, argv=<optimized out>, dbname=<optimized out>, username=<optimized out>) at postgres.c:1094
#14 0x000000000046f605 in BackendRun (port=0x28b5150) at postmaster.c:4271
#15 BackendStartup (port=0x28b5150) at postmaster.c:3945
#16 ServerLoop () at postmaster.c:1701
#17 0x00000000006748f8 in PostmasterMain (argc=argc@entry=1, argv=argv@entry=0x288da60) at postmaster.c:1309
#18 0x000000000047026e in main (argc=1, argv=0x288da60) at main.c:228
(gdb)
</pre>

Probably,
I think that orafce needs to call LWLockRegisterTranche() before LWLockAcquire() in each process(session).

It was written as follows in lwlock.h

lwlock.h
<pre>
> /*
>  * There is another, more flexible method of obtaining lwlocks. First, call
>  * LWLockNewTrancheId just once to obtain a tranche ID; this allocates from
>  * a shared counter.  Next, each individual process using the tranche should
>  * call LWLockRegisterTranche() to associate that tranche ID with appropriate
>  * metadata.  Finally, LWLockInitialize should be called just once per lwlock,
>  * passing the tranche ID as an argument.
>  *
>  * It may seem strange that each process using the tranche must register it
>  * separately, but dynamic shared memory segments aren't guaranteed to be
>  * mapped at the same address in all coordinating backends, so storing the
>  * registration in the main shared memory segment wouldn't work for that case.
>  */
</pre>

For example, if you do the following in pipe.c,
then regression test will be OK.

Example:

pipe.c
<pre>
----------
ora_lock_shmem()
:
:
#if PG_VERSION_NUM >= 90600

#if PG_VERSION_NUM < 100000                                                           //add
                                                                                      //add
                        {                                                             //add
                                static LWLockTranche tranche;                         //add
                                                                                      //add
 　                               tranche.name = "orafce";                              //add
   　                             tranche.array_base = &sh_mem->shmem_lock;             //add
  　                              tranche.array_stride = sizeof(LWLock);                //add
  　                              LWLockRegisterTranche(sh_mem->tranche_id, &tranche);  //add
 　                                                                                     //add
　                        }                                                             //add
 　                                                                                     //add
　#endif                                                                                //add
 　                       shmem_lockid = &sh_mem->shmem_lock;
　
　#else
　
 　                       shmem_lockid = sh_mem->shmem_lockid;
　
　#endif
　
 　                       LWLockAcquire(shmem_lockid, LW_EXCLUSIVE);
　:
　:
----------
</pre>

Regards,
kfuru

**Comment by okbob** [comment]
Hi
Should be fixed by 03feefa91e869db3f51a095d7f35d7e3fe577b8e commit.
Thank you for report and perfect diagnostics
