### ISSUE TITLE
An error occured in VARCHAR2 type column.

### ISSUE THREAD

**Issue by U-ikki** [orafce/orafce#54]
Hi,
When creating INDEX with VARCHAR 2 type column or executing sort, 
the following problem occurred.

    ERROR:  could not determine which collation to use for string comparison
    HINT:  Use the COLLATE clause to set the collation explicitly.

CentOS 7.3
PostgreSQL 9.6.2
orafce master branch

Procedure for reproducing:

    $ initdb -D ~/local/pg962/data --no-locale --encoding=utf8
    $ pg_ctl -D ~/local/pg962/data start
    $ psql postgres -c "create extension orafce"
    CREATE EXTENSION
    $ psql postgres -c "create table test(x varchar2(10))"
    CREATE TABLE
    $ psql postgres -c "insert into test values ('1'),('aaa')"
    INSERT 0 2
    $ psql postgres -c "create index ON test(x)"
    ERROR:  could not determine which collation to use for string comparison
    HINT:  Use the COLLATE clause to set the collation explicitly.
    STATEMENT: create index on test(x)
    ERROR:  could not determine which collation to use for string comparison
    HINT:  Use the COLLATE clause to set the collation explicitly.
    $ psql postgres -c "select * from test order by x"
    ERROR:  could not determine which collation to use for string comparison
    HINT:  Use the COLLATE clause to set the collation explicitly.
    STATEMENT: select * from test order by x
    ERROR:  could not determine which collation to use for string comparison
    HINT:  Use the COLLATE clause to set the collation explicitly.

I think that it is caused by not setting collatable to true with CREATE TYPE option.
A same error also occurs in NVARCHAR2.

The error is solved by the following fixes.

    $ git diff
    diff --git a/orafce--3.5.sql b/orafce--3.5.sql
    index ebebb14..341deaf 100644
    --- a/orafce--3.5.sql
    +++ b/orafce--3.5.sql
    @@ -2171,7 +2171,8 @@ receive = varchar2recv,
     send = varchar2send,
     category = 'S',
     typmod_in = varchar2typmodin,
    -typmod_out = varchar2typmodout
    +typmod_out = varchar2typmodout,
    +collatable = true
     );
     
     /* CREATE CAST */
    @@ -2373,7 +2374,8 @@ receive = nvarchar2recv,
     send = nvarchar2send,
     category = 'S',
     typmod_in = nvarchar2typmodin,
    -typmod_out = nvarchar2typmodout
    +typmod_out = nvarchar2typmodout,
    +collatable = true
     );
     
     /* CREATE CAST */

regards,
ikki

**Comment by okbob** [comment]
should be fixed. Thank you for report and for patch

**Comment by U-ikki** [comment]
Hi,
Thank you for quick response.
