### ISSUE TITLE
RDS version?

### ISSUE THREAD

**Issue by MichaelDBA** [orafce/orafce#55]
Is there a way we could package up all the objects in orafce so that we could install them on a RDS PG instance?

Looking at what is installed via create extension orafce, it appears I just need to consolidate all the objects like functions, types, casts, etc. and then just deploy them manually to an RDS PG instance database.  

Can this be done and if so what is the best way to accomplish this?

**Comment by okbob** [comment]
It can work only if Amazon will support Orafce. Orafce objects depends on C code compiled to dll file. Without installed this dll, the Orafce objects doesn't work

**Comment by MichaelDBA** [comment]
Thanks
