### ISSUE TITLE
make plvlex.c had some warning

### ISSUE THREAD

**Issue by smkingsoft** [orafce/orafce#58]
plvlex.c: In function ‘plvlex_tokens’:
plvlex.c:209: warning: call to function ‘orafce_sql_yyparse’ without a real prototype
plvlex.c:39: note: ‘orafce_sql_yyparse’ was declared here

plvlex.c:39:              extern int      orafce_sql_yyparse();
plvlex.c:209:		if (orafce_sql_yyparse(&lexems) != 0)

**Comment by okbob** [comment]
what is your configuration. I cannot to reply it.

**Comment by okbob** [comment]
I cannot to reproduce it
