### ISSUE TITLE
Crashes due to insufficent argument checking

### ISSUE THREAD

**Issue by anse1** [orafce/orafce#59]
Running sqlsmith on a DB with orafce installed yielded a couple of
core dumps due to insufficient argument checking in some functions.
The following statements crash trying to dereference a null pointer:

    select dbms_random.string(null, 42);
    select dbms_pipe.create_pipe(null);
    select plunit.assert_not_equals(1,2,3);

**Comment by okbob** [comment]
It really interesting tool. Reported issues should be fixed now. thank you.
