### ISSUE TITLE
rpad() add a half space to the beggining instead of the end when padding multi-byte character.

### ISSUE THREAD

**Issue by kato-sho** [orafce/orafce#60]
When padding multi-byte characters using rpad(), a half-width space was added at the beggining.Encoding is UTF8.

```sh
$cat test.sql 
select '|' || oracle.RPAD(TO_MULTI_BYTE('±'),10,'あ') || '|' from dual;
$psql -f test.sql postgres                                                                             
 
  ?column?   
--------------
 | ±ああああ|
(1 行)
```
In such a case, the oracle rpad() adds a half-width space at the end.
I use Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit.
```sh
SQL> select '|' || RPAD(TO_MULTI_BYTE('±'),10,'あ') || '|' from dual;

'|'||RPAD(TO_MULT
-----------------
|±ああああ |
```
I think this is an error of the orafce rpad(), is it correct?

**Comment by okbob** [comment]
yes, it is wrong - the space should not be appended from left.

**Comment by kato-sho** [comment]
> yes, it is wrong - the space should not be appended from left.
ok, I  make a patch. 
#61

**Comment by kato-sho** [comment]
Thank you for merging patch.
