### ISSUE TITLE
New release with PG10 support?

### ISSUE THREAD

**Issue by ChristophBerg** [orafce/orafce#62]
Hi,
I see that master has been updated to support PG 10, thanks for that.
Would you consider releasing a new version with these patches so I can update the packages for Debian and apt.postgresql.org?
Thanks!

**Comment by okbob** [comment]
2017-09-10 13:00 GMT+02:00 Christoph Berg <notifications@github.com>:

> Hi,
> I see that master has been updated to support PG 10, thanks for that.
> Would you consider releasing a new version with these patches so I can
> update the packages for Debian and apt.postgresql.org?
> Thanks!
>
sure

same week as PG 10 well be released, I'll release Orafce

Regards

Pavel

**Comment by ChristophBerg** [comment]
Well, pg10beta has already been released, and I'd ideally like to test the orafce packages before 10.0 is out. How about a beta release?

**Comment by ChristophBerg** [comment]
Ping :)

**Comment by okbob** [comment]
done

**Comment by ChristophBerg** [comment]
Thanks! Debian packages updated.
PS: I had to drop support for PostgreSQL 9.2 because it lacks pg_class.relispopulated.

**Comment by okbob** [comment]
2017-10-13 20:25 GMT+02:00 Christoph Berg <notifications@github.com>:

> Thanks! Debian packages updated.
> PS: I had to drop support for PostgreSQL 9.2 because it lacks
> pg_class.relispopulated.
>

It is unsupported already
