### ISSUE TITLE
could not find function "orafce_dump" 

### ISSUE THREAD

**Issue by mohammed-a-wadod** [orafce/orafce#65]
Hi, 
i am trying to create ext on postgresql 10 using this command 'CREATE EXTENSION orafce;'
and i am using windows 10, and i got this error 
**ERROR:  could not find function "orafce_dump" in file "C:\PostgreSQL\pg10\share\postgresql\extension\orafce-10-x64.dll"**

**Comment by mohammed-a-wadod** [comment]
and my orafce version is 3.6.1

**Comment by okbob** [comment]
please, try orafce 3.6.2 - http://okbob.blogspot.cz/2017/12/bugfix-of-precompiled-dll-of-orafce-362.html

**Comment by mohammed-a-wadod** [comment]
thanks
