### ISSUE TITLE
Wrong function name in COMMENT command

### ISSUE THREAD

**Issue by artemiuss** [orafce/orafce#74]
`CREATE FUNCTION oracle.dbtimezone()
RETURNS text
AS 'MODULE_PATHNAME','orafce_dbtimezone'
LANGUAGE C STABLE STRICT;
COMMENT ON FUNCTION oracle.sessiontimezone() IS 'Ruturns server time zone (orafce.timezone)';`

**Comment by okbob** [comment]
should be fixed by 9e0d1d0d430480a766be540ff608c3a9388227ff commit.
Thank you for report.
