### ISSUE TITLE
round() does not work correctly with TIMESTAMPs

### ISSUE THREAD

**Issue by artemiuss** [orafce/orafce#76]
Here is an example:
`select round(TIMESTAMP WITH TIME ZONE'12/08/1990 05:35:25.123456','DDD')`
The result:
`1990-12-08 00:00:00.123456+00`
As seen fractional seconds have not been rounded

**Comment by okbob** [comment]
Should be fixed by commit 3af70a28f6ab81f43c990fb5661df99a37328b8a
Thank you for report.
