### ISSUE TITLE
sqlparse.y:88:17: error: 'result' undeclared (first use in this function)

### ISSUE THREAD

**Issue by MAGE001** [orafce/orafce#77]
gcc -O3 -std=gnu99  -Wall -Wmissing-prototypes -Wpointer-arith  -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fno-aggressive-loop-optimizations  -I/usr/include/libxml2 -fpic -I. -I../../src/include -D_GNU_SOURCE  -I/home/hawq/apache-hawq-src-2.3.0.0-incubating/depends/libhdfs3/build/install/usr/local/hawq/include -I/home/hawq/apache-hawq-src-2.3.0.0-incubating/depends/libyarn/build/install/usr/local/hawq/include  -c -o sqlparse.o sqlparse.c
sqlparse.y: In function 'orafce_sql_yyparse':
sqlparse.y:88:17: error: 'result' undeclared (first use in this function)
      elements { *((void**)result) = $1; }
                 ^

**Comment by okbob** [comment]
What is your PostgreSQL version and gcc varsion? I cannot to reproduce it. Can you check master?

**Comment by okbob** [comment]
no more activity
