### ISSUE TITLE
Wrong comment on pg_catalog.substrb(varchar2, integer)

### ISSUE THREAD

**Issue by artemiuss** [orafce/orafce#78]
Here is it:

`CREATE OR REPLACE FUNCTION pg_catalog.substrb(varchar2, integer) RETURNS varchar2
AS 'bytea_substr_no_len'
LANGUAGE internal
STRICT IMMUTABLE;
COMMENT ON FUNCTION pg_catalog.substrb(varchar2, integer, integer) IS 'extracts specified number of bytes from the input varchar2 string starting at the specified byte position (1-based) and returns as a varchar2 string';`

(from orafce--3.7.sql)

**Comment by okbob** [comment]
Should be fixed by c3f66fc45856223d5757452894ec0554662a879d. 

Thank you for report.
