### ISSUE TITLE
Problem when installing on macOS 10.14.1 and Postgres 10.6

### ISSUE THREAD

**Issue by martinmanzo** [orafce/orafce#79]
Hi guys,

I'm trying to install orafce in a Mac that runs Postgres 10.6.
Running _make_ and _make install_ throwed no errors but when I run _CREATE EXTENSION orafce;_ I get this error:
```
WARNING:  operator attribute "function" not recognized
ERROR:  operator procedure must be specified
```

If I try to create the extension using pgAdmin orafce appears in the combo of available extensions but after the confirmation the same error is thrown.

Any ideas?

Thanks!

**Comment by okbob** [comment]
I am able to reproduce this issue. I have to diagnose it.

**Comment by okbob** [comment]
should be fixed now, please check.

**Comment by martinmanzo** [comment]
Well that was quick! It works now. Closing the issue.

Thanks @okbob!
