### ISSUE TITLE
Install Error when schema public doesn't exist

### ISSUE THREAD

**Issue by jacks33** [orafce/orafce#80]
Hello guys,

I try to create extension in another schema than public, using postgreSQL syntax:

db1=# CREATE EXTENSION IF NOT EXISTS orafce WITH SCHEMA common;
ERROR:  schema "public" does not exist

Creating public schema solves the issue it seems orafce create a view to  emulate Oracle 'dual' table.

Thank you

**Comment by okbob** [comment]
Hi

po 7. 1. 2019 v 15:45 odesílatel jacks33 <notifications@github.com> napsal:

> Hello guys,
>
> I try to create extension in another schema than public, using postgreSQL
> syntax:
>
> db1=# CREATE EXTENSION IF NOT EXISTS orafce WITH SCHEMA common;
> ERROR: schema "public" does not exist
>
> Creating public schema solves the issue it seems orafce create a view to
> emulate Oracle 'dual' table.
>

probably there will be more issues - orafce uses public schema too much and
doesn't support using other schema.

regards

Pavel

**Comment by jacks33** [comment]
ok, thanks for you feedback.
I'll try to create public schema then.
