### ISSUE TITLE
question on utl_file

### ISSUE THREAD

**Issue by jacks33** [orafce/orafce#84]
Hi,

I'm migrating a stored procedure wich invokes oracle utl_file.fopen.
Then there an exception block, above the translation from ora2pg

do you have these error codes in orafce ?

UTL_FILE.INVALID_PATH 
UTL_FILE.INVALID_MODE 
UTL_FILE.INVALID_OPERATION

Thank you very much for you help

        EXCEPTION
                when UTL_FILE.INVALID_PATH then
                        RAISE NOTICE 'INVALID PATH';
                        RAISE EXCEPTION '%', 'Ouverture du fichier de traces : INVALID_PATH' USING ERRCODE = '45010';
                when  UTL_FILE.INVALID_MODE then
                        RAISE NOTICE 'INVALID MODE';
                        RAISE EXCEPTION '%', 'Ouverture du fichier de traces : INVALID_MODE' USING ERRCODE = '45010';
                when  UTL_FILE.INVALID_OPERATION then
                        RAISE NOTICE 'INVALID OPERATION';
                        RAISE EXCEPTION '%', 'Ouverture du fichier de traces : INVALID_OPERATION' USING ERRCODE = '45010';
                when  others THEN
                        RAISE NOTICE 'OTHERS :Erreur SQL%.', DBMS_UTILITY.FORMAT_ERROR_STACK;
                        RAISE EXCEPTION '%', 'Erreur SQL' || DBMS_UTILITY.FORMAT_ERROR_STACK || '.' USING ERRCODE = '45010';

do you know code returned by orafce.fopen in this case ?

Thanks 
Best regarf

**Comment by okbob** [comment]
pá 22. 2. 2019 v 17:34 odesílatel Jack A. <notifications@github.com> napsal:

> Hi,
>
> I'm migrating a stored procedure wich invokes oracle utl_file.fopen.
> Then there an exception block, above the translation from ora2pg
>
> do you have these error codes in orafce ?
>
> UTL_FILE.INVALID_PATH
> UTL_FILE.INVALID_MODE
> UTL_FILE.INVALID_OPERATION
>
> Thank you very much for you help
>
>     EXCEPTION
>             when UTL_FILE.INVALID_PATH then
>                     RAISE NOTICE 'INVALID PATH';
>                     RAISE EXCEPTION '%', 'Ouverture du fichier de traces : INVALID_PATH' USING ERRCODE = '45010';
>             when  UTL_FILE.INVALID_MODE then
>                     RAISE NOTICE 'INVALID MODE';
>                     RAISE EXCEPTION '%', 'Ouverture du fichier de traces : INVALID_MODE' USING ERRCODE = '45010';
>             when  UTL_FILE.INVALID_OPERATION then
>                     RAISE NOTICE 'INVALID OPERATION';
>                     RAISE EXCEPTION '%', 'Ouverture du fichier de traces : INVALID_OPERATION' USING ERRCODE = '45010';
>             when  others THEN
>                     RAISE NOTICE 'OTHERS :Erreur SQL%.', DBMS_UTILITY.FORMAT_ERROR_STACK;
>                     RAISE EXCEPTION '%', 'Erreur SQL' || DBMS_UTILITY.FORMAT_ERROR_STACK || '.' USING ERRCODE = '45010';
>
> do you know code returned by orafce.fopen in this case ?
>
orafce raise just ERRCODE_RAISE_EXCEPTION P0001 - error message is different

please, read
https://github.com/orafce/orafce/blob/master/doc/sql_migration/sql_migration06.md

Pavel

**Comment by jacks33** [comment]
thank you.
Great documentation.

I have a question anyway. I have a package to translate and there is a global variable to reference the file:
gc_hdl UTL_FILE.FILE_TYPE;

I'm a thinking of changing signatures of the procedures adding an extra argument. What do you think ?

**Comment by okbob** [comment]
po 25. 2. 2019 v 10:30 odesílatel Jack A. <notifications@github.com> napsal:

> thank you.
> Great documentation.
>
> I have a question anyway. I have a package to translate and there is a
> global variable to reference the file:
> gc_hdl UTL_FILE.FILE_TYPE;
>
> I'm a thinking of changing signatures of the procedures adding an extra
> argument. What do you think ?
>
I am think nothing :-). I have not a idea about you are speaking. Can you
explain to more descriptive?

Pavel

**Comment by jacks33** [comment]
oh sorry. 
In one sentence =>  migrate a global variable (defined in a package) from oracle to postgres.

Here's what my package looks like:


PACKAGE k_log IS                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                             
	-- GLOBAL VARIABLE (log handler)
	gc_hdl UTL_FILE.FILE_TYPE;                                                                                                                                                                                                                                                                                                                  

	PROCEDURE p_openLog( av_filename IN VARCHAR2, av_filepath IN VARCHAR2, ac_level IN char) ;                                                                                                                                                                                                                                                  
	PROCEDURE p_debug( av_message IN VARCHAR2);                                                                                                                                                                                                                                                                                                 
....
END

Thank you

**Comment by okbob** [comment]
po 25. 2. 2019 v 13:31 odesílatel Jack A. <notifications@github.com> napsal:

> oh sorry.
> In one sentence => migrate a global variable (defined in a package) from
> oracle to postgres.
>
> Here's what my package looks like:
>
> PACKAGE k_log IS
>
> -- GLOBAL VARIABLE (log handler)
> gc_hdl UTL_FILE.FILE_TYPE;
>
> PROCEDURE p_openLog( av_filename IN VARCHAR2, av_filepath IN VARCHAR2, ac_level IN char) ;
> PROCEDURE p_debug( av_message IN VARCHAR2);
>
> ....
> END
>
ok

I am sorry, still I don't understand, what you want?

Pavel
