### ISSUE TITLE
Can't create extension orafce in Postgresql

### ISSUE THREAD

**Issue by mboiteau** [orafce/orafce#86]
Hi,
my os is redhat 7.3 and I am trying to install orafce to postgresql with psql version 9.2 and server version 9.6. Firstly, i try to install via the script orafce downloaded on github but after reading some topics about extension in postgresql, i understood that the installation only requires to run

> CREATE EXTENSION orafce;

in psql because the file in .sql is already present in extension directory of postgresql. But my problem is, when i run this commands it said

> ERROR: could not access file "$libdir/orafce: No such file or directory".

When i run the command

> SELECT * FROM pg_available_extensions;

to find which version of orafce is compatible with my postgresql version it said version "3.1". So i run the command

> CREATE EXTENSION orafce--3.1;

in my database with a superuser and this time it doesn't give any errors. But when i check the extension list in my database as the same user with

>  \dx

I don't see orafce and I can't use the orafce functions in my pgplsql code.

**Comment by okbob** [comment]
GitHub source doesn't contains binary (compiled) files. There is source code, that should be compiled first. You should to clone github repository, compile code, and install this extension as usual. Then run `make; sudo make install`

**Comment by mboiteau** [comment]
Thank for the response, can you be more clear about the installation procedure ? Because i already downloaded the github repository and put it in my include directory installation of postgre, launch make && make install and then 

> CREATE EXTENSION orafce--3.1

 but maybe i missed a step during the installation procedure.

**Comment by okbob** [comment]
what is result of make; make install?

**Comment by mboiteau** [comment]
- Result of `make USE_PGXS=1` :

> gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o putline.o putline.c
> gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o assert.o assert.c
> gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o plunit.o plunit.c
> gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o random.o random.c
> gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o aggregate.o aggregate.c
> gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o orafce.o orafce.c
> gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o varchar2.o varchar2.c
> gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o nvarchar2.o nvarchar2.c
> gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o charpad.o charpad.c
> gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2   -c -o charlen.o charlen.c
> gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -shared -o orafce.so parse_keyword.o convert.o file.o datefce.o magic.o others.o plvstr.o plvdate.o shmmc.o plvsubst.o utility.o plvlex.o alert.o pipe.o sqlparse.o putline.o assert.o plunit.o random.o aggregate.o orafce.o varchar2.o nvarchar2.o charpad.o charlen.o -L/usr/lib64 -Wl,-z,relro   -Wl,--as-needed

- Result of `make USE_PGXS=1 install` :

> /usr/bin/mkdir -p '/usr/lib64/pgsql'
> /usr/bin/mkdir -p '/usr/share/pgsql/extension'
> /usr/bin/mkdir -p '/usr/share/pgsql/extension'
> /usr/bin/mkdir -p '/usr/share/doc/pgsql/extension'
> /bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 755  orafce.so '/usr/lib64/pgsql/orafce.so'
> /bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./orafce.control '/usr/share/pgsql/extension/'
> /bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./orafce--3.8.sql ./orafce--3.2--3.3.sql ./orafce--3.3--3.4.sql ./orafce--3.4--3.5.sql ./orafce--3.5--3.6.sql ./orafce--3.6--3.7.sql ./orafce--3.7--3.8.sql  '/usr/share/pgsql/extension/'
> /bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./README.asciidoc ./COPYRIGHT.orafce ./INSTALL.orafce '/usr/share/doc/pgsql/extension/'

**Comment by okbob** [comment]
looks correct - so please try `drop extension orafce; create extension orafce`; there is `/usr/lib64/pgsql/orafce.so`. If it doesn't work, maybe your environment is broken - devel packages (directories) are for different version of Postgres that you are connect.
`create extension orafce` should be enough. If it requires some different, then some wrong is in your environment. Correct result looks like
<pre>
postgres=# create extension orafce;
CREATE EXTENSION
postgres=# \dn
      List of schemas
┌──────────────┬──────────┐
│     Name     │  Owner   │
╞══════════════╪══════════╡
│ dbms_alert   │ pavel    │
│ dbms_assert  │ pavel    │
│ dbms_output  │ pavel    │
│ dbms_pipe    │ pavel    │
│ dbms_random  │ pavel    │
│ dbms_utility │ pavel    │
│ oracle       │ pavel    │
│ plunit       │ pavel    │
│ plvchr       │ pavel    │
│ plvdate      │ pavel    │
│ plvlex       │ pavel    │
│ plvstr       │ pavel    │
│ plvsubst     │ pavel    │
│ public       │ postgres │
│ utl_file     │ pavel    │
└──────────────┴──────────┘
(15 rows)
</pre>

**Comment by okbob** [comment]
Maybe you have more installed versions of PostgreSQL server?

**Comment by mboiteau** [comment]
```
p05d01=# create extension orafce;
ERROR:  could not access file "$libdir/orafce": No such file or directory
```

**Comment by mboiteau** [comment]
I don't think that i have more installed versions of PostgreSQL server but how do i check ?

**Comment by okbob** [comment]
út 4. 6. 2019 v 17:14 odesílatel mboiteau <notifications@github.com> napsal:

> I don't think that i have more installed versions of PostgreSQL server but
> how do i check ?
>
check installed rpm packages - maybe some was installed directly without
packages.

**Comment by mboiteau** [comment]
ok so there is the result of `rpm -qa | grep postgres` :

```
postgresql96-pltcl-9.6.8-1PGDG.rhel7.x86_64
postgresql-devel-9.2.24-1.el7_5.i686
postgresql96-plpython-9.6.8-1PGDG.rhel7.x86_64
postgresql-libs-9.2.24-1.el7_5.x86_64
postgresql96-libs-9.6.8-1PGDG.rhel7.x86_64
postgresql96-test-9.6.8-1PGDG.rhel7.x86_64
postgresql96-contrib-9.6.8-1PGDG.rhel7.x86_64
postgresql-9.2.24-1.el7_5.x86_64
postgresql96-plperl-9.6.8-1PGDG.rhel7.x86_64
postgresql-9.2.24-1.el7_5.i686
postgresql96-devel-9.6.8-1PGDG.rhel7.x86_64
postgresql96-server-9.6.8-1PGDG.rhel7.x86_64
postgresql96-debuginfo-9.6.8-1PGDG.rhel7.x86_64
postgresql96-9.6.8-1PGDG.rhel7.x86_64
postgresql96-docs-9.6.8-1PGDG.rhel7.x86_64
postgresql-devel-9.2.24-1.el7_5.x86_64
postgresql-libs-9.2.24-1.el7_5.i686
```
I noticed that i have multiple version so maybe that's the problem ?

**Comment by okbob** [comment]
probably - orafce is compiled and installed against different pg than you connect

**Comment by mboiteau** [comment]
Ok it's strange because i checked my version of pg in root which i used for the installation of orafce and my version in the user postgres which i used for my database and it seems to have the same version number.

User root pg version :
```
[dv05dasc04:root:null]$psql -U postgres postgres
psql (9.2.24, server 9.6.8)
```

User postgres pg  version :
```
[dv05dasc04:postgres:pgserver01]$psql
psql (9.2.24, server 9.6.8)
```

**Comment by mboiteau** [comment]
I think my problem come from this error when i run `CREATE EXTENSION orafce` :
`ERROR:  could not access file "$libdir/orafce": No such file or directory`

Do you have a solution for this issue ?

**Comment by mboiteau** [comment]
ok finally i find the problem, the .so was not present in my libdir path so i just cp the file into this directory and it solves my problem now i have orafce in my database ! Thanks for your help @okbob !

**Comment by okbob** [comment]
The error message is absolutely clear - the running Postgres has not a access to directory with compiled files.

You should to check if `pg_config` is related for running postgres. 

you can try `pg_config --version`

**Comment by okbob** [comment]
maybe you have set LD_LIBRARY_PATH too

**Comment by suvaytranh** [comment]
> ```
> p05d01=# create extension orafce;
> ERROR:  could not access file "$libdir/orafce": No such file or directory
> ```
@okbob @mboiteau 
I also got this error. Could you please give me some instructions to fix this? I am installing orafce on Windows 10 environment and PostgreSQL version is 13
