### ISSUE TITLE
Add dbms_sql

### ISSUE THREAD

**Issue by rouxelphilippe** [orafce/orafce#88]
Do you think possible to add package dbms_sql?

[https://docs.oracle.com/cd/B28359_01/appdev.111/b28419/d_sql.htm#BABEDAHF](url)

**Comment by okbob** [comment]
It is possible, and I am open accept a patch if somebody send it. I have not a free time for this target.

**Comment by okbob** [comment]
I wrote separate extension dbms_sql https://github.com/okbob/dbms_sql

**Comment by remduv** [comment]
Hello Pavel, I just tested it on a simple case and it works great !
Nice job, I hope it will make it to the orafce code base.
I will try to test it some more.
