### ISSUE TITLE
Issue with UTL_FILE.PUT_LINE()

### ISSUE THREAD

**Issue by mboiteau** [orafce/orafce#89]
Hi i am migrating a function from oracle to postgresql. 

        `CREATE OR REPLACE FUNCTION pda.purge ( IN_REQ_EXPORT text, IN_HEAD_EXPORT text, IN_TABLE       text, IN_NAME text, IN_CONDITION text, OUT_ERREUR OUT integer) AS $body$
       DECLARE

	reqSelect varchar(10000) := '';
	reqDelete varchar(10000) := '';
	csv_file UTL_FILE.FILE_TYPE;
	ligne varchar(10000);
	records refcursor;

        BEGIN
	OUT_ERREUR:=0;

	reqSelect := IN_REQ_EXPORT || ' WHERE ' || IN_CONDITION;
	reqDelete := ' DELETE FROM ' || IN_TABLE || ' WHERE ' || IN_CONDITION;

	OPEN records FOR EXECUTE reqSelect;
        FETCH records INTO ligne;

	IF Not records%NOTFOUND THEN

		csv_file := UTL_FILE.FOPEN(location     => 'EXTRACT_DIR',
		                           filename     => IN_NAME || '_' || to_char(clock_timestamp(), 'yyyyMMddhh24miss') || '.csv',
		                           open_mode    => 'w',
		                           max_linesize => 32767);

		UTL_FILE.PUT_LINE(file  => csv_file,
                      buffer => IN_HEAD_EXPORT);`

And it crash at the line `UTL_FILE.PUT_LINE(file  => csv_file,
                      buffer => IN_HEAD_EXPORT);`

reporting this error : `ERROR:  syntax error at or near "UTL_FILE"`

I have the orafce well installed and all the other functions of UTL_FILE work well.
`# \dx
                                                  List of installed extensions
  Name   | Version |   Schema   |                                          Description
---------+---------+------------+-----------------------------------------------------------------------------------------------
 orafce  | 3.1     | public     | Functions and operators that emulate a subset of functions and packages from the Oracle RDBMS
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)`
I can't get what i am doing wrong.

**Comment by okbob** [comment]
čt 20. 6. 2019 v 12:33 odesílatel mboiteau <notifications@github.com>
napsal:

> Hi i am migrating a function from oracle to postgresql.
>
> `CREATE OR REPLACE FUNCTION pda.purge ( IN_REQ_EXPORT text, IN_HEAD_EXPORT
> text, IN_TABLE text, IN_NAME text, IN_CONDITION text, OUT_ERREUR OUT
> integer) AS $body$
> DECLARE
>
> reqSelect varchar(10000) := '';
> reqDelete varchar(10000) := '';
> csv_file UTL_FILE.FILE_TYPE;
> ligne varchar(10000);
> records refcursor;
>
> BEGIN
> OUT_ERREUR:=0;
>
> -- construction de la requete select d'export des elements
> reqSelect := IN_REQ_EXPORT || ' WHERE ' || IN_CONDITION;
>
> -- construction de la requete delete
> reqDelete := ' DELETE FROM ' || IN_TABLE || ' WHERE ' || IN_CONDITION;
>
> -- recuperation des elements a exporter
> OPEN records FOR EXECUTE reqSelect;
>
> FETCH records INTO ligne;
>
> IF Not records%NOTFOUND THEN
>
> 	-- ouverture du fichier d'export
> 	csv_file := UTL_FILE.FOPEN(location     => 'EXTRACT_DIR',
> 	                           filename     => IN_NAME || '_' || to_char(clock_timestamp(), 'yyyyMMddhh24miss') || '.csv',
> 	                           open_mode    => 'w',
> 	                           max_linesize => 32767);
>
> 	-- ecriture de la ligne de titre
> 	UTL_FILE.PUT_LINE(file  => csv_file,
>                   buffer => IN_HEAD_EXPORT);`
>
> And it crash at the line UTL_FILE.PUT_LINE(file => csv_file, buffer =>
> IN_HEAD_EXPORT);
>
UTL_FILE.PUT_LINE is void function in Postgres. Void functions are called
by PERFORM statement.

It should be like

  PERFORM UTL_FILE.PUT_LINE(...)

**Comment by mboiteau** [comment]
Thanks ! Now i have error `ERROR:  syntax error at or near "UTL_FILE"
LINE 70:   WHEN UTL_FILE.INVALID_PATH THEN
`
when trying to catch exception, any idea about what is this error cause ?

**Comment by okbob** [comment]
Hi

Postgres has not named custom exceptions, you can catch this exception only
via SQLSTATE
https://github.com/orafce/orafce/blob/master/doc/sql_migration/sql_migration06.md

UTL_FILE.INVALID_PATH


I am sure so this syntax is not postgres

IF Not records%NOTFOUND THEN



čt 20. 6. 2019 v 13:19 odesílatel mboiteau <notifications@github.com>
napsal:

**Comment by mboiteau** [comment]
Thanks for the link, the doc is very usefull and helped me to resolve my problem.
What makes you say that this syntax is not postgres ? Because i don't have any error on importing the function about that

**Comment by okbob** [comment]
čt 20. 6. 2019 v 17:01 odesílatel mboiteau <notifications@github.com>
napsal:

> Thanks for the link, the doc is very usefull and helped me to resolve my
> problem.
> What makes you say that this syntax is not postgres ? Because i don't have
> any error on importing the function about that
>
It probably raises runtime error.

Postgres doesn't support this syntax on cursors

http://www.postgresqltutorial.com/plpgsql-cursor/

Good to start to read plpgsql documentation - there are lot of differences
from PL/SQL

https://www.postgresql.org/docs/current/plpgsql.html
