### ISSUE TITLE
SUBSTR with negative values

### ISSUE THREAD

**Issue by supermarconinja** [orafce/orafce#90]
This query: select SUBSTR('abcdefg',-5,4) from dual;
In Oracle gets back: "cdef"
In PostgreSQL gets back an empty string.

**Comment by okbob** [comment]
You are calling builtin Postgres's function `substr`. Unfortunately, nobody can overload (from security reasons) builtin function. If you want to call Orafce's implementation, you should to use schema.functionname pattern (schema `oracle`)
<pre>
postgres=# select SUBSTR('abcdefg',-5,4) ;
┌────────┐
│ substr │
╞════════╡
│        │
└────────┘
(1 row)

postgres=# select oracle.SUBSTR('abcdefg',-5,4) ;
┌────────┐
│ substr │
╞════════╡
│ cdef   │
└────────┘
(1 row)
</pre>
