### ISSUE TITLE
Windows build of orafce 3.8 ?

### ISSUE THREAD

**Issue by jncanches** [orafce/orafce#95]
First of all, thanks for this awesome work !
I spent hours trying to compile orafce using Visual Studio on Windows (yes I know...), without success. 
I just found the 3.6.2 version compiled for Windows in this blogpost http://okbob.blogspot.com/2017/12/bugfix-of-precompiled-dll-of-orafce-362.html (excellent blog by the way ! ).
Is there a link somewhere with the latest 3.8 built for Windows (dll) ?

Thank you

**Comment by okbob** [comment]
Hi

so 12. 10. 2019 v 1:08 odesílatel jncanches <notifications@github.com>
napsal:

> First of all, thanks for this awesome work !
> I spent hours trying to compile orafce using Visual Studio on Windows (yes
> I know...), without success.
> I just found the 3.6.2 version compiled for Windows in this blogpost
> http://okbob.blogspot.com/2017/12/bugfix-of-precompiled-dll-of-orafce-362.html
> (excellent blog by the way ! ).
> Is there a link somewhere with the latest 3.8 built for Windows (dll) ?
>
Unfortunately I don't use a windows now, and my build environment for
windows is obsolete.

When I did build on windows I use setup described by
https://www.2ndquadrant.com/en/blog/compiling-postgresql-extensions-visual-studio-windows/

**Comment by jncanches** [comment]
Thanks you for your answer. I followed this tutorial toi. Without success. There is a very weird behavior, not explained in the tuto. I think some .lib are missing in the path. The tuto only says we have to add postgres.lib but when building, a lot of fonctions are not found. 
Perhaps I have to try with a VS 2010 version...

**Comment by okbob** [comment]
I did build of orafce 3.8 for windows - http://okbob.blogspot.com/2019/10/precompiled-libraries-for-orafce-38-for.html
