### ISSUE TITLE
The public schema is hard coded

### ISSUE THREAD

**Issue by danielwestermann** [orafce/orafce#96]
Hi,

just compiled an installed from source code. When trying to add the extension this is the result:

```
devel=# create extension orafce with schema booking_app;
ERROR:  schema "public" does not exist
```

This is on PostgreSQL 12 although I don't think it really matters. Looking at the sql files that got installed:

```
postgres@dbi-pg-developer:/u01/app/postgres/product/12/db_0/share/extension/ [pg12.0] grep "public" *orafce*
orafce--3.9.sql:CREATE VIEW public.dual AS SELECT 'X'::varchar AS dummy;
orafce--3.9.sql:REVOKE ALL ON public.dual FROM PUBLIC;
orafce--3.9.sql:GRANT SELECT, REFERENCES ON public.dual TO PUBLIC;
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, text)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, text, text)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, text, anyelement, text)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, text, anyelement, text, text)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, text, anyelement, text, anyelement, text)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, text, anyelement, text, anyelement, text, text)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bpchar)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bpchar, bpchar)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bpchar, anyelement, bpchar)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bpchar, anyelement, bpchar, bpchar)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bpchar, anyelement, bpchar, anyelement, bpchar)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bpchar, anyelement, bpchar, anyelement, bpchar, bpchar)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, integer)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, integer, integer)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, integer, anyelement, integer)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, integer, anyelement, integer, integer)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, integer, anyelement, integer, anyelement, integer)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, integer, anyelement, integer, anyelement, integer, integer)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bigint)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bigint, bigint)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bigint, anyelement, bigint)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bigint, anyelement, bigint, bigint)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bigint, anyelement, bigint, anyelement, bigint)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bigint, anyelement, bigint, anyelement, bigint, bigint)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, numeric)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, numeric, numeric)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, numeric, anyelement, numeric)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, numeric, anyelement, numeric, numeric)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, numeric, anyelement, numeric, anyelement, numeric)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, numeric, anyelement, numeric, anyelement, numeric, numeric)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, date)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, date, date)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, date, anyelement, date)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, date, anyelement, date, date)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, date, anyelement, date, anyelement, date)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, date, anyelement, date, anyelement, date, date)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, time)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, time, time)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, time, anyelement, time)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, time, anyelement, time, time)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, time, anyelement, time, anyelement, time)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, time, anyelement, time, anyelement, time, time)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamp)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamp, timestamp)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamp, anyelement, timestamp)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamp, anyelement, timestamp, timestamp)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamp, anyelement, timestamp, anyelement, timestamp)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamp, anyelement, timestamp, anyelement, timestamp, timestamp)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamptz)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamptz, timestamptz)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamptz, anyelement, timestamptz)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamptz, anyelement, timestamptz, timestamptz)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamptz, anyelement, timestamptz, anyelement, timestamptz)
orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamptz, anyelement, timestamptz, anyelement, timestamptz, timestamptz)
```

Is that intentional?

Best regards
Daniel

**Comment by okbob** [comment]
Hi

po 28. 10. 2019 v 17:32 odesílatel danielwestermann <
notifications@github.com> napsal:

> Hi,
>
> just compiled an installed from source code. When trying to add the
> extension this is the result:
>
> devel=# create extension orafce with schema booking_app;
> ERROR:  schema "public" does not exist
>
> This is on PostgreSQL 12 although I don't think it really matters. Looking
> at the sql files that got installed:
>
> postgres@dbi-pg-developer:/u01/app/postgres/product/12/db_0/share/extension/ [pg12.0] grep "public" *orafce*
> orafce--3.9.sql:CREATE VIEW public.dual AS SELECT 'X'::varchar AS dummy;
> orafce--3.9.sql:REVOKE ALL ON public.dual FROM PUBLIC;
> orafce--3.9.sql:GRANT SELECT, REFERENCES ON public.dual TO PUBLIC;
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, text)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, text, text)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, text, anyelement, text)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, text, anyelement, text, text)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, text, anyelement, text, anyelement, text)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, text, anyelement, text, anyelement, text, text)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bpchar)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bpchar, bpchar)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bpchar, anyelement, bpchar)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bpchar, anyelement, bpchar, bpchar)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bpchar, anyelement, bpchar, anyelement, bpchar)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bpchar, anyelement, bpchar, anyelement, bpchar, bpchar)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, integer)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, integer, integer)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, integer, anyelement, integer)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, integer, anyelement, integer, integer)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, integer, anyelement, integer, anyelement, integer)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, integer, anyelement, integer, anyelement, integer, integer)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bigint)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bigint, bigint)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bigint, anyelement, bigint)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bigint, anyelement, bigint, bigint)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bigint, anyelement, bigint, anyelement, bigint)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, bigint, anyelement, bigint, anyelement, bigint, bigint)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, numeric)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, numeric, numeric)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, numeric, anyelement, numeric)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, numeric, anyelement, numeric, numeric)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, numeric, anyelement, numeric, anyelement, numeric)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, numeric, anyelement, numeric, anyelement, numeric, numeric)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, date)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, date, date)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, date, anyelement, date)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, date, anyelement, date, date)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, date, anyelement, date, anyelement, date)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, date, anyelement, date, anyelement, date, date)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, time)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, time, time)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, time, anyelement, time)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, time, anyelement, time, time)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, time, anyelement, time, anyelement, time)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, time, anyelement, time, anyelement, time, time)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamp)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamp, timestamp)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamp, anyelement, timestamp)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamp, anyelement, timestamp, timestamp)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamp, anyelement, timestamp, anyelement, timestamp)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamp, anyelement, timestamp, anyelement, timestamp, timestamp)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamptz)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamptz, timestamptz)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamptz, anyelement, timestamptz)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamptz, anyelement, timestamptz, timestamptz)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamptz, anyelement, timestamptz, anyelement, timestamptz)
> orafce--3.9.sql:CREATE FUNCTION public.decode(anyelement, anyelement, timestamptz, anyelement, timestamptz, anyelement, timestamptz, timestamptz)
>
> Is that intentional?
>
Orafce is older than "new" extensions. There was not a possibility to
install extension to schema. And it doesn't support it too, and will not do
it in future.

Orafce uses schema like packages and because implements more "packages",
then uses hard coded schemas. I don't plan to change it now. I know so
there is some functions in public schema, what is wrong - now I can use
schema "oracle", but I cannot to change it due possible compatibility
issues. I though about it, and I waiting on end of support 9.4, 9.5, 9.6.
Then I'll release cleaned Orafce 4.0 where public schema will not be used .

So I am sorry - orafce needs public schema. Probably fix is not hard - and
you can do it for self. In this moment, I would not to break (or risk
breaking) anything.

Still there is some wrong, because in orafce.control file there is
"relocatable = false", so create extension with schema should fail.

Regards

Pavel

**Comment by danielwestermann** [comment]
Thanks for the feedback Pavel. Fine for me.
Best regards
Daniel
