### ISSUE TITLE
to_char(11::double precision) = '11' is not correct

### ISSUE THREAD

**Issue by snzip** [orafce/orafce#97]
ppmdev=# select to_char(11::double precision) = '11';
 ?column?
----------
 f
(1 row)

**Comment by okbob** [comment]
should be fixed by last commit - please, check.

**Comment by snzip** [comment]
thanks:)  when will you release a new version?

**Comment by okbob** [comment]
Hi

po 9. 12. 2019 v 5:26 odesílatel Michael Song <notifications@github.com>
napsal:

> thanks:) when will you release a new version?
>
I will check if there are not any other errors, and probably after New
Year, I'll release this bugfix

Pavel

**Comment by snzip** [comment]
thanks
