### ISSUE TITLE
make clean error 

### ISSUE THREAD

**Issue by qzren1982** [orafce/orafce#98]
make clean command will delete *.h files
Error reported in the second recompilation

postgres@localhost:~/source/postgresql-12.1/contrib/orafce-VERSION_3_8_0$ make clean
rm -f orafce.so   liborafce.a  liborafce.pc
rm -f parse_keyword.o convert.o file.o datefce.o magic.o others.o plvstr.o plvdate.o shmmc.o plvsubst.o utility.o plvlex.o alert.o pipe.o sqlparse.o putline.o assert.o plunit.o random.o aggregate.o orafce.o varchar2.o nvarchar2.o charpad.o charlen.o parse_keyword.bc convert.bc file.bc datefce.bc magic.bc others.bc plvstr.bc plvdate.bc shmmc.bc plvsubst.bc utility.bc plvlex.bc alert.bc pipe.bc sqlparse.bc putline.bc assert.bc plunit.bc random.bc aggregate.bc orafce.bc varchar2.bc nvarchar2.bc charpad.bc charlen.bc

rm -rf sqlparse.c sqlparse.h sqlscan.c y.tab.c y.tab.h

rm -rf results/ regression.diffs regression.out tmp_check/ tmp_check_iso/ log/ output_iso/

**Comment by okbob** [comment]
It should be fixed now. Thank you for report
