### ISSUE TITLE
[BUG] to_single_byte to_multi_byte conversion different from oracle

### ISSUE THREAD

**Issue by qiuyuhang** [orafce/orafce#99]
~ and \ conversion work different from Oracle.

```sql
SELECT to_multi_byte('~'); -- ∼(\342\210\274) in oracle
SELECT to_multi_byte('\'); -- ＼(\357\274\274) in oracle
```

**Comment by okbob** [comment]
backslash was probably wrong, and I fixed it. But for tilde I am not sure what is correct value

Now Orafce returns fullwidth tilde - https://graphemica.com/%EF%BD%9E what looks correct. Oracle returns https://graphemica.com/%E2%88%BC tilde - that looks not too much correct. 

In this case I would not to break compatibility for current Orafce applications. So I will note to Orafce code, and somebody can recompile Orafce with own fix.

**Comment by okbob** [comment]
please look to commit 63f5dd24ef325eda9d5555de0d3af2b2eabbd787

**Comment by qiuyuhang** [comment]
Agree with you. Fullwidth tilde should be right.

**Comment by qiuyuhang** [comment]
Another conversion diff.

```sql
-- EUC_JP encoding
select to_multi_byte('`'); -- ’(\241\307) in oracle, ‘(\241\306) in oraface.
```

The sql I used to get the muti_byte list. The rest conversions are all the same.
```sql
select ascii, dump(m, 1008) oct, s single, m multi, lengthb(s) single_length, lengthb(m) multi_length
from (select ascii, chr(ascii) s, to_multi_byte(chr(ascii)) as m
      from (select rownum + 31 ascii
            from dual
            connect by rownum <= 95));
```

**Comment by okbob** [comment]
po 24. 2. 2020 v 10:29 odesílatel 邱宇航 <notifications@github.com> napsal:

> Another conversion diff.
>
> -- EUC_JP encoding
> select to_multi_byte('`'); -- ’(\241\307) in oracle, ‘(\241\306) in oraface.
>
> The sql I used to get the muti_byte list. The rest conversions are all the
> same.
>
> select ascii, dump(m, 1008) oct, s single, m multi, lengthb(s) single_length, lengthb(m) multi_length
> from (select ascii, chr(ascii) s, to_multi_byte(chr(ascii)) as m
>
>       from (select rownum + 31 ascii
>
>             from dual
>
>             connect by rownum <= 95));
>
>
This is simillar case, when I don't know if I have to fix it.

‘ LEFT SINGLE QUOTATION MARK (U+2018)
<https://www.fileformat.info/info/unicode/char/2018/index.htm> a1c6
(Postgres) UTF8 e28098
’ RIGHT SINGLE QUOTATION MARK (U+2019)
<https://www.fileformat.info/info/unicode/char/2019/index.htm> a1c7
(Oracle) UTF8 e28099

The most correct value looks like
https://www.fileformat.info/info/charset/EUC-JP/list.htm
https://www.fileformat.info/info/unicode/char/0060/index.htm

But it is not any value .. So I checked UTF8 and the mapping there
\342\200\230 ..

So this is second value where Oracle something else, but Oracle isn't
consistent with self, and then I think so Postgres value is better -
minimally it returns for UTF8 and for EUC_JP same value.

So although Orafce returns different value, it is not clean bug, and I am
not sure If I have to change Orafce mapping. It is hard questions - if I
change it, I can break some applications that use Orafce now.

Please, look to commit 177880dc94e71d802a9ee8cfde89ebcd67844ccd

**Comment by qiuyuhang** [comment]
Yes, you're right.
